/* =====================================================================
   TRỢ LÝ AI — nhận định, cảnh báo, đề xuất điều chỉnh kế hoạch sau mỗi báo cáo TikTok tuần
   Web chạy bộ luật phân tích số liệu; nhận định gửi BOT CỦA PHÒNG BAN (OpenClaw, combo AI ở 9router) — xem bots.js.
   ===================================================================== */
const AI_SRC_T9="t9file";
function aiShape(d){if(!d.ai)d.ai={state:{},log:[],src:"",tg:{bat:false,gio:"08:00",nhan:"Chị Hoa, Lead Content & Media"}};if(!d.ttWeeks)d.ttWeeks=[];return d}
function aiWeeks(){const d=D(),L=(d.ttWeeks||[]).slice();if(typeof T9FILE!=="undefined")L.unshift({key:AI_SRC_T9,label:"Tuần 24–30/9 (file thật)",tu:"2026-09-24",den:"2026-09-30",recs:T9FILE.recs.map(r=>[r[0],guessSku(r[3])||guessSku(r[2])||"KHAC",r[7],r[6],r[4],String(r[1]).slice(0,10),/[#@]/.test(String(r[2]))?1:0,String(r[2]).slice(0,80),r[8]||""])});return L}
const ttUrl=v=>`https://www.tiktok.com/@${v[8]||"aillavietnamstore"}/video/${v[0]}`;
const vidRef=v=>v?{id:v[0],url:ttUrl(v),ten:v[7]||v[0]}:null;
function aiAnalyze(wk,prev){
  const d=D(),T=d.kpiTargets,pot=d.settings.potential||30,R=wk.recs,tot=R.reduce((a,r)=>a+r[2],0)||1,P=d.pillars.filter(p=>p.kenh==="TikTok chính"),khT=P.reduce((a,p)=>a+p.kh,0)||1;
  const by={};R.forEach(r=>{const o=by[r[1]]=by[r[1]]||{sku:r[1],gmv:0,don:0,n:0,nOrd:0,top:null};o.gmv+=r[2];o.don+=r[3];o.n++;if(r[3]>0)o.nOrd++;if(!o.top||r[2]>o.top[2])o.top=r});
  const pb=k=>prev?prev.recs.filter(r=>r[1]===k).reduce((a,r)=>a+r[2],0):null;
  const rows=Object.values(by).map(o=>{const pk=P.filter(p=>p.sku===o.sku).reduce((a,p)=>a+p.kh,0),cg=d.cards.filter(c=>c.sku===o.sku&&c.kenh==="TikTok chính"&&c.step==="cg").length,shG=o.gmv/tot,shP=pk/khT,p0=pb(o.sku);return {...o,pk,cg,shG,shP,ratio:shP?shG/shP:(shG>0.05?9:0),wow:p0?((o.gmv-p0)/p0):null,huong:(prods().find(p=>p.k===o.sku)||{}).huong||"—"}}).sort((a,b)=>b.gmv-a.gmv);
  P.forEach(p=>{if(!rows.some(r=>r.sku===p.sku))rows.push({sku:p.sku,gmv:0,don:0,n:0,nOrd:0,top:null,pk:P.filter(x=>x.sku===p.sku).reduce((a,x)=>a+x.kh,0),cg:d.cards.filter(c=>c.sku===p.sku&&c.kenh==="TikTok chính"&&c.step==="cg").length,shG:0,shP:p.kh/khT,ratio:0,wow:null,huong:(prods().find(x=>x.k===p.sku)||{}).huong||"—"})});
  const I=[],key=s=>wk.key+"|"+s,topV=R.slice().sort((a,b)=>b[2]-a[2]),cloneV=topV.filter(v=>v[3]>=pot*2).slice(0,3),isClone=v=>v&&cloneV.some(c=>c[0]===v[0]);
  const hot=rows.filter(r=>r.pk&&(r.ratio>=1.5&&r.shG>=0.1||r.wow!=null&&r.wow>=0.5&&r.gmv>tot*0.05)),cold=rows.filter(r=>r.pk&&r.ratio<0.5&&r.huong!=="Đẩy mạnh"&&r.cg>0);
  hot.forEach(h=>{const want=Math.min(15,Math.max(3,Math.round(h.pk*0.3))),pool=cold.reduce((a,c)=>a+Math.min(c.cg,Math.ceil(c.pk*0.3)),0),n=Math.min(want,pool);const from=[];let left=n;cold.slice().sort((a,b)=>a.ratio-b.ratio).forEach(c=>{if(left<=0)return;const t=Math.min(left,c.cg,Math.ceil(c.pk*0.3));if(t>0){from.push({sku:c.sku,n:t});left-=t}});
    I.push({key:key("hot-"+h.sku),lv:"hot",title:`${sk(h.sku).n} đang ra số tốt — đẩy thêm video`,why:`Chiếm ${Math.round(h.shG*100)}% doanh thu video tuần (${tr(h.gmv)}, ${nf(h.don)} đơn) trong khi kế hoạch chỉ dành ${Math.round(h.shP*100)}% số video (${h.pk} video). Hướng hiện tại: ${h.huong}.${h.wow!=null?` So tuần trước: ${h.wow>=0?"+":""}${Math.round(h.wow*100)}%.`:""}${h.top&&!isClone(h.top)?` Video kéo nhiều nhất: "${h.top[7]||h.top[0]}" ${tr(h.top[2])}.`:h.top?" Đề xuất nhân bản video kéo số nằm ở thẻ riêng bên dưới.":""}`,vid:h.top&&!isClone(h.top)?vidRef(h.top):null,
      act:n?{type:"realloc",to:h.sku,from,n,hot:h.top?h.top[0]:"",hotTen:h.top?(h.top[7]||""):""}:null,actTxt:n?`Chuyển ${n} thẻ chưa giao sang ${sk(h.sku).n} (tuyến "Nhân bản winner"): ${from.map(f=>`${sk(f.sku).n} −${f.n}`).join(", ")}.${h.huong!=="Đẩy mạnh"?` Đổi hướng ${sk(h.sku).n} thành "Đẩy mạnh".`:""}`:`Chưa có thẻ trống ở nhóm chậm để chuyển — tăng số video ${sk(h.sku).n} bằng cách thêm tuyến ở Pillar & tuyến.`})});
  cold.filter(c=>!hot.length).forEach(c=>I.push({key:key("cold-"+c.sku),lv:"warn",title:`${sk(c.sku).n} ra số thấp so với số video dành cho nó`,why:`Chiếm ${Math.round(c.shG*100)}% doanh thu nhưng chiếm ${Math.round(c.shP*100)}% số video kế hoạch (${c.pk} video), ${c.cg} thẻ còn chưa giao.`,act:null,actTxt:"Giữ nhịp tối thiểu, đổi góc nội dung; nếu tuần sau vẫn thấp thì chuyển bớt thẻ sang nhóm đang lên."}));
  rows.filter(r=>r.huong==="Đẩy mạnh"&&r.pk&&r.ratio<0.5).forEach(r=>I.push({key:key("push-"+r.sku),lv:"warn",title:`${sk(r.sku).n} đang "Đẩy mạnh" nhưng chưa ra số`,why:`${r.n} video có số, ${r.nOrd} video ra đơn, doanh thu ${tr(r.gmv)} (${Math.round(r.shG*100)}% tổng) so với ${Math.round(r.shP*100)}% số video kế hoạch.`,act:null,actTxt:"Không cắt (chị đã chốt đẩy mạnh). Đề xuất: đổi hook 3 giây đầu sang cảnh trước/sau, nhờ Digital chạy test 3 video, xem lại giá và combo."}));
  const conc=topV[0]&&topV[0][2]/tot>0.5;
  cloneV.forEach(v=>I.push({key:key("clone-"+v[0]),lv:"hot",vid:vidRef(v),title:`Video "${(v[7]||v[0]).slice(0,50)}" đang bán mạnh — nhân bản`,why:`${nf(v[3])} đơn, ${tr(v[2])} trong tuần (${Math.round(v[2]/tot*100)}% doanh thu). Sản phẩm: ${sk(v[1]).n}. Đăng ${v[5]||"—"}.${conc&&v===topV[0]?` ⚠️ Doanh thu đang phụ thuộc video này (${Math.round(v[2]/tot*100)}%) — video chững là doanh thu tụt mạnh, nên nhân bản sớm và tìm thêm 2–3 video win mới.`:""}`,act:{type:"clone",id:v[0],sku:v[1],ten:v[7]||"",n:4},actTxt:`Tạo 4 thẻ "Nhân bản winner" giữ cảnh và câu mở, đổi người nói / bối cảnh, giao trong 7 ngày tới.`}));
  if(conc&&!isClone(topV[0]))I.push({key:key("conc"),lv:"warn",vid:vidRef(topV[0]),title:"Doanh thu phụ thuộc 1 video",why:`Video đứng đầu chiếm ${Math.round(topV[0][2]/tot*100)}% doanh thu tuần. Video này mà chững là doanh thu tụt mạnh.`,act:null,actTxt:"Ưu tiên nhân bản video này và tìm 2–3 video win mới trong tháng."});
  const team=R.filter(r=>r[6]),zero=team.filter(r=>r[3]===0).length;if(team.length>=10&&zero/team.length>0.8)I.push({key:key("zero"),lv:"warn",title:`${Math.round(zero/team.length*100)}% video của team ra 0 đơn`,why:`${zero}/${team.length} video có hashtag/tag (video team) không ra đơn trong tuần.`,act:null,actTxt:"Rà lại hook 3 giây đầu, gắn giỏ đúng sản phẩm, dồn sức vào tuyến đã có bằng chứng."});
  const proj=tot*30/7;I.push({key:key("pace"),lv:proj>=T.gmvVideo?"info":"warn",title:proj>=T.gmvVideo?"Nhịp doanh thu đang đạt mục tiêu tháng":"Nhịp doanh thu đang dưới mục tiêu tháng",why:`Tuần này ${tr(tot)} → nhân ra tháng khoảng ${tr(proj)} so với mục tiêu ${tr(T.gmvVideo)} (${Math.round(proj/T.gmvVideo*100)}%).`,act:null,actTxt:proj>=T.gmvVideo?"Giữ nhịp, tập trung nhân bản video đang bán.":"Áp dụng các đề xuất đẩy thêm ở trên; kiểm tra video cũ có đang chững."});
  return {rows,I,tot,wk};
}
function aiApply(dt,ins){
  dcShape(dt);const a=ins.act,ch=[];
  if(a.type==="realloc"){ch.push({k:a.to,f:"kh",old:khOf(dt,a.to),nw:khOf(dt,a.to)+a.n});a.from.forEach(f=>ch.push({k:f.sku,f:"kh",old:khOf(dt,f.sku),nw:khOf(dt,f.sku)-f.n}));const p=dt.products.find(z=>z.k===a.to);if(p&&p.huong!=="Đẩy mạnh")ch.push({k:a.to,f:"huong",old:p.huong,nw:"Đẩy mạnh"})}
  if(a.type==="clone")ch.push({k:a.sku,f:"kh",old:khOf(dt,a.sku),nw:khOf(dt,a.sku)+a.n});
  const adj={id:"DC-"+String(dt.adjusts.length+1).padStart(2,"0"),at:new Date().toLocaleString("vi-VN"),day:dt.settings.today,by:ME.name+" bấm áp dụng",src:"Trợ lý AI",lyDo:`${ins.title}. ${ins.why}`,changes:ch,st:"pending"};
  if(can(ME,"kehoach.duyet"))applyAdjust(dt,adj);else dt.adjusts.unshift(adj);
  dt.ai.state[ins.key]="applied";dt.ai.log.unshift({at:new Date().toLocaleString("vi-VN"),by:ME.name,title:ins.title,act:ins.actTxt,n:ch.length,dc:adj.id});return ch.length;
}
function tgText(R){return `🔔 AILLA — Nhận định tuần ${R.wk.label||""}\nDoanh thu video: ${tr(R.tot)}\n\n`+R.I.filter(i=>i.lv!=="info").slice(0,5).map((i,k)=>`${i.lv==="hot"?"🔥":"⚠️"} ${k+1}. ${i.title}\n   ${i.why}\n   👉 ${i.actTxt}`).join("\n\n")+`\n\nTrả lời "duyệt 1" để áp dụng đề xuất 1, "bỏ 2" để bỏ qua.`}
let AISRC="";
let AIOUT={nd:"",hoi:""};
function pAI(m){
  aiShape(D());const W=aiWeeks();if(!W.length){m.innerHTML=H("Trợ lý AI","Nhận định, cảnh báo, đề xuất điều chỉnh kế hoạch")+`<section class="card waitf"><h2>Chưa có báo cáo tuần</h2><p>Nhập file TikTok "Video Performance List" ở Marketing › Đo lường › Nhập báo cáo. Ngay sau khi nhập, trợ lý tự phân tích.</p></section>`;return}
  if(!W.some(w=>w.key===AISRC))AISRC=W[W.length-1].key;const wi=W.findIndex(w=>w.key===AISRC),wk=W[wi],R=aiAnalyze(wk,wi>0?W[wi-1]:null),S=D().ai.state;
  const lvC={hot:["Cơ hội","pnk"],warn:["Cảnh báo","amb"],info:["Thông tin","blu"]};
  m.innerHTML=H("Trợ lý AI","Đọc báo cáo TikTok tuần → nhận định → đề xuất. Bấm Áp dụng thì tạo phiếu Điều chỉnh kế hoạch (kế hoạch gốc giữ nguyên để đối chiếu)")+`<div class="filters"><label class="inl">Báo cáo <select id="ai-src">${opt(W.map(w=>[w.key,w.label||(w.tu+" → "+w.den)]),AISRC)}</select></label><span class="hint">${nf(wk.recs.length)} video · doanh thu ${tr(R.tot)}</span></div>
  <div class="aigrid"><div class="stack">${R.I.map((i,k)=>{const st=S[i.key];return `<section class="card ai ${i.lv}${st?" done":""}"><div class="card-h"><span class="ain">${k+1}</span><h2>${esc(i.title)}</h2>${pill(lvC[i.lv][0],lvC[i.lv][1])}</div><p>${esc(i.why)}</p>${i.vid?`<p class="vidref">🎬 ID video <b class="mono">${esc(i.vid.id)}</b> · <a href="${esc(i.vid.url)}" target="_blank" rel="noopener">Mở trên TikTok ↗</a> · <button class="lnk" data-cpid="${esc(i.vid.id)}">Sao chép ID</button></p>`:""}<div class="aiact"><b>Đề xuất:</b> ${esc(i.actTxt)}</div><div class="acts">${st==="applied"?pill("Đã áp dụng","grn"):st==="ignored"?pill("Đã bỏ qua","gry"):`${i.act&&can(ME,"kehoach.duyet")?`<button class="btn sm pri" data-ai-ok="${k}">Áp dụng</button>`:""}<button class="btn sm" data-ai-no="${k}">Bỏ qua</button>`}</div></section>`}).join("")}</div>
  <div class="stack"><section class="card"><div class="card-h"><h2>Tỷ trọng doanh thu so với số video kế hoạch</h2></div>${tbl(["Sản phẩm","Hướng","Doanh thu","% doanh thu","% video KH","Hệ số"],R.rows.filter(r=>r.gmv||r.pk).map(r=>`<tr><td>${swatch(r.sku)}${esc(sk(r.sku).n)}</td><td>${esc(r.huong)}</td><td class="n">${tr(r.gmv)}</td><td class="n">${Math.round(r.shG*100)}%</td><td class="n">${r.pk?Math.round(r.shP*100)+"%":"—"}</td><td class="n">${r.pk?pill(r.ratio.toFixed(1)+"×",r.ratio>=1.5?"grn":r.ratio<0.5?"red":"gry"):"—"}</td></tr>`))}<p class="hint">Hệ số = % doanh thu ÷ % số video. Trên 1,5× là đang "ăn" hơn phần video dành cho nó → nên đẩy thêm. Dưới 0,5× là đang dư video.</p></section>
   ${clConnectCard()}<section class="card"><div class="card-h"><h2>AI nhận định tuần này</h2>${pill(aiSrc()==="9router"?"qua 9router":"Claude API","blu")}</div><p class="hint">Web gửi số liệu tuần + các đề xuất bên trái cho AI, AI viết nhận định và đề xuất bằng lời. Nút Áp dụng vẫn ở các thẻ bên trái.</p><div class="acts"><button class="btn pri" id="ai-cl">${AIOUT.nd?"Phân tích lại":"Nhờ AI phân tích"}</button><button class="btn" id="ai-copy">Sao chép số liệu gửi đi</button></div><div id="ai-cl-out" class="clout">${AIOUT.nd||""}</div></section>
   <section class="card"><div class="card-h"><h2>Hỏi AI về số liệu</h2></div><textarea id="ai-q" rows="3" placeholder="VD: Vì sao tinh dầu tăng mạnh tuần này? Nên giảm sản phẩm nào để dồn video?"></textarea><div class="acts"><button class="btn pri" id="ai-ask">Hỏi AI</button></div><div id="ai-q-out" class="clout">${AIOUT.hoi||""}</div><p class="hint">Câu hỏi được gửi kèm số liệu tuần đang chọn. Sau này chuyển sang bot phòng ban (xem Cài đặt › Bot AI phòng ban).</p></section>
   <section class="card"><div class="card-h"><h2>Đã áp dụng</h2></div>${(D().ai.log||[]).slice(0,8).map(l=>`<div class="event"><p><strong>${esc(l.title)}</strong></p><small>${esc(l.by)} · ${esc(l.at)}${l.dc?" · phiếu "+esc(l.dc):""}</small></div>`).join("")||`<p class="empty">Chưa áp dụng đề xuất nào.</p>`}</section></div></div>`;
  $("#ai-src").onchange=e=>{AISRC=e.target.value;renderMain()};
  m.querySelectorAll("[data-ai-ok]").forEach(b=>b.onclick=()=>{const ins=R.I[+b.dataset.aiOk];if(!confirm(`Áp dụng: ${ins.actTxt}`))return;let n=0;DB.mutate(ME.name,"áp dụng đề xuất AI: "+ins.title,dt=>{aiShape(dt);n=aiApply(dt,ins)});toast(can(ME,"kehoach.duyet")?"Đã tạo và áp dụng phiếu điều chỉnh. Xem ở Điều chỉnh kế hoạch":"Đã gửi phiếu điều chỉnh chờ CEO duyệt");renderMain()});
  m.querySelectorAll("[data-ai-no]").forEach(b=>b.onclick=()=>{const ins=R.I[+b.dataset.aiNo];DB.mutate(ME.name,"bỏ qua đề xuất AI: "+ins.title,dt=>{aiShape(dt);dt.ai.state[ins.key]="ignored"});renderMain()});
  const cp=t=>{try{navigator.clipboard.writeText(t);toast("Đã sao chép")}catch(e){toast("Không sao chép được")}};
  m.querySelectorAll("[data-cpid]").forEach(b=>b.onclick=()=>cp(b.dataset.cpid));
  const ctx=`Số liệu TikTok tuần ${wk.label||wk.tu+"→"+wk.den}: tổng doanh thu video ${tr(R.tot)}, ${wk.recs.length} video.
Theo sản phẩm (doanh thu · % doanh thu · % video kế hoạch tháng · hướng đã chốt):
`+R.rows.filter(r=>r.gmv||r.pk).map(r=>`- ${sk(r.sku).n}: ${tr(r.gmv)} · ${Math.round(r.shG*100)}% · ${r.pk?Math.round(r.shP*100)+"%":"—"} · ${r.huong}`).join("\n")+`
Top 8 video: `+wk.recs.slice().sort((a,b)=>b[2]-a[2]).slice(0,8).map(v=>`"${(v[7]||v[0]).slice(0,50)}" (ID ${v[0]}) ${nf(v[3])} đơn ${tr(v[2])}`).join("; ")+`

Đề xuất bộ luật của web đã đưa ra:
`+R.I.map((i,k)=>`${k+1}. [${i.lv}] ${i.title} — ${i.why} → ${i.actTxt}`).join("\n");
  const run=async(btn,out,key,sys,msg,eff)=>{btn.disabled=true;const t0=btn.textContent;btn.textContent="AI đang đọc số…";$(out).innerHTML=`<p class="hint">Đang chờ AI trả lời (thường 20–60 giây)…</p>`;try{const r=await askClaude(sys,msg,eff);AIOUT[key]=mdLite(r.text)+`<p class="hint">— ${esc(r.model)}${r.trunc?" · câu trả lời bị cắt do quá dài":""}</p>`;if($(out))$(out).innerHTML=AIOUT[key]}catch(e){if($(out))$(out).innerHTML=`<div class="note red">${esc(e.message||String(e))}</div>`}btn.disabled=false;btn.textContent=t0};
  $("#ai-copy").onclick=()=>cp(ctx);
  $("#ai-cl").onclick=e=>run(e.target,"#ai-cl-out","nd",CL_SYS,ctx,"medium");
  $("#ai-ask").onclick=e=>{const q=$("#ai-q").value.trim();if(!q){toast("Gõ câu hỏi trước");return}run(e.target,"#ai-q-out","hoi",CL_SYS.replace(/Cấu trúc:.*$/,"Trả lời đúng câu hỏi, ngắn, có đề xuất hành động cụ thể cho tuần tới. Không quá 250 chữ."),ctx+`

Câu hỏi: ${q}`,"medium")};
  bindClConnect();
}
function aiTop(n){const W=aiWeeks();if(!W.length)return [];const wk=W[W.length-1],R=aiAnalyze(wk,W.length>1?W[W.length-2]:null),S=(D().ai||{state:{}}).state;return R.I.filter(i=>i.lv!=="info"&&!S[i.key]).slice(0,n)}
Object.assign(PAGES,{ai:pAI});
