/* =====================================================================
   BOT AI PHÒNG BAN (OpenClaw trên VPS · combo AI cấu hình ở 9router)
   Web chuẩn bị số liệu + cảnh báo + đề xuất, gửi đúng bot của phòng ban; bot trả lệnh duyệt ngược lại.
   Không lưu token/mật khẩu bot trong web — để ở VPS.
   ===================================================================== */
const BOT_VIEC=[["canhbao","Nhận cảnh báo"],["dexuat","Gửi đề xuất cần duyệt"],["baocao","Báo cáo sáng hằng ngày"],["hoi","Trả lời câu hỏi số liệu"],["taoviec","Tạo / giao việc trên web"]];
const BOTS0=[["BDH","Bot Điều hành","Chị Hoa (chat riêng)",["canhbao","dexuat","baocao","hoi"]],["CM","Bot Content","Nhóm Content & Media",["canhbao","dexuat","baocao","hoi","taoviec"]],["ADS","Bot Digital","Nhóm Digital",["canhbao","dexuat","baocao","hoi"]],["B2C","Bot Sale B2C","Nhóm Sale B2C + CSKH",["canhbao","baocao","hoi"]],["B2B","Bot Sale B2B","Nhóm Sale B2B",["canhbao","baocao","hoi","taoviec"]],["KT","Bot Kế toán","Kế toán",["canhbao","baocao","hoi"]],["HCNS","Bot HCNS","Hành chính – Nhân sự",["canhbao","hoi"]],["KOC","Bot KOC","Team KOC",["canhbao","hoi"]]];
function botShape(d){if(!d.bots)d.bots=BOTS0.map(([pb,ten,chat,viec])=>({pb,ten,tg:"",chat,combo:"",viec,duyet:pb==="BDH"||pb==="CM"||pb==="ADS"?"u_chi":"",bat:false,gio:"08:00"}));return d}
const botOf=pb=>(D().bots||[]).find(b=>b.pb===pb)||null;
const botChip=pb=>{const b=botOf(pb);return b?`<span class="botchip${b.bat?"":" off"}" title="${b.bat?"đang bật":"chưa kết nối"}">🤖 ${esc(b.ten)}</span>`:""};
/* trang nào thuộc phòng nào → bot nào nhận cảnh báo */
const PAGE_PB={cv:"CM",kehoach:"CM",dieuchinh:"CM",ai:"CM",bc_tiktok:"CM",bc_koc:"KOC",fb_sale:"B2C",bc_fb:"B2C",doisoat:"KT",bc_shopee:"KT",b2b_cn:"B2B",b2b_don:"B2B",b2b_today:"B2B",hr_nghi:"HCNS",hr_kpi:"HCNS",hr_hd:"HCNS",hr_td:"HCNS",adshieuqua:"ADS",fb_ads:"ADS"};
function pBots(m){
  const d=botShape(D()),ed=can(ME,"caidat.quanly");
  m.innerHTML=H("Bot AI phòng ban","Mỗi phòng ban một bot OpenClaw · bộ AI dùng theo combo đã cài ở 9router")+`<div class="note">Web không tự gọi AI. Web gom số liệu, cảnh báo, đề xuất rồi gửi cho <b>đúng bot của phòng ban</b>. Bot dùng combo AI ở 9router để viết nhận định, nhắn vào nhóm Telegram. Người có quyền trả lời bot (ví dụ "duyệt 1") thì web nhận lệnh và áp dụng. Token bot, mật khẩu để trên VPS, <b>không lưu trong web</b>.</div>
  <section class="card flush"><div class="tbl edit"><table><thead><tr><th>Phòng ban</th><th>Tên bot</th><th>Bot Telegram (@tên)</th><th>Gửi vào nhóm / người</th><th>Combo AI (9router)</th><th>Bot được làm</th><th>Người duyệt đề xuất</th><th>Báo cáo sáng</th><th>Bật</th></tr></thead><tbody>
  ${d.bots.map((b,i)=>`<tr><td><b>${esc((d.departments.find(p=>p.k===b.pb)||{n:b.pb}).n)}</b></td><td>${ed?`<input data-bt="${i}" data-f="ten" value="${esc(b.ten)}">`:esc(b.ten)}</td><td>${ed?`<input data-bt="${i}" data-f="tg" value="${esc(b.tg)}" placeholder="@ailla_content_bot">`:esc(b.tg||"—")}</td><td>${ed?`<input data-bt="${i}" data-f="chat" value="${esc(b.chat)}">`:esc(b.chat)}</td><td>${ed?`<input data-bt="${i}" data-f="combo" value="${esc(b.combo)}" placeholder="tên combo trong 9router">`:esc(b.combo||"—")}</td><td><div class="phc">${BOT_VIEC.map(([k,l])=>ed?`<label class="ck sm"><input type="checkbox" data-bv="${i}" value="${k}" ${b.viec.includes(k)?"checked":""}> ${l}</label>`:b.viec.includes(k)?pill(l,"blu")+" ":"").join("")}</div></td><td>${ed?`<select data-bt="${i}" data-f="duyet">${opt([["","—"]].concat(d.users.filter(u=>u.active&&["admin","lead"].includes(u.role)).map(u=>[u.id,u.name])),b.duyet)}</select>`:esc(userName(b.duyet)||"—")}</td><td>${ed?`<input data-bt="${i}" data-f="gio" value="${esc(b.gio)}" style="width:70px">`:esc(b.gio)}</td><td>${ed?`<input type="checkbox" data-bt="${i}" data-f="bat" ${b.bat?"checked":""} style="width:auto">`:b.bat?"Có":"Chưa"}</td></tr>`).join("")}</tbody></table></div></section>
  <section class="card"><div class="card-h"><h2>Cảnh báo nào đi bot nào</h2></div>${tbl(["Loại cảnh báo / đề xuất","Bot nhận"],[["Đề xuất dồn video, nhân bản video win, thẻ trễ hạn, phiếu điều chỉnh kế hoạch","CM"],["Chi Ads vượt ngưỡng, ROAS giảm, creative hết hiệu quả","ADS"],["Tỷ lệ hủy / hoàn cao, đơn tồn chưa xử lý","B2C"],["Công nợ vượt hạn mức, khách tới chu kỳ nhập, đơn chờ duyệt","B2B"],["Tiền treo chưa đối soát, SKU thiếu giá vốn, chi phí tháng chưa nhập","KT"],["Hợp đồng sắp hết, đơn nghỉ chờ duyệt, KPI chờ duyệt","HCNS"],["KOC chưa nghiệm thu video","KOC"],["Tóm tắt toàn công ty mỗi sáng + mọi cảnh báo đỏ","BDH"]].map(([a,pb])=>`<tr><td>${a}</td><td>${botChip(pb)}</td></tr>`))}</section>
  <section class="card"><div class="card-h"><h2>Bot hỏi ngược lại web được gì</h2></div><ol class="lessons"><li>"Tuần này tinh dầu bao nhiêu đơn?" → web trả số theo đúng quyền của người hỏi.</li><li>"Việc của Quỳnh hôm nay?" → danh sách việc từ mục Công việc.</li><li>"duyệt 1" / "bỏ 2" → duyệt hoặc bỏ đề xuất đã gửi, ghi nhật ký người duyệt.</li><li>"giao 3 video nhân bản cho Hòa, hạn thứ 6" → tạo việc trên web (bot có quyền "Tạo / giao việc").</li></ol><p class="hint">Bản thật: web mở một cổng dữ liệu riêng cho bot, mỗi bot chỉ đọc được số của phòng mình.</p></section>`;
  m.querySelectorAll("[data-bt]").forEach(x=>x.onchange=()=>{DB.mutate(ME.name,"sửa bot phòng ban",dt=>{botShape(dt);dt.bots[+x.dataset.bt][x.dataset.f]=x.type==="checkbox"?x.checked:x.value});toast("Đã lưu")});
  m.querySelectorAll("[data-bv]").forEach(x=>x.onchange=()=>{DB.mutate(ME.name,"sửa việc bot",dt=>{const b=dt.bots[+x.dataset.bv];b.viec=x.checked?[...new Set(b.viec.concat(x.value))]:b.viec.filter(v=>v!==x.value)});toast("Đã lưu")});
}
Object.assign(PAGES,{bots:pBots});
