/* =====================================================================
   KẾ HOẠCH GỐC & ĐIỀU CHỈNH TRONG THÁNG
   Đầu tháng chốt kế hoạch gốc (giữ nguyên để đối chiếu). Giữa tháng thay đổi = phiếu điều chỉnh có lý do, người đề xuất, người duyệt.
   ===================================================================== */
const khOf=(d,k)=>d.tuyen.filter(t=>t.sku===k).reduce((a,t)=>a+t.kh,0);
function snapPlan(d,by){return {at:new Date().toLocaleString("vi-VN"),day:d.settings.today,by,items:d.products.map(p=>({k:p.k,n:p.n,huong:p.huong,gmv:(d.goals[p.k]||{}).gmv||0,kh:khOf(d,p.k)})),tong:d.kpiTargets.gmvVideo}}
function dcShape(d){if(!d.adjusts)d.adjusts=[];if(!d.planBase&&d.plan&&d.plan.published)d.planBase=snapPlan(d,"Oanh · chị duyệt");return d}
const HUONGS=["Đẩy mạnh","Đẩy nhẹ","Giữ","Giữ nhẹ","Test","Giảm","Dừng"];
function applyAdjust(dt,adj){
  adj.changes.forEach(ch=>{const p=dt.products.find(x=>x.k===ch.k);if(!p)return;
    if(ch.f==="huong")p.huong=ch.nw;
    if(ch.f==="gmv")(dt.goals[ch.k]=dt.goals[ch.k]||{m9:0,gmv:0}).gmv=ch.nw;
    if(ch.f==="kh"){const delta=ch.nw-ch.old;
      if(delta>0){const w=weekOf(dt.settings.today)||1;let tu=dt.tuyen.find(t=>t.sku===ch.k&&t.ma===`T${MONTH.mon}-${ch.k}-DC${w}`);if(!tu){tu={ma:`T${MONTH.mon}-${ch.k}-DC${w}`,kenh:"TikTok chính",sku:ch.k,tuyen:adj.src==="Trợ lý AI"?"Nhân bản winner":"Điều chỉnh tuần "+w,vaiTro:"Điều chỉnh giữa tháng",kh:0,nguoi:(dt.pillars.find(x=>x.sku===ch.k)||{}).nguoi||"",kiemChung:"Có bằng chứng",maInsight:"",ghiChu:adj.lyDo};dt.tuyen.push(tu)}
        const from=dt.settings.today+1,span=Math.max(1,MONTH.ndays-from+1);for(let i=0;i<delta;i++){const c=newCard(dt,{sku:ch.k,kenh:"TikTok chính",maTuyen:tu.ma,day:Math.min(MONTH.ndays,from+Math.floor(i*span/delta)),nguon:tu.tuyen==="Nhân bản winner"?"Nhân bản winner":"Quay mới",tuyen:tu.tuyen,goiy:tu.nguoi});c.dieuChinh=adj.id;dt.cards.push(c)}tu.kh+=delta}
      if(delta<0){const C=dt.cards.filter(c=>c.sku===ch.k&&c.step==="cg").sort((a,b)=>(a.kenh==="TikTok chính"?0:1)-(b.kenh==="TikTok chính"?0:1)||b.day-a.day).slice(0,-delta);C.forEach(c=>{const t=dt.tuyen.find(x=>x.ma===c.maTuyen);if(t)t.kh=Math.max(0,t.kh-1)});const ids=new Set(C.map(c=>c.id));dt.cards=dt.cards.filter(c=>!ids.has(c.id));ch.thucTe=-C.length}}
  });
  adj.st="applied";adj.duyet=ME.name;adj.duyetLuc=new Date().toLocaleString("vi-VN");dt.adjusts.unshift(adj);
  const w=weekOf(dt.settings.today)||1;dt.weekNotes[w]=dt.weekNotes[w]||{};dt.weekNotes[w].qd=((dt.weekNotes[w].qd||"")+(dt.weekNotes[w].qd?"\n":"")+`[Điều chỉnh ${adj.id}] ${adj.lyDo}`).trim();
}
const fmtCh=ch=>ch.f==="huong"?`${sk(ch.k).n}: hướng ${ch.old} → <b>${ch.nw}</b>`:ch.f==="gmv"?`${sk(ch.k).n}: mục tiêu ${tr(ch.old)} → <b>${tr(ch.nw)}</b>`:`${sk(ch.k).n}: số video ${ch.old} → <b>${ch.nw}</b>${ch.thucTe!=null&&-ch.thucTe<ch.old-ch.nw?` (chỉ bớt được ${-ch.thucTe} thẻ chưa giao)`:""}`;
function pDieuChinh(m){
  const d=dcShape(D()),B=d.planBase,ed=can(ME,"kehoach.duyet"),sug=can(ME,"kehoach.sua");
  if(!B){m.innerHTML=H("Điều chỉnh kế hoạch")+`<section class="card waitf"><h2>Chưa chốt kế hoạch gốc</h2><p>Kế hoạch gốc được chốt khi phát hành kế hoạch ở Kế hoạch › Bước 6. Từ lúc đó mọi thay đổi trong tháng đều đi qua trang này.</p></section>`;return}
  const rows=d.products.map(p=>{const b=B.items.find(x=>x.k===p.k)||{huong:"(chưa có)",gmv:0,kh:0},cur={huong:p.huong,gmv:(d.goals[p.k]||{}).gmv||0,kh:khOf(d,p.k)};return {p,b,cur}});
  const pend=d.adjusts.filter(a=>a.st==="pending");
  m.innerHTML=H("Điều chỉnh kế hoạch",`Kế hoạch gốc chốt ${esc(B.at)} · ${d.adjusts.filter(a=>a.st==="applied").length} lần điều chỉnh`)+`<div class="note">Kế hoạch gốc giữ nguyên để cuối tháng đối chiếu. Khi số tuần cho thấy cần đổi (sản phẩm đang lên, sản phẩm chậm), tạo <b>phiếu điều chỉnh</b> có lý do. Oanh hoặc trợ lý AI đề xuất, chị duyệt. Duyệt xong thẻ việc tự thêm hoặc bớt, và ghi vào Quyết định tuần.</div>
  <section class="card flush"><div class="card-h pad"><h2>Kế hoạch gốc so với hiện tại</h2></div><div class="tbl"><table><thead><tr><th>Sản phẩm</th><th>Hướng gốc</th><th>Hướng hiện tại</th><th class="n">Mục tiêu gốc</th><th class="n">Mục tiêu hiện tại</th><th class="n">Số video gốc (mọi kênh)</th><th class="n">Số video hiện tại</th></tr></thead><tbody>${rows.map(({p,b,cur})=>{const dh=b.huong!==cur.huong,dg=b.gmv!==cur.gmv,dk=b.kh!==cur.kh;return `<tr class="${dh||dg||dk?"chg-row":""}"><td>${swatch(p.k)}<b>${esc(p.n)}</b></td><td>${esc(b.huong)}</td><td>${dh?`<b class="t-pink">${esc(cur.huong)}</b>`:esc(cur.huong)}</td><td class="n">${tr(b.gmv)}</td><td class="n">${dg?`<b class="t-pink">${tr(cur.gmv)}</b>`:tr(cur.gmv)}</td><td class="n">${b.kh}</td><td class="n">${dk?`<b class="t-pink">${cur.kh} (${cur.kh>b.kh?"+":""}${cur.kh-b.kh})</b>`:cur.kh}</td></tr>`}).join("")}</tbody></table></div></section>
  ${pend.length?`<section class="card"><div class="card-h"><h2>Phiếu chờ chị duyệt (${pend.length})</h2></div>${pend.map(a=>`<div class="adj"><div><b>${a.id}</b> · ${esc(a.src)} · ${esc(a.by)} · ${esc(a.at)}</div><div>${esc(a.lyDo)}</div><ul>${a.changes.map(c=>`<li>${fmtCh(c)}</li>`).join("")}</ul>${ed?`<div class="acts"><button class="btn sm pri" data-adj-ok="${a.id}">Duyệt và áp dụng</button><button class="btn sm danger" data-adj-no="${a.id}">Không duyệt</button></div>`:pill("Chờ chị duyệt","amb")}</div>`).join("")}</section>`:""}
  ${sug?`<section class="card"><div class="card-h"><h2>Tạo phiếu điều chỉnh</h2><span class="hint">${ed?"Chị tạo thì áp dụng ngay":"Oanh tạo thì chờ chị duyệt"}</span></div><form class="frm" id="adjf"><div class="tbl"><table><thead><tr><th>Sản phẩm</th><th>Hướng mới</th><th class="n">Mục tiêu mới (triệu)</th><th class="n">Số video mới</th></tr></thead><tbody>${rows.map(({p,cur})=>`<tr><td>${esc(p.n)}</td><td><select data-nh="${p.k}">${opt(HUONGS,cur.huong)}</select></td><td class="n"><input class="num" data-ng="${p.k}" value="${Math.round(cur.gmv/1e6)}"></td><td class="n"><input class="num s" data-nk="${p.k}" value="${cur.kh}"></td></tr>`).join("")}</tbody></table></div><label class="field">Lý do điều chỉnh *<textarea id="adj-ly" required placeholder="VD: Tuần 2 tinh dầu chiếm 60% doanh thu video (gấp 2 phần video dành cho nó), dồn thêm 10 video nhân bản; bớt sáp thơm và lau sàn vì chưa ra đơn"></textarea></label><button class="btn pri">${ed?"Duyệt và áp dụng":"Gửi chị duyệt"}</button></form></section>`:""}
  <section class="card"><div class="card-h"><h2>Lịch sử điều chỉnh</h2></div>${d.adjusts.filter(a=>a.st!=="pending").map(a=>`<div class="adj ${a.st}"><div><b>${a.id}</b> · ${pill(a.st==="applied"?"Đã áp dụng":"Không duyệt",a.st==="applied"?"grn":"gry")} · đề xuất: ${esc(a.src)} (${esc(a.by)}, ${esc(a.at)})${a.duyet?` · ${esc(a.duyet)} duyệt ${esc(a.duyetLuc)}`:""}</div><div>${esc(a.lyDo)}</div><ul>${a.changes.map(c=>`<li>${fmtCh(c)}</li>`).join("")}</ul></div>`).join("")||`<p class="empty">Chưa có lần điều chỉnh nào. Kế hoạch đang chạy đúng như bản gốc.</p>`}</section>`;
  if($("#adjf"))$("#adjf").onsubmit=e=>{e.preventDefault();const ch=[];rows.forEach(({p,cur})=>{const h=m.querySelector(`[data-nh="${p.k}"]`).value,g=Math.round((+m.querySelector(`[data-ng="${p.k}"]`).value||0)*1e6),k=Math.max(0,+m.querySelector(`[data-nk="${p.k}"]`).value||0);if(h!==cur.huong)ch.push({k:p.k,f:"huong",old:cur.huong,nw:h});if(Math.round(cur.gmv/1e6)*1e6!==g)ch.push({k:p.k,f:"gmv",old:cur.gmv,nw:g});if(k!==cur.kh)ch.push({k:p.k,f:"kh",old:cur.kh,nw:k})});if(!ch.length){toast("Chưa thay đổi gì");return}
    const adj={id:"DC-"+String(d.adjusts.length+1).padStart(2,"0"),at:new Date().toLocaleString("vi-VN"),day:d.settings.today,by:ME.name,src:ed?"Chị":"Oanh",lyDo:$("#adj-ly").value,changes:ch,st:"pending"};
    DB.mutate(ME.name,`${ed?"điều chỉnh":"đề xuất điều chỉnh"} kế hoạch ${adj.id}`,dt=>{dcShape(dt);if(ed)applyAdjust(dt,adj);else dt.adjusts.unshift(adj)});toast(ed?"Đã áp dụng điều chỉnh":"Đã gửi chị duyệt");renderMain()};
  m.querySelectorAll("[data-adj-ok]").forEach(b=>b.onclick=()=>{DB.mutate(ME.name,"duyệt điều chỉnh "+b.dataset.adjOk,dt=>{const i=dt.adjusts.findIndex(a=>a.id===b.dataset.adjOk);const a=dt.adjusts.splice(i,1)[0];applyAdjust(dt,a)});toast("Đã duyệt và áp dụng");renderMain()});
  m.querySelectorAll("[data-adj-no]").forEach(b=>b.onclick=()=>{DB.mutate(ME.name,"không duyệt "+b.dataset.adjNo,dt=>{const a=dt.adjusts.find(x=>x.id===b.dataset.adjNo);a.st="rejected";a.duyet=ME.name;a.duyetLuc=new Date().toLocaleString("vi-VN")});renderMain()});
}
Object.assign(PAGES,{dieuchinh:pDieuChinh});
