/* =====================================================================
   NHÂN SỰ — theo cấu trúc file AILLA HR MASTER
   Lương, hợp đồng, phép, KPI… KHÔNG nhúng trong file web: nạp từ file HR MASTER, chỉ lưu trong trình duyệt.
   ===================================================================== */
const HR_NGHE=["Dải gốc","Kế toán SX","Kỹ thuật/R&D","Kế toán nội bộ","Content & Media","Sale B2B","Vận hành TMĐT/KOC","Hành chính/NS","Digital Mkt/Ads","SX-Kho vận","Phụ trợ","Sale B2C"];
const HR_THANG0={L1a:[5650000,6215000,5933000,5650000,5650000,5368000,5368000,5368000,5310000,5310000,5310000,5310000],L1b:[6200000,6820000,6510000,6200000,6200000,5890000,5890000,5890000,5580000,5310000,5310000,5310000],L1c:[6800000,7480000,7140000,6800000,6800000,6460000,6460000,6460000,6120000,5310000,5310000,5310000],L2a:[7500000,8250000,7875000,7500000,7500000,7125000,7125000,7125000,6750000,5310000,5310000,5310000],L2b:[8250000,9075000,8663000,8250000,8250000,7838000,7838000,7838000,7425000,5775000,5363000,5310000],L2c:[9050000,9955000,9503000,9050000,9050000,8598000,8598000,8598000,8145000,6335000,5883000,5792000],L3a:[9850000,10835000,10343000,9850000,9850000,9358000,9358000,9358000,8865000,6895000,6403000,6304000],L3b:[10750000,11825000,11288000,10750000,10750000,10213000,10213000,10213000,9675000,7525000,6988000,6880000],L3c:[11700000,12870000,12285000,11700000,11700000,11115000,11115000,11115000,10530000,8190000,7605000,7488000],L4a:[12650000,13915000,13283000,12650000,12650000,12018000,12018000,12018000,11385000,8855000,8223000,8096000],L4b:[13650000,15015000,14333000,13650000,13650000,12968000,12968000,12968000,12285000,9555000,8873000,8736000],L4c:[14750000,16225000,15488000,14750000,14750000,14013000,14013000,14013000,13275000,10325000,9588000,9440000],L5a:[15800000,17380000,16590000,15800000,15800000,15010000,15010000,15010000,14220000,11060000,10270000,10112000],L5b:[16900000,18590000,17745000,16900000,16900000,16055000,16055000,16055000,15210000,11830000,10985000,10816000],L5c:[18100000,19910000,19005000,18100000,18100000,17195000,17195000,17195000,16290000,12670000,11765000,11584000]};
const HR_CS0={ma:"CS-2026-HRM",hieuLuc:"2026-01-01",cong:26,gio:8,ot:1.5,otCN:2,anTrua:780000,xang:500000,dt:300000,cc:500000,docHai:500000,muonMax:2,bhxh:0.105,tranBH:36000000,gtBan:11000000,gtNPT:4400000,bieu:"7",phepNam:12,xetBacThang:3,nguongBac:70,kpiQD:[[95,1],[85,.75],[70,.5],[0,0]],note:"Theo DM_HeThong file HR MASTER — nhiều số đang là GIẢ ĐỊNH DEMO, CEO/HCNS/Kế toán cần chốt"};
const TAX={"7":[[5e6,.05],[10e6,.1],[18e6,.15],[32e6,.2],[52e6,.25],[80e6,.3],[1e15,.35]],"5":[[10e6,.05],[30e6,.1],[60e6,.2],[100e6,.3],[1e15,.35]]};
const hrNow=()=>{const t=new Date();return {iso:iso(t),thang:iso(t).slice(0,7)}};
function hrShape(d){const z={loaded:false,ns:{},phep:{},kpi:[],dg:[],xb:[],td:[],dt:[],tu:[],cc:{},thuong:{},don:[],payroll:{},cs:[JSON.parse(JSON.stringify(HR_CS0))],thangLuong:JSON.parse(JSON.stringify(HR_THANG0)),file:""};d.hr=d.hr||{};for(const k in z)if(d.hr[k]==null)d.hr[k]=z[k]; // phần riêng (lương, hồ sơ) chỉ người được phép nhận về: thiếu thì điền rỗng
const nsOf={u_quynh:"NV012",u_va:"NV015",u_thao:"NV025",u_duan:"NV024",u_dat:"NV014",u_huyen:"NV021"};d.users.forEach(u=>{if(!u.maNS&&nsOf[u.id])u.maNS=nsOf[u.id]});return d}
const HRD=()=>D().hr;
const csOf=thang=>{const L=HRD().cs.filter(c=>c.hieuLuc.slice(0,7)<=thang).sort((a,b)=>a.hieuLuc<b.hieuLuc?1:-1);return L[0]||HRD().cs[0]};
const staffBy=ma=>D().staff.find(x=>x.ma===ma)||{ma,ten:ma,pb:"",khoi:""};
const pbName=k=>(D().departments.find(p=>p.k===k)||{n:k||"—"}).n;
const canHR=()=>can(ME,"nhansu.quanly");
const canLuong=()=>can(ME,"luong.quanly")||ME.role==="admin";
const vndate=s=>s?String(s).slice(0,10).split("-").reverse().join("/"):"—";
const daysTo=s=>s?Math.round((pdate(String(s).slice(0,10))-pdate(hrNow().iso))/864e5):null;
const hrEmpty=()=>`<section class="card waitf"><h2>Chưa nạp dữ liệu nhân sự</h2><p>Lương, hợp đồng, phép, KPI, xét bậc, tạm ứng không nằm sẵn trong file web để giữ bí mật. Chị (hoặc HCNS) tải file <b>AILLA HR MASTER</b> trên Google Drive về dạng Excel rồi nạp ở trang <b>Nạp file HR MASTER</b>. Số chỉ lưu trong trình duyệt của máy đó.</p><div class="acts"><button class="btn pri" data-go="hr_nap">Nạp file HR MASTER</button></div></section>`;

/* ---------- Nạp file ---------- */
function wbSheets(f){return new Promise((res,rej)=>{if(typeof XLSX==="undefined"){toast("Cần mạng để đọc Excel");rej();return}const r=new FileReader();r.onload=()=>{try{const wb=XLSX.read(r.result,{type:"array",cellDates:true});const o={};wb.SheetNames.forEach(n=>o[n]=XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,raw:true,defval:null}));res(o)}catch(e){toast("Không đọc được file");rej(e)}};r.readAsArrayBuffer(f)})}
const dstr=v=>v instanceof Date?iso(v):typeof v==="number"&&v>30000&&v<60000?iso(new Date(Date.UTC(1899,11,30)+v*864e5)):v?String(v).slice(0,10):"";
const nv=v=>{const n=+String(v??"").replace(/[^\d.-]/g,"");return isFinite(n)?n:0};
function tableOf(rows,key="Mã NS"){const hi=(rows||[]).findIndex(r=>r&&r.some(c=>String(c||"").trim()===key));if(hi<0)return [];const H=rows[hi].map(c=>String(c||"").trim());return rows.slice(hi+1).filter(r=>r&&r.some(c=>c!==null&&c!=="")).map(r=>{const o={};H.forEach((h,i)=>{if(h)o[h]=r[i]});return o})}
function importHR(S){
  const out={ns:{},phep:{},kpi:[],dg:[],xb:[],td:[],dt:[],tu:[],cc:{},thangLuong:null};let n=0;
  tableOf(S["01_NhanSu"]).filter(r=>/^NV/.test(r["Mã NS"]||"")).forEach(r=>{out.ns[r["Mã NS"]]={luong:nv(r["Lương cứng"]),nenBH:nv(r["Nền BHXH"]),npt:nv(r["Người phụ thuộc"]),bac:String(r["Bậc hiện tại"]||""),ngayBac:dstr(r["Ngày vào bậc"]),nghe:String(r["Nhóm nghề"]||""),hd:{loai:String(r["Loại HĐ"]||""),hetTV:dstr(r["Ngày hết thử việc"]),het:dstr(r["Ngày hết HĐ"])},hoSo:String(r["Tình trạng hồ sơ"]||""),gioi:String(r["Giới tính"]||"")};n++});
  tableOf(S["02_HopDong"]).filter(r=>/^NV/.test(r["Mã NS"]||"")).forEach(r=>{const x=out.ns[r["Mã NS"]]=out.ns[r["Mã NS"]]||{};x.hd={loai:String(r["Loại HĐ"]||""),so:String(r["Số HĐ"]||""),ky:dstr(r["Ngày ký"]),hieuLuc:dstr(r["Ngày hiệu lực"]),het:dstr(r["Ngày hết hạn"]),hetTV:dstr(r["Ngày hết thử việc"]),luongTV:nv(r["Lương thử việc"]),luongCT:nv(r["Lương chính thức"]),giay:String(r["Đã ký bản giấy"]||"")}});
  tableOf(S["04_NghiPhep"]).filter(r=>/^NV/.test(r["Mã NS"]||"")).forEach(r=>{out.phep[r["Mã NS"]]={chuan:nv(r[Object.keys(r).find(k=>/tiêu chuẩn/.test(k))]),huong:nv(r["Phép được hưởng"]),da:nv(r["Đã nghỉ phép"]),kl:nv(r["Nghỉ không lương"]),om:nv(r["Nghỉ ốm"])}});
  tableOf(S["05_KPI"]).filter(r=>/^NV/.test(r["Mã NS"]||"")).forEach(r=>{const ks=Object.keys(r);const ct=[1,2,3].map(i=>[String(r["Chỉ tiêu "+i]||""),nv(r["KQ "+i]),nv(r["Trọng số "+i])]).filter(x=>x[0]);out.kpi.push({id:uid("kp"),thang:dstr(r["Tháng"]).slice(0,7),ma:r["Mã NS"],ct,diem:nv(r["Điểm KPI"]),xl:String(r["Xếp loại"]||""),st:/Đã/.test(r["Lead xác nhận"]||"")?"duyet":"cho",nguon:"file"})});
  tableOf(S["06_DanhGia"]).filter(r=>/^NV/.test(r["Mã NS"]||"")).forEach(r=>out.dg.push({ky:dstr(r["Kỳ đánh giá"]),ma:r["Mã NS"],nl:nv(r["Điểm năng lực"]),hv:nv(r["Điểm hành vi/360"]),sop:nv(r["Tuân thủ SOP"]),kl:String(r["Kỷ luật còn hiệu lực?"]||""),diem:nv(r["Điểm tổng hợp"]),xl:String(r["Xếp loại"]||"")}));
  tableOf(S["07_XetBac"]).filter(r=>/^NV/.test(r["Mã NS"]||"")).forEach(r=>out.xb.push({ky:dstr(r["Kỳ xét"]),ma:r["Mã NS"],bac:String(r["Bậc hiện tại"]||""),deNghi:String(r["Bậc đề nghị"]||""),thangOBac:nv(r["Tháng ở bậc"]),kpi3:nv(r["KPI TB 3 tháng"]),kpi100:nv(r["Số tháng KPI ≥100%"]),khongKL:String(r["Không kỷ luật"]||""),cua:[nv(r["Cửa Kết quả"]),nv(r["Cửa Năng lực"]),nv(r["Cửa Hành vi"]),nv(r["Cửa Phạm vi"])],diem:nv(r["Điểm tổng"]),kl:String(r["Kết luận"]||""),xetLai:dstr(r["Kỳ xét lại"]),st:"cho"}));
  tableOf(S["10_TuyenDung"],"Mã yêu cầu").filter(r=>r["Mã yêu cầu"]).forEach(r=>out.td.push({ma:r["Mã yêu cầu"],viTri:r["Vị trí"],pb:r["Phòng ban"],sl:nv(r["Số lượng"]),mo:dstr(r["Ngày mở"]),han:dstr(r["Hạn tuyển"]),nguon:r["Nguồn tuyển"]||"",uv:nv(r["Ứng viên"]),pv:nv(r["Phỏng vấn"]),nhan:nv(r["Đã nhận việc"]),tt:r["Trạng thái"]||""}));
  tableOf(S["11_DaoTao"]).filter(r=>/^NV/.test(r["Mã NS"]||"")).forEach(r=>out.dt.push({ma:r["Mã NS"],ct:r["Chương trình"]||"",loai:r["Loại"]||"",bd:dstr(r["Ngày bắt đầu"]),han:dstr(r["Hạn hoàn thành"]),tien:nv(r["Tiến độ"]),diem:nv(r["Điểm test"]),hd:r["Người hướng dẫn"]||"",tt:r["Trạng thái"]||""}));
  tableOf(S["14_TamUng"]).filter(r=>/^NV/.test(r["Mã NS"]||"")).forEach(r=>{const k=String(r["Kỳ trừ lương"]||r["Tháng"]||"");const m=k.match(/(\d{2})\/(\d{4})/);out.tu.push({id:r["Mã đề nghị"]||uid("tu"),ma:r["Mã NS"],ngay:dstr(r["Ngày đề nghị"]),tien:nv(r["Số tiền tạm ứng"]),lyDo:r["Lý do"]||"",tt:/Đã duyệt/.test(r["Trạng thái"]||"")?"duyet":/Từ chối/.test(r["Trạng thái"]||"")?"tuchoi":"cho",ky:m?`${m[2]}-${m[1]}`:hrNow().thang})});
  tableOf(S["03_ChamCong"]).filter(r=>/^NV/.test(r["Mã NS"]||"")&&r["Công thực tế"]!=null).forEach(r=>{const th=dstr(r["Tháng"]).slice(0,7);(out.cc[th]=out.cc[th]||{})[r["Mã NS"]]={cong:nv(r["Công thực tế"]),phep:nv(r["Phép hưởng lương"]),kl:nv(r["Nghỉ không lương"]),muon:nv(r["Đi muộn"])+nv(r["Về sớm"]),ot:nv(r["Giờ OT thường"]),otCN:nv(r["Giờ OT khác"])}});
  const dm=S["DM_HeThong"]||[];const hi=dm.findIndex(r=>r&&r[0]==="Bậc-nấc");if(hi>=0){const tl={};dm.slice(hi+1).forEach(r=>{if(r&&/^L\d[abc]$/.test(String(r[0]||"")))tl[r[0]]=r.slice(1,13).map(nv)});if(Object.keys(tl).length)out.thangLuong=tl}
  return {out,n};
}
function pHrNap(m){
  const h=HRD();m.innerHTML=H("Nạp file HR MASTER","Dữ liệu nhân sự nhạy cảm chỉ lưu trong trình duyệt của máy này")+`<section class="card"><ol class="lessons"><li>Mở Google Sheet <b>AILLA HR MASTER — Demo quản trị nhân sự 2026</b> → <b>Tệp › Tải xuống › Microsoft Excel (.xlsx)</b>.</li><li>Kéo file vừa tải vào ô dưới.</li><li>Web đọc các tab: 01_NhanSu, 02_HopDong, 03_ChamCong, 04_NghiPhep, 05_KPI, 06_DanhGia, 07_XetBac, 10_TuyenDung, 11_DaoTao, 14_TamUng, DM_HeThong (thang lương). Không đọc CCCD, tài khoản ngân hàng, số điện thoại.</li></ol>${dropZone("hr")}
  ${h.loaded?`<div class="note">Đã nạp <b>${esc(h.file)}</b> lúc ${esc(h.at)}: ${Object.keys(h.ns).length} hồ sơ lương, ${h.kpi.length} dòng KPI, ${h.xb.length} xét bậc, ${h.td.length} yêu cầu tuyển dụng, ${h.tu.length} tạm ứng.</div><div class="acts"><button class="btn danger" id="hr-clear">Xóa dữ liệu nhân sự khỏi trình duyệt này</button></div>`:""}</section>`;
  bindDrop("hr",async f=>{const S=await wbSheets(f);if(!S["01_NhanSu"]){toast("File không có tab 01_NhanSu");return}const {out,n}=importHR(S);DB.mutate(ME.name,"nạp file HR MASTER",dt=>{Object.assign(dt.hr,out,{loaded:true,file:f.name,at:new Date().toLocaleString("vi-VN"),thangLuong:out.thangLuong||dt.hr.thangLuong})});toast(`Đã nạp ${n} nhân sự`);renderMain()});
  if($("#hr-clear"))$("#hr-clear").onclick=()=>{if(!confirm("Xóa toàn bộ lương, hợp đồng, phép, KPI đã nạp?"))return;DB.mutate(ME.name,"xóa dữ liệu nhân sự",dt=>{const cs=dt.hr.cs,tl=dt.hr.thangLuong,don=dt.hr.don;delete dt.hr;hrShape(dt);dt.hr.cs=cs;dt.hr.thangLuong=tl;dt.hr.don=don});renderMain()};
}
/* ---------- Tính lương ---------- */
function taxOf(tn,bieu){let t=0,prev=0;for(const [cap,r] of TAX[bieu]||TAX["7"]){if(tn<=prev)break;t+=(Math.min(tn,cap)-prev)*r;prev=cap}return Math.round(Math.max(0,t))}
function winnerBonus(ma,thang){const u=D().users.find(x=>x.maNS===ma);if(!u||thang!==MONTH.key)return 0;const s=D().settings;return D().cards.filter(c=>c.nguoi===u.id&&c.don>=s.winnerOrders).length*s.winnerBonus}
function calcRow(ma,thang){
  const h=HRD(),cs=csOf(thang),st=staffBy(ma),ns=h.ns[ma]||{},cc=((h.cc[thang]||{})[ma])||null,cong=cc?cc.cong:cs.cong,tamTinh=!cc;
  const luong=ns.luong||0,lCong=Math.round(luong*Math.min(cong,cs.cong+5)/cs.cong),dg=luong/cs.cong/cs.gio;
  const sale=["B2C","B2B","CSKH"].includes(st.pb),sx=st.khoi==="Sản xuất & Kho",muon=cc?cc.muon:0;
  const pc={anTrua:cs.anTrua,xang:sale?cs.xang:0,dt:sale?cs.dt:0,cc:muon<=cs.muonMax?cs.cc:0,docHai:sx?cs.docHai:0};const pcT=Object.values(pc).reduce((a,b)=>a+b,0);
  const ot=Math.round(((cc?cc.ot:0)*cs.ot+(cc?cc.otCN:0)*cs.otCN)*dg);
  const th=(h.thuong[thang]||{})[ma]||{kpi:0,khac:0},wb=winnerBonus(ma,thang);
  const tong=lCong+pcT+ot+th.kpi+th.khac+wb;
  const bh=Math.round(Math.min(ns.nenBH||0,cs.tranBH)*cs.bhxh);
  const tnTT=Math.max(0,tong-pc.anTrua-bh-cs.gtBan-(ns.npt||0)*cs.gtNPT);
  const thue=taxOf(tnTT,cs.bieu);
  const tu=h.tu.filter(x=>x.ma===ma&&x.ky===thang&&x.tt==="duyet").reduce((a,x)=>a+x.tien,0);
  return {ma,ten:st.ten,pb:st.pb,khoi:st.khoi,bac:ns.bac||"",cong,congChuan:cs.cong,tamTinh,luong,lCong,pc,pcT,ot,kpi:th.kpi,khac:th.khac,wb,tong,nenBH:ns.nenBH||0,bh,npt:ns.npt||0,tnTT,thue,tu,thucLinh:tong-bh-thue-tu,cs:cs.ma};
}
const payPeriod=thang=>HRD().payroll[thang]||{st:"nhap"};
const PST={nhap:["Nháp","gry"],chot:["Đã chốt","amb"],phathanh:["Đã phát hành","grn"]};
let HRM=(()=>{const t=new Date();t.setMonth(t.getMonth()-1);return iso(t).slice(0,7)})();
function monthSel(id){return `<label class="inl">Kỳ lương <input type="month" id="${id}" value="${HRM}"></label>`}
function pHrBangLuong(m){
  if(!HRD().loaded){m.innerHTML=H("Bảng lương")+hrEmpty();return}
  const h=HRD(),P=payPeriod(HRM),cs=csOf(HRM),rows=P.rows||D().staff.filter(x=>x.tt!=="Đã nghỉ"&&h.ns[x.ma]).map(x=>calcRow(x.ma,HRM)),ed=canLuong()&&P.st==="nhap";
  const T=k=>rows.reduce((a,r)=>a+(r[k]||0),0),tamTinh=rows.filter(r=>r.tamTinh).length;
  m.innerHTML=H("Bảng lương",`Kỳ ${HRM.slice(5)}/${HRM.slice(0,4)} · chính sách ${esc(cs.ma)}`)+`<div class="filters">${monthSel("bl-m")}${pill(PST[P.st][0],PST[P.st][1])}<span class="sp"></span>${canLuong()?(P.st==="nhap"?`<button class="btn" id="bl-chot">Chốt kỳ lương</button>`:P.st==="chot"?`<button class="btn" id="bl-mo">Mở lại</button><button class="btn pri" id="bl-ph">Phát hành phiếu lương</button>`:""):""}<button class="btn" id="bl-xl">⬇ Excel</button></div>
  <div class="grid kpis">${kpi("Số người",rows.length)}${kpi("Tổng thu nhập",money(T("tong")))}${kpi("BHXH người lao động",money(T("bh")))}${kpi("Thuế TNCN",money(T("thue")))}${kpi("Thực lĩnh",money(T("thucLinh")),"",`var(--green)`)}</div>
  ${rows.some(r=>!r.luong)?`<div class="note warn">${rows.filter(r=>!r.luong).length} người chưa có lương cứng trong file HR MASTER (${rows.filter(r=>!r.luong).map(r=>esc(r.ten)).join(", ")}). Bổ sung ở tab 01_NhanSu rồi nạp lại.</div>`:""}${tamTinh?`<div class="note">${tamTinh} người <b>chưa có công thực tế</b> kỳ này nên đang tạm tính đủ ${cs.cong} công. Nhập công ở trang Chấm công trước khi chốt.</div>`:""}${cs.bieu==="7"?`<div class="note warn">Đang dùng giảm trừ ${nf(cs.gtBan)} / ${nf(cs.gtNPT)} và biểu thuế 7 bậc như file HR MASTER (file ghi "cần cập nhật pháp lý"). Kế toán xác nhận rồi đổi ở <b>Cài đặt lương</b>.</div>`:""}
  <section class="card flush"><div class="tbl"><table><thead><tr><th>Mã</th><th>Họ tên</th><th>Phòng</th><th class="n">Công</th><th class="n">Lương cứng</th><th class="n">Lương theo công</th><th class="n">Phụ cấp</th><th class="n">KPI / thưởng</th><th class="n">Thưởng video win</th><th class="n">OT</th><th class="n">Tổng thu nhập</th><th class="n">BHXH</th><th class="n">Thuế TNCN</th><th class="n">Tạm ứng</th><th class="n">Thực lĩnh</th><th></th></tr></thead><tbody>
  ${rows.map(r=>`<tr><td class="mono">${r.ma}</td><td><b>${esc(r.ten)}</b></td><td>${esc(pbName(r.pb))}</td><td class="n">${r.cong}${r.tamTinh?"*":""}</td><td class="n">${r.luong?nf(r.luong):pill("chưa có","red")}</td><td class="n">${nf(r.lCong)}</td><td class="n">${nf(r.pcT)}</td><td class="n">${ed?`<input class="num s" data-th="${r.ma}" data-f="kpi" value="${r.kpi||""}" placeholder="0">`:nf(r.kpi)}</td><td class="n">${r.wb?nf(r.wb):"—"}</td><td class="n">${nf(r.ot)}</td><td class="n"><b>${nf(r.tong)}</b></td><td class="n">${nf(r.bh)}</td><td class="n">${nf(r.thue)}</td><td class="n">${r.tu?nf(r.tu):"—"}</td><td class="n"><b class="${r.thucLinh<0?"t-red":""}">${nf(r.thucLinh)}</b></td><td><button class="btn sm" data-pl="${r.ma}">Phiếu</button></td></tr>`).join("")}</tbody></table></div></section><p class="hint">* tạm tính đủ công. Lương theo công = lương cứng × công thực tế ÷ ${cs.cong}. Phụ cấp: ăn trưa mọi người; xăng + điện thoại cho Sale, CSKH; chuyên cần nếu muộn/về sớm ≤ ${cs.muonMax} lần; độc hại cho Sản xuất & Kho. Thưởng video win tự lấy từ Marketing (≥${D().settings.winnerOrders} đơn × ${nf(D().settings.winnerBonus)}đ).</p>`;
  $("#bl-m").onchange=e=>{HRM=e.target.value||HRM;renderMain()};
  m.querySelectorAll("[data-th]").forEach(x=>x.onchange=()=>{DB.mutate(ME.name,"nhập thưởng KPI "+x.dataset.th,dt=>{const t=dt.hr.thuong[HRM]=dt.hr.thuong[HRM]||{};t[x.dataset.th]=t[x.dataset.th]||{kpi:0,khac:0};t[x.dataset.th][x.dataset.f]=nv(x.value)});renderMain()});
  m.querySelectorAll("[data-pl]").forEach(b=>b.onclick=()=>openPhieu(rows.find(r=>r.ma===b.dataset.pl),HRM,P));
  if($("#bl-chot"))$("#bl-chot").onclick=()=>{if(tamTinh&&!confirm(`${tamTinh} người chưa nhập công, vẫn chốt?`))return;DB.mutate(ME.name,"chốt kỳ lương "+HRM,dt=>dt.hr.payroll[HRM]={st:"chot",rows:rows.map(r=>JSON.parse(JSON.stringify(r))),at:new Date().toLocaleString("vi-VN"),by:ME.name});renderMain()};
  if($("#bl-mo"))$("#bl-mo").onclick=()=>{DB.mutate(ME.name,"mở lại kỳ lương "+HRM,dt=>delete dt.hr.payroll[HRM]);renderMain()};
  if($("#bl-ph"))$("#bl-ph").onclick=()=>{DB.mutate(ME.name,"phát hành phiếu lương "+HRM,dt=>{const p=dt.hr.payroll[HRM];p.st="phathanh";p.ph=new Date().toLocaleString("vi-VN");p.xem={}});toast("Đã phát hành: nhân viên xem được phiếu của mình");renderMain()};
  $("#bl-xl").onclick=()=>{if(typeof XLSX==="undefined")return;const ws=XLSX.utils.aoa_to_sheet([["Mã NS","Họ tên","Phòng","Công","Lương cứng","Lương theo công","Phụ cấp","KPI/thưởng","Thưởng video win","OT","Tổng thu nhập","BHXH","Thuế TNCN","Tạm ứng","Thực lĩnh"]].concat(rows.map(r=>[r.ma,r.ten,pbName(r.pb),r.cong,r.luong,r.lCong,r.pcT,r.kpi,r.wb,r.ot,r.tong,r.bh,r.thue,r.tu,r.thucLinh])));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Bang luong");XLSX.writeFile(wb,`Bang-luong-${HRM}.xlsx`)};
}
function openPhieu(r,thang,P){
  if(!r)return;const L=[["Lương theo công",r.lCong],["Ăn trưa",r.pc.anTrua],["Xăng xe",r.pc.xang],["Điện thoại",r.pc.dt],["Chuyên cần",r.pc.cc],["Độc hại",r.pc.docHai],["KPI / thưởng",r.kpi],["Thưởng video winner",r.wb],["Thưởng khác",r.khac],["Tăng ca",r.ot]].filter(x=>x[1]);
  openDrawerHTML(`<div class="phieu" id="phieu"><h2>Phiếu lương tháng ${thang.slice(5)}/${thang.slice(0,4)}</h2><div class="grid kpis">${kpi("Nhân viên",esc(r.ten),r.ma)}${kpi("Bộ phận",esc(pbName(r.pb)),r.bac?"bậc "+r.bac:"")}${kpi("Công thực tế / chuẩn",`${r.cong} / ${r.congChuan}`)}</div>
   <div class="grid cols2"><div><h3>Thu nhập</h3>${tbl(["Khoản","Số tiền"],L.map(x=>`<tr><td>${x[0]}</td><td class="n">${nf(x[1])}</td></tr>`).concat([`<tr class="tot"><td>TỔNG THU NHẬP</td><td class="n">${nf(r.tong)}</td></tr>`]))}</div>
   <div><h3>Khấu trừ</h3>${tbl(["Khoản","Số tiền"],[["BHXH, BHYT, BHTN người lao động",r.bh],["Thuế TNCN",r.thue],["Tạm ứng",r.tu]].map(x=>`<tr><td>${x[0]}</td><td class="n">${nf(x[1])}</td></tr>`).concat([`<tr class="tot"><td>THỰC LĨNH</td><td class="n">${nf(r.thucLinh)}</td></tr>`]))}</div></div>
   <div class="grid kpis">${kpi("Mức đóng BHXH",nf(r.nenBH))}${kpi("Người phụ thuộc",r.npt)}${kpi("Thu nhập tính thuế",nf(r.tnTT))}</div>
   <p class="hint">${P&&P.st==="phathanh"?"Phiếu do HCNS phát hành "+esc(P.ph||"")+". Số liệu là bản chốt của kỳ, không đổi khi chính sách thay đổi.":P&&P.st==="chot"?"Kỳ đã chốt, chưa phát hành.":"Bản nháp, chưa chốt."}</p></div><div class="acts"><button class="btn pri" id="ph-pdf">In / Tải PDF</button></div>`);
  $("#ph-pdf").onclick=()=>{const w=window.open("","_blank");if(!w){toast("Trình duyệt chặn cửa sổ in");return}w.document.write(`<!doctype html><meta charset="utf-8"><title>Phieu luong ${r.ma} ${thang}</title><style>body{font-family:Arial,sans-serif;padding:24px;color:#14213d}table{width:100%;border-collapse:collapse;margin:8px 0}td,th{border:1px solid #ccd;padding:6px 8px;font-size:13px;text-align:left}.n{text-align:right}.tot td{font-weight:700;background:#f3f5fa}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.kpi{display:inline-block;margin:0 18px 10px 0}.l{font-size:11px;color:#667}.v{font-weight:700;font-size:16px}.btn,.acts{display:none}</style>`+$("#phieu").innerHTML);w.document.close();w.focus();w.print()};
}
/* ---------- Phiếu lương (HCNS + của tôi) ---------- */
function pHrPhieu(m,mine){
  const h=HRD(),ma=ME.maNS,ks=Object.entries(h.payroll).filter(([k,p])=>p.st==="phathanh"||(!mine&&p.st==="chot")).sort((a,b)=>a[0]<b[0]?1:-1);
  if(mine&&!ma){m.innerHTML=H("Phiếu lương của tôi")+`<section class="card"><p>Tài khoản này chưa gắn với mã nhân sự. Nhờ HCNS gắn ở Danh sách nhân sự.</p></section>`;return}
  if(mine){const L=ks.map(([k,p])=>[k,p,(p.rows||[]).find(r=>r.ma===ma)]).filter(x=>x[2]&&x[1].st==="phathanh");const chua=L.filter(x=>!(x[1].xem||{})[ma]).length;
    m.innerHTML=H("Phiếu lương của tôi","Chỉ hiện các kỳ HCNS đã phát hành cho bạn")+`<div class="grid kpis">${kpi("Phiếu đã phát hành",L.length)}${kpi("Chưa xem",chua,"",chua?"var(--pink)":"")}${kpi("Kỳ gần nhất",L[0]?L[0][0].slice(5)+"/"+L[0][0].slice(0,4):"—")}</div>${L.map(([k,p,r])=>`<section class="card plrow${(p.xem||{})[ma]?"":" new"}"><div><b>Tháng ${k.slice(5)}/${k.slice(0,4)}</b><small>Phát hành ${esc(p.ph||"")}</small>${pill((p.xem||{})[ma]?"Đã xem":"Mới",(p.xem||{})[ma]?"grn":"pnk")}</div><div><span class="hint">Tổng thu nhập</span><b>${nf(r.tong)}</b></div><div><span class="hint">BHXH</span><b>${nf(r.bh)}</b></div><div><span class="hint">Thuế TNCN</span><b>${nf(r.thue)}</b></div><div><span class="hint">Thực lĩnh</span><b>${nf(r.thucLinh)}</b></div><button class="btn pri" data-k="${k}">Xem phiếu</button></section>`).join("")||`<section class="card"><p class="empty">Chưa có phiếu lương nào được phát hành.</p></section>`}`;
    m.querySelectorAll("[data-k]").forEach(b=>b.onclick=()=>{const p=h.payroll[b.dataset.k];DB.mutate(ME.name,"xem phiếu lương "+b.dataset.k,dt=>{const x=dt.hr.payroll[b.dataset.k];x.xem=x.xem||{};x.xem[ma]=new Date().toLocaleString("vi-VN")});openPhieu(p.rows.find(r=>r.ma===ma),b.dataset.k,p)});return}
  if(!h.loaded){m.innerHTML=H("Phiếu lương")+hrEmpty();return}
  m.innerHTML=H("Phiếu lương","Theo dõi phát hành và lượt xem của nhân viên")+(ks.length?ks.map(([k,p])=>{const n=(p.rows||[]).length,x=Object.keys(p.xem||{}).length;return `<section class="card"><div class="card-h"><h2>Kỳ ${k.slice(5)}/${k.slice(0,4)}</h2>${pill(PST[p.st][0],PST[p.st][1])}</div><p>${n} phiếu · ${p.st==="phathanh"?`${x}/${n} người đã xem · phát hành ${esc(p.ph)}`:"chốt "+esc(p.at)+", chưa phát hành"}</p><div class="acts"><button class="btn" data-go="hr_bl">Mở bảng lương</button></div></section>`}).join(""):`<section class="card"><p class="empty">Chưa có kỳ lương nào được chốt. Vào Bảng lương › Chốt kỳ lương › Phát hành.</p></section>`);
}
/* ---------- Chấm công ---------- */
function pHrCC(m){
  if(!HRD().loaded){m.innerHTML=H("Chấm công")+hrEmpty();return}
  const h=HRD(),cs=csOf(HRM),C=h.cc[HRM]||{},ed=canHR()&&payPeriod(HRM).st==="nhap",L=D().staff.filter(x=>x.tt!=="Đã nghỉ");
  m.innerHTML=H("Chấm công",`Kỳ ${HRM.slice(5)}/${HRM.slice(0,4)} · công chuẩn ${cs.cong}`)+`<div class="filters">${monthSel("cc-m")}<span class="sp"></span>${ed?`<button class="btn" id="cc-full">Điền đủ công cho ô trống</button>`:""}</div>
  <section class="card flush"><div class="tbl edit"><table><thead><tr><th>Mã</th><th>Họ tên</th><th>Khối</th><th class="n">Công thực tế</th><th class="n">Phép hưởng lương</th><th class="n">Nghỉ không lương</th><th class="n">Muộn / về sớm (lần)</th><th class="n">OT thường (giờ)</th><th class="n">OT CN, lễ (giờ)</th><th>Chuyên cần</th></tr></thead><tbody>
  ${L.map(x=>{const c=C[x.ma]||{};const f=(k)=>ed?`<input class="num s" data-cc="${x.ma}" data-f="${k}" value="${c[k]??""}">`:(c[k]??"—");return `<tr><td class="mono">${x.ma}</td><td><b>${esc(x.ten)}</b></td><td>${esc(x.khoi)}</td><td class="n">${f("cong")}</td><td class="n">${f("phep")}</td><td class="n">${f("kl")}</td><td class="n">${f("muon")}</td><td class="n">${f("ot")}</td><td class="n">${f("otCN")}</td><td>${c.cong==null?"—":(c.muon||0)<=cs.muonMax?pill("Đủ","grn"):pill("Mất","red")}</td></tr>`}).join("")}</tbody></table></div></section>
  ${ed?`<section class="card"><div class="card-h"><h2>Nạp file chấm công</h2></div><p class="hint">File Excel có cột: <b>Mã NS · Công thực tế · Phép hưởng lương · Nghỉ không lương · Đi muộn · Về sớm · Giờ OT thường · Giờ OT khác</b> (đúng như tab 03_ChamCong). Bản thật: kéo thẳng file máy chấm công văn phòng và ảnh xưởng như tab CC_Raw_VP.</p>${dropZone("cc")}</section>`:""}`;
  $("#cc-m").onchange=e=>{HRM=e.target.value||HRM;renderMain()};
  m.querySelectorAll("[data-cc]").forEach(x=>x.onchange=()=>{DB.mutate(ME.name,"nhập công "+x.dataset.cc,dt=>{const t=dt.hr.cc[HRM]=dt.hr.cc[HRM]||{};const o=t[x.dataset.cc]=t[x.dataset.cc]||{cong:null,phep:0,kl:0,muon:0,ot:0,otCN:0};o[x.dataset.f]=x.value===""?(x.dataset.f==="cong"?null:0):nv(x.value);if(o.cong==null)delete t[x.dataset.cc]});renderMain()});
  if($("#cc-full"))$("#cc-full").onclick=()=>{DB.mutate(ME.name,"điền đủ công "+HRM,dt=>{const t=dt.hr.cc[HRM]=dt.hr.cc[HRM]||{};L.forEach(x=>{if(!t[x.ma])t[x.ma]={cong:cs.cong,phep:0,kl:0,muon:0,ot:0,otCN:0}})});renderMain()};
  if($("#dz-cc"))bindDrop("cc",async f=>{const S=await wbSheets(f);const rows=tableOf(Object.values(S)[0]);let n=0;DB.mutate(ME.name,"nạp file chấm công "+HRM,dt=>{const t=dt.hr.cc[HRM]=dt.hr.cc[HRM]||{};rows.filter(r=>/^NV/.test(r["Mã NS"]||"")&&r["Công thực tế"]!=null).forEach(r=>{t[r["Mã NS"]]={cong:nv(r["Công thực tế"]),phep:nv(r["Phép hưởng lương"]),kl:nv(r["Nghỉ không lương"]),muon:nv(r["Đi muộn"])+nv(r["Về sớm"]),ot:nv(r["Giờ OT thường"]),otCN:nv(r["Giờ OT khác"])};n++})});toast(`Đã nạp công ${n} người`);renderMain()});
}
/* ---------- Đơn nghỉ phép, OT, tạm ứng (gửi + duyệt) ---------- */
const DON_LOAI=["Nghỉ phép năm","Nghỉ không lương","Nghỉ ốm","Làm thêm giờ (OT)","Tạm ứng lương"];
function donForm(maDefault){const L=D().staff.filter(x=>x.tt!=="Đã nghỉ");return `<form class="frm" id="donf"><div class="row4">${maDefault?"":`<label class="field">Nhân viên<select id="dn-ma">${opt(L.map(x=>[x.ma,x.ma+" · "+x.ten]),"")}</select></label>`}<label class="field">Loại đơn<select id="dn-l">${opt(DON_LOAI,"Nghỉ phép năm")}</select></label><label class="field">Từ ngày<input type="date" id="dn-tu" value="${hrNow().iso}"></label><label class="field">Đến ngày<input type="date" id="dn-den" value="${hrNow().iso}"></label></div><div class="row4"><label class="field">Số ngày / số giờ / số tiền<input id="dn-sl" type="number" min="0" step="0.5" value="1"></label><label class="field grow">Lý do<input id="dn-ly" required></label></div><button class="btn pri">Gửi đơn</button></form>`}
function bindDonForm(ma){$("#donf").onsubmit=e=>{e.preventDefault();const m2=ma||$("#dn-ma").value,l=$("#dn-l").value;DB.mutate(ME.name,`gửi đơn ${l}`,dt=>dt.hr.don.push({id:uid("dn"),ma:m2,loai:l,tu:$("#dn-tu").value,den:$("#dn-den").value,sl:nv($("#dn-sl").value),ly:$("#dn-ly").value,tt:"cho",gui:new Date().toLocaleString("vi-VN"),by:ME.name}));toast("Đã gửi đơn, chờ duyệt");renderMain()}}
function applyDon(dt,x){const ky=x.tu.slice(0,7);if(x.loai==="Nghỉ phép năm"){const p=dt.hr.phep[x.ma]=dt.hr.phep[x.ma]||{chuan:12,huong:12,da:0,kl:0,om:0};p.da+=x.sl}if(x.loai==="Nghỉ không lương"){const p=dt.hr.phep[x.ma]=dt.hr.phep[x.ma]||{chuan:12,huong:12,da:0,kl:0,om:0};p.kl+=x.sl}if(x.loai==="Tạm ứng lương")dt.hr.tu.push({id:x.id,ma:x.ma,ngay:x.tu,tien:x.sl,lyDo:x.ly,tt:"duyet",ky})}
function pHrNghi(m){
  const h=HRD(),ed=can(ME,"nhansu.duyet")||canHR(),cho=h.don.filter(x=>x.tt==="cho"),tuCho=h.tu.filter(x=>x.tt==="cho");
  m.innerHTML=H("Nghỉ phép, OT & tạm ứng","Nhân viên gửi đơn trên web, quản lý duyệt, phép và lương tự cập nhật")+`<div class="grid kpis">${kpi("Đơn chờ duyệt",cho.length+tuCho.length,"",cho.length+tuCho.length?"var(--orange)":"")}${kpi("Phép năm tiêu chuẩn",csOf(hrNow().thang).phepNam+" ngày","thử việc không có, không chuyển năm")}</div>
  <section class="card"><div class="card-h"><h2>Đơn chờ duyệt</h2></div>${tbl(["Nhân viên","Loại","Thời gian","Số lượng","Lý do","Gửi lúc",""],cho.map(x=>`<tr><td><b>${esc(staffBy(x.ma).ten)}</b><small>${x.ma}</small></td><td>${esc(x.loai)}</td><td>${vndate(x.tu)}${x.den!==x.tu?" – "+vndate(x.den):""}</td><td class="n">${x.loai==="Tạm ứng lương"?nf(x.sl)+"đ":x.sl}</td><td>${esc(x.ly)}</td><td>${esc(x.gui)}</td><td>${ed?`<button class="btn sm pri" data-dd="${x.id}" data-v="duyet">Duyệt</button> <button class="btn sm" data-dd="${x.id}" data-v="tuchoi">Từ chối</button>`:""}</td></tr>`).concat(tuCho.map(x=>`<tr><td><b>${esc(staffBy(x.ma).ten)}</b><small>${x.ma}</small></td><td>Tạm ứng (từ file)</td><td>${vndate(x.ngay)}</td><td class="n">${nf(x.tien)}đ</td><td>${esc(x.lyDo)}</td><td>—</td><td>${ed?`<button class="btn sm pri" data-tu="${x.id}" data-v="duyet">Duyệt</button> <button class="btn sm" data-tu="${x.id}" data-v="tuchoi">Từ chối</button>`:""}</td></tr>`)))}</section>
  <section class="card"><div class="card-h"><h2>Gửi đơn thay nhân viên</h2></div>${donForm(null)}</section>
  ${h.loaded?`<section class="card"><div class="card-h"><h2>Phép năm ${hrNow().iso.slice(0,4)}</h2></div>${tbl(["Nhân viên","Phòng","Được hưởng","Đã nghỉ","Còn","Không lương","Ốm",""],D().staff.filter(x=>h.phep[x.ma]).map(x=>{const p=h.phep[x.ma],con=p.huong-p.da;return `<tr><td><b>${esc(x.ten)}</b></td><td>${esc(pbName(x.pb))}</td><td class="n">${p.huong}</td><td class="n">${p.da}</td><td class="n">${con<=1?pill(con,"amb"):con}</td><td class="n">${p.kl}</td><td class="n">${p.om}</td><td>${con<=1?pill("Sắp hết phép","amb"):""}</td></tr>`}))}</section>`:hrEmpty()}
  <section class="card"><div class="card-h"><h2>Đơn đã xử lý</h2></div>${tbl(["Nhân viên","Loại","Thời gian","Số lượng","Kết quả"],h.don.filter(x=>x.tt!=="cho").slice(-30).reverse().map(x=>`<tr><td>${esc(staffBy(x.ma).ten)}</td><td>${esc(x.loai)}</td><td>${vndate(x.tu)}</td><td class="n">${x.sl}</td><td>${pill(x.tt==="duyet"?"Đã duyệt":"Từ chối",x.tt==="duyet"?"grn":"red")} <small>${esc(x.nguoiDuyet||"")}</small></td></tr>`))}</section>`;
  bindDonForm(null);
  m.querySelectorAll("[data-dd]").forEach(b=>b.onclick=()=>{DB.mutate(ME.name,(b.dataset.v==="duyet"?"duyệt":"từ chối")+" đơn",dt=>{const x=dt.hr.don.find(y=>y.id===b.dataset.dd);x.tt=b.dataset.v;x.nguoiDuyet=ME.name;if(x.tt==="duyet")applyDon(dt,x)});renderMain()});
  m.querySelectorAll("[data-tu]").forEach(b=>b.onclick=()=>{DB.mutate(ME.name,"xử lý tạm ứng",dt=>dt.hr.tu.find(y=>y.id===b.dataset.tu).tt=b.dataset.v);renderMain()});
}
/* ---------- KPI ---------- */
function autoKPI(ma){
  const u=D().users.find(x=>x.maNS===ma);if(!u)return null;const today=D().settings.today;
  if(u.role==="digital"){const n=u.name.split(" ").pop();const p=(KDX.adsPeople||[]).find(x=>x.n.endsWith(n));if(!p)return null;return {nguon:"Báo cáo Digital tháng 9 (số thật)",ct:[["Doanh số so với KPI giao",Math.min(1.2,p.dt/p.kpi),.6],["Chi Ads / doanh số ≤ 35%",Math.min(1.2,.35/Math.max(.01,p.chi/p.dt)),.3],["Việc đúng hạn",onTimeRate(u.id),.1]]}}
  const C=D().cards.filter(c=>c.nguoi===u.id),xong=C.filter(c=>c.step==="xong"),due=C.filter(c=>c.day<today);
  return {nguon:"Marketing tháng 10 (số mẫu demo)",ct:[["Video đăng đúng hạn",due.length?due.filter(c=>c.step==="xong").length/due.length:1,.5],["Tỷ lệ video ra đơn",xong.filter(c=>c.tiktokId).length?Math.min(1.2,xong.filter(c=>c.don>0).length/xong.filter(c=>c.tiktokId).length/.4):0,.3],["Việc khác đúng hạn",onTimeRate(u.id),.2]]};
}
function onTimeRate(uid2){const today=D().settings.today,I=cvItems().filter(x=>x.nguoi===uid2&&x.han<today);return I.length?I.filter(x=>x.st==="done"||!x.late).length/I.length:1}
const kpiDiem=ct=>ct.reduce((a,c)=>a+c[1]*c[2],0)/Math.max(.0001,ct.reduce((a,c)=>a+c[2],0));
const kpiHS=(d,cs)=>{for(const [p,h] of cs.kpiQD)if(d*100>=p)return h;return 0};
let KPM=null;
function pHrKPI(m,mine){
  const h=HRD(),months=[...new Set(h.kpi.map(k=>k.thang))].sort();if(!KPM)KPM=months[months.length-1]||hrNow().thang;const cs=csOf(KPM),me=ME.maNS;
  const L=h.kpi.filter(k=>k.thang===KPM&&(!mine||k.ma===me)),ed=can(ME,"nhansu.duyet")||canHR();
  const auto=D().staff.filter(x=>D().users.some(u=>u.maNS===x.ma)).filter(x=>!mine||x.ma===me).map(x=>({x,a:autoKPI(x.ma)})).filter(y=>y.a);
  m.innerHTML=H(mine?"KPI của tôi":"KPI","Tự đánh giá → quản lý duyệt → quy đổi hệ số vào bảng lương")+`<div class="filters"><label class="inl">Kỳ <select id="kp-m">${opt([...new Set(months.concat([hrNow().thang]))].sort().map(x=>[x,x.slice(5)+"/"+x.slice(0,4)]),KPM)}</select></label><span class="hint">Quy đổi: ${cs.kpiQD.map(([p,h2])=>`≥${p}% → ${h2}`).join(" · ")}</span></div>
  ${mine?"":`<div class="grid kpis">${kpi("Đã có KPI",L.length)}${kpi("Chờ duyệt",L.filter(k=>k.st==="cho").length,"",L.some(k=>k.st==="cho")?"var(--orange)":"")}${kpi("Đạt (≥ 85%)",L.filter(k=>k.diem>=.85).length)}${kpi("Không đạt (< 70%)",L.filter(k=>k.diem<.7).length,"","var(--red)")}</div>`}
  <section class="card"><div class="card-h"><h2>KPI tự lấy số từ vận hành</h2><span class="hint">không chấm cảm tính: số đi thẳng từ Công việc, Marketing, báo cáo Ads</span></div>${tbl(["Nhân viên","Nguồn số","Chỉ tiêu (kết quả · trọng số)","Điểm","Hệ số",""],auto.map(({x,a})=>{const d2=kpiDiem(a.ct);return `<tr><td><b>${esc(x.ten)}</b><small>${esc(pbName(x.pb))}</small></td><td class="hint">${esc(a.nguon)}</td><td>${a.ct.map(c=>`${esc(c[0])}: <b>${Math.round(c[1]*100)}%</b> · ${Math.round(c[2]*100)}%`).join("<br>")}</td><td class="n"><b>${Math.round(d2*100)}</b></td><td class="n">${kpiHS(d2,cs)}</td><td>${ed&&!mine?`<button class="btn sm" data-ak="${x.ma}">Đưa vào kỳ ${KPM.slice(5)}</button>`:""}</td></tr>`}))}</section>
  <section class="card"><div class="card-h"><h2>Phiếu KPI kỳ ${KPM.slice(5)}/${KPM.slice(0,4)}</h2></div>${tbl(["Nhân viên","Phòng","Chỉ tiêu","Điểm","Xếp loại","Hệ số","Trạng thái",""],L.map(k=>{const s=staffBy(k.ma);return `<tr><td><b>${esc(s.ten)}</b><small>${k.ma}</small></td><td>${esc(pbName(s.pb))}</td><td>${k.ct.map(c=>`${esc(c[0])}: ${Math.round(c[1]*100)}% × ${Math.round(c[2]*100)}%`).join("<br>")}</td><td class="n"><b>${Math.round(k.diem*100)}</b></td><td>${esc(k.xl||(k.diem>=.85?"Đạt":k.diem>=.7?"Cần cải thiện":"Không đạt"))}</td><td class="n">${kpiHS(k.diem,cs)}</td><td>${pill(k.st==="duyet"?"Đã duyệt":"Chờ duyệt",k.st==="duyet"?"grn":"amb")}</td><td>${ed&&!mine&&k.st!=="duyet"?`<button class="btn sm pri" data-kd="${k.id}">Duyệt</button>`:""}</td></tr>`}))}</section>
  ${mine&&me?`<section class="card"><div class="card-h"><h2>Tự đánh giá kỳ ${KPM.slice(5)}</h2></div><form class="frm" id="kpf">${[1,2,3].map(i=>`<div class="row4"><label class="field grow">Chỉ tiêu ${i}<input id="kp-c${i}" value="${i===1?"Việc đúng hạn":i===2?"Kết quả chính":"Tuân thủ quy trình"}"></label><label class="field">Kết quả %<input id="kp-k${i}" type="number" min="0" max="150" value="100"></label><label class="field">Trọng số %<input id="kp-t${i}" type="number" min="0" max="100" value="${[50,30,20][i-1]}"></label></div>`).join("")}<button class="btn pri">Gửi tự đánh giá</button></form></section>`:""}`;
  $("#kp-m").onchange=e=>{KPM=e.target.value;renderMain()};
  m.querySelectorAll("[data-kd]").forEach(b=>b.onclick=()=>{DB.mutate(ME.name,"duyệt KPI",dt=>{const k=dt.hr.kpi.find(x=>x.id===b.dataset.kd);k.st="duyet";k.nguoiDuyet=ME.name});renderMain()});
  m.querySelectorAll("[data-ak]").forEach(b=>b.onclick=()=>{const a=autoKPI(b.dataset.ak);DB.mutate(ME.name,"đưa KPI tự động vào kỳ "+KPM,dt=>{dt.hr.kpi=dt.hr.kpi.filter(k=>!(k.thang===KPM&&k.ma===b.dataset.ak));dt.hr.kpi.push({id:uid("kp"),thang:KPM,ma:b.dataset.ak,ct:a.ct,diem:kpiDiem(a.ct),xl:"",st:"cho",nguon:"auto"})});toast("Đã đưa vào phiếu KPI, chờ duyệt");renderMain()});
  if($("#kpf"))$("#kpf").onsubmit=e=>{e.preventDefault();const ct=[1,2,3].map(i=>[$("#kp-c"+i).value,nv($("#kp-k"+i).value)/100,nv($("#kp-t"+i).value)/100]).filter(c=>c[0]&&c[2]);DB.mutate(ME.name,"tự đánh giá KPI "+KPM,dt=>{dt.hr.kpi=dt.hr.kpi.filter(k=>!(k.thang===KPM&&k.ma===me));dt.hr.kpi.push({id:uid("kp"),thang:KPM,ma:me,ct,diem:kpiDiem(ct),xl:"",st:"cho",nguon:"tu"})});toast("Đã gửi, chờ quản lý duyệt");renderMain()};
}
/* ---------- Xét bậc & đánh giá ---------- */
function pHrXetBac(m){
  if(!HRD().loaded){m.innerHTML=H("Xét bậc & đánh giá")+hrEmpty();return}
  const h=HRD(),cs=csOf(hrNow().thang),ed=canHR();
  m.innerHTML=H("Xét bậc & đánh giá",`Chu kỳ ${cs.xetBacThang} tháng · phải qua đủ 4 cửa, ngưỡng ${cs.nguongBac} điểm`)+`<div class="grid kpis">${kpi("Đủ điều kiện trình duyệt",h.xb.filter(x=>/ĐỦ ĐK/.test(x.kl)).length,"","var(--green)")}${kpi("Thiếu KPI",h.xb.filter(x=>/THIẾU KPI/.test(x.kl)).length)}${kpi("Chưa đạt",h.xb.filter(x=>/CHƯA|KHÔNG/.test(x.kl)).length)}</div>
  <section class="card flush"><div class="tbl"><table><thead><tr><th>Nhân viên</th><th>Bậc</th><th class="n">Tháng ở bậc</th><th class="n">KPI TB 3 tháng</th><th class="n">Tháng KPI ≥100%</th><th>Không kỷ luật</th><th class="n">Cửa Kết quả</th><th class="n">Cửa Năng lực</th><th class="n">Cửa Hành vi</th><th class="n">Cửa Phạm vi</th><th class="n">Điểm</th><th>Kết luận</th><th>Xét lại</th><th></th></tr></thead><tbody>
  ${h.xb.map((x,i)=>{const s=staffBy(x.ma),ok=/ĐỦ ĐK/.test(x.kl);return `<tr><td><b>${esc(s.ten)}</b><small>${esc(pbName(s.pb))}</small></td><td>${esc(x.bac)}${x.deNghi?" → "+esc(x.deNghi):""}</td><td class="n">${x.thangOBac}</td><td class="n">${Math.round(x.kpi3*100)}%</td><td class="n">${x.kpi100}</td><td>${esc(x.khongKL)}</td>${x.cua.map(c=>`<td class="n">${c<cs.nguongBac?`<span class="t-red">${c}</span>`:c}</td>`).join("")}<td class="n"><b>${x.diem}</b></td><td>${pill(x.kl,ok?"grn":/THIẾU/.test(x.kl)?"amb":"red")}</td><td>${vndate(x.xetLai)}</td><td>${ed&&ok&&x.st!=="duyet"?`<button class="btn sm pri" data-xb="${i}">Duyệt lên bậc</button>`:x.st==="duyet"?pill("CEO đã duyệt","grn"):""}</td></tr>`}).join("")}</tbody></table></div></section>
  <section class="card"><div class="card-h"><h2>Đánh giá năng lực & hành vi</h2></div>${tbl(["Nhân viên","Kỳ","Năng lực","Hành vi / 360","Tuân thủ SOP","Kỷ luật","Điểm","Xếp loại"],h.dg.map(x=>`<tr><td><b>${esc(staffBy(x.ma).ten)}</b></td><td>${vndate(x.ky)}</td><td class="n">${x.nl}</td><td class="n">${x.hv}</td><td class="n">${x.sop}</td><td>${esc(x.kl)}</td><td class="n"><b>${x.diem}</b></td><td>${pill(x.xl,/Tốt|Xuất/.test(x.xl)?"grn":/Không/.test(x.xl)?"red":"blu")}</td></tr>`))}</section><div class="note">Dữ liệu xét bậc, đánh giá trong file HR MASTER đang là dữ liệu demo. Khi chạy thật, cửa Kết quả lấy từ KPI 3 tháng; KPI lấy số tự động từ vận hành.</div>`;
  m.querySelectorAll("[data-xb]").forEach(b=>b.onclick=()=>{DB.mutate(ME.name,"duyệt lên bậc",dt=>{const x=dt.hr.xb[+b.dataset.xb];x.st="duyet";if(x.deNghi&&dt.hr.ns[x.ma])dt.hr.ns[x.ma].bac=x.deNghi});toast("Đã duyệt. Lương theo bậc mới áp từ kỳ sau");renderMain()});
}
/* ---------- Hợp đồng ---------- */
function pHrHD(m){
  if(!HRD().loaded){m.innerHTML=H("Hợp đồng & thử việc")+hrEmpty();return}
  const h=HRD(),L=D().staff.filter(x=>h.ns[x.ma]&&h.ns[x.ma].hd).map(x=>({x,hd:h.ns[x.ma].hd})).map(o=>({...o,con:daysTo(o.hd.het),tv:daysTo(o.hd.hetTV)})).sort((a,b)=>(a.con??9999)-(b.con??9999));
  m.innerHTML=H("Hợp đồng & thử việc",`${L.length} hồ sơ`)+`<div class="grid kpis">${kpi("Hết hạn trong 45 ngày",L.filter(o=>o.con!=null&&o.con<=45&&o.con>=0).length,"","var(--orange)")}${kpi("Đã quá hạn",L.filter(o=>o.con!=null&&o.con<0).length,"","var(--red)")}${kpi("Chưa ký bản giấy",L.filter(o=>/Chưa/.test(o.hd.giay||"")).length)}</div>
  <section class="card">${tbl(["Nhân viên","Loại HĐ","Số HĐ","Hiệu lực","Hết hạn","Còn (ngày)","Hết thử việc","Bản giấy","Cảnh báo"],L.map(o=>`<tr><td><b>${esc(o.x.ten)}</b><small>${o.x.ma}</small></td><td>${esc(o.hd.loai||"—")}</td><td class="mono">${esc(o.hd.so||"")}</td><td>${vndate(o.hd.hieuLuc)}</td><td>${vndate(o.hd.het)}</td><td class="n">${o.con??"—"}</td><td>${vndate(o.hd.hetTV)}</td><td>${esc(o.hd.giay||"")}</td><td>${o.con!=null&&o.con<0?pill("Quá hạn","red"):o.con!=null&&o.con<=45?pill("Sắp hết hạn","amb"):o.tv!=null&&o.tv>=0&&o.tv<=15?pill("Sắp hết thử việc","amb"):pill("Còn hiệu lực","grn")}</td></tr>`))}</section>`;
}
/* ---------- Tuyển dụng & đào tạo ---------- */
function pHrTD(m){
  const h=HRD(),ed=canHR();
  m.innerHTML=H("Tuyển dụng","Ưu tiên: Sale B2B, CSKH, Booking KOC")+`<div class="grid kpis">${kpi("Đang tuyển",h.td.filter(x=>/Đang/.test(x.tt)).length)}${kpi("Ứng viên",h.td.reduce((a,x)=>a+x.uv,0))}${kpi("Đã nhận việc",h.td.reduce((a,x)=>a+x.nhan,0))}${kpi("Quá hạn tuyển",h.td.filter(x=>/Đang/.test(x.tt)&&daysTo(x.han)<0).length,"","var(--red)")}</div>
  <section class="card">${tbl(["Mã","Vị trí","Phòng","Cần","Ứng viên","Phỏng vấn","Nhận việc","Nguồn","Hạn","Trạng thái"],h.td.map(x=>`<tr><td class="mono">${esc(x.ma)}</td><td><b>${esc(x.viTri)}</b></td><td>${esc(x.pb)}</td><td class="n">${x.sl}</td><td class="n">${x.uv}</td><td class="n">${x.pv}</td><td class="n">${x.nhan}/${x.sl}</td><td>${esc(x.nguon)}</td><td>${vndate(x.han)}${/Đang/.test(x.tt)&&daysTo(x.han)<0?" "+pill("quá hạn","red"):""}</td><td>${pill(x.tt,/Đóng|Đã đóng/.test(x.tt)?"gry":"blu")}</td></tr>`))}</section>
  ${ed?`<section class="card"><div class="card-h"><h2>Mở yêu cầu tuyển</h2></div><form class="frm row7" id="tdf"><label class="field">Vị trí<input id="td-v" required></label><label class="field">Phòng ban<select id="td-p">${opt(D().departments.map(p=>[p.n,p.n]),"Sale B2B")}</select></label><label class="field">Số lượng<input id="td-s" type="number" min="1" value="1"></label><label class="field">Hạn<input id="td-h" type="date"></label><button class="btn pri">Mở</button></form></section>`:""}
  ${h.dt.length?`<section class="card"><div class="card-h"><h2>Đào tạo & onboarding</h2></div>${tbl(["Nhân viên","Chương trình","Loại","Hạn","Tiến độ","Điểm test","Trạng thái"],h.dt.map(x=>`<tr><td><b>${esc(staffBy(x.ma).ten)}</b></td><td>${esc(x.ct)}</td><td>${esc(x.loai)}</td><td>${vndate(x.han)}</td><td class="n">${Math.round(x.tien*100)}%</td><td class="n">${x.diem}</td><td>${pill(x.tt,/Quá/.test(x.tt)?"red":/xong/.test(x.tt)?"grn":"blu")}</td></tr>`))}</section>`:""}`;
  if($("#tdf"))$("#tdf").onsubmit=e=>{e.preventDefault();DB.mutate(ME.name,"mở tuyển "+$("#td-v").value,dt=>dt.hr.td.push({ma:"TD-"+String(dt.hr.td.length+1).padStart(3,"0"),viTri:$("#td-v").value,pb:$("#td-p").value,sl:nv($("#td-s").value),mo:hrNow().iso,han:$("#td-h").value,nguon:"",uv:0,pv:0,nhan:0,tt:"Đang tuyển"}));renderMain()};
}
/* ---------- Cài đặt lương ---------- */
let CDT="cs";
function pHrCaiDat(m){
  const h=HRD(),cs=h.cs[h.cs.length-1],ed=canLuong();
  const F=[["cong","Ngày công chuẩn"],["gio","Giờ / ngày"],["ot","Hệ số OT ngày thường"],["otCN","Hệ số OT CN, lễ"],["anTrua","Ăn trưa (đ/tháng)"],["xang","Xăng xe — Sale, CSKH"],["dt","Điện thoại — Sale, CSKH"],["cc","Chuyên cần"],["docHai","Độc hại — Sản xuất & Kho"],["muonMax","Muộn/về sớm tối đa để giữ chuyên cần"],["bhxh","Tỷ lệ BHXH+BHYT+BHTN người lao động"],["tranBH","Trần nền đóng BHXH"],["gtBan","Giảm trừ bản thân"],["gtNPT","Giảm trừ người phụ thuộc"],["phepNam","Phép năm (ngày)"],["xetBacThang","Chu kỳ xét bậc (tháng)"],["nguongBac","Ngưỡng điểm mỗi cửa"]];
  m.innerHTML=H("Cài đặt lương","Chính sách có ngày hiệu lực — kỳ đã chốt không bị sửa ngược")+`<div class="tabs">${[["cs","Chính sách"],["tl","Thang bảng lương"],["ls","Lịch sử chính sách"]].map(([k,t])=>`<button data-cdt="${k}" class="${CDT===k?"on":""}">${t}</button>`).join("")}</div>
  ${CDT==="cs"?`<section class="card"><div class="card-h"><h2>${esc(cs.ma)} · hiệu lực từ ${vndate(cs.hieuLuc)}</h2></div><div class="note warn">${esc(cs.note||"")}</div><div class="grid cols3">${F.map(([k,l])=>`<label class="field">${l}<input ${ed?"":"disabled"} data-cs="${k}" value="${cs[k]}"></label>`).join("")}<label class="field">Biểu thuế TNCN<select data-cs="bieu" ${ed?"":"disabled"}>${opt([["7","7 bậc (đang dùng trong file)"],["5","5 bậc (luật sửa đổi — kế toán xác nhận)"]],cs.bieu)}</select></label></div>
   ${ed?`<div class="acts"><button class="btn" id="cs-2026">Điền mức mới: giảm trừ 15,5tr / 6,2tr + biểu 5 bậc</button><button class="btn pri" id="cs-new">Lưu thành chính sách mới (chọn ngày hiệu lực)</button></div><p class="hint">Sửa ô bên trên là sửa chính sách hiện tại. Muốn đổi từ một tháng nào đó mà giữ nguyên các tháng trước, bấm "Lưu thành chính sách mới".</p>`:""}</section>`:""}
  ${CDT==="tl"?`<section class="card flush"><div class="tbl"><table><thead><tr><th>Bậc-nấc</th>${HR_NGHE.map(n=>`<th class="n">${n}</th>`).join("")}</tr></thead><tbody>${Object.entries(h.thangLuong).map(([b,v])=>`<tr><td><b>${b}</b></td>${v.map(x=>`<td class="n">${nf(x)}</td>`).join("")}</tr>`).join("")}</tbody></table></div></section><div class="note">Thang lương quản trị L1a–L5c theo 12 nhóm nghề (tab DM_HeThong). Đang là bản dự thảo, chưa ban hành.</div>`:""}
  ${CDT==="ls"?`<section class="card">${tbl(["Mã","Hiệu lực từ","Giảm trừ","Biểu thuế","BHXH"],h.cs.map(c=>`<tr><td>${esc(c.ma)}</td><td>${vndate(c.hieuLuc)}</td><td>${nf(c.gtBan)} / ${nf(c.gtNPT)}</td><td>${c.bieu} bậc</td><td>${(c.bhxh*100).toFixed(1)}%</td></tr>`))}</section>`:""}`;
  m.querySelectorAll("[data-cdt]").forEach(b=>b.onclick=()=>{CDT=b.dataset.cdt;renderMain()});
  m.querySelectorAll("[data-cs]").forEach(x=>x.onchange=()=>{DB.mutate(ME.name,"sửa chính sách lương "+x.dataset.cs,dt=>{const c=dt.hr.cs[dt.hr.cs.length-1];c[x.dataset.cs]=x.dataset.cs==="bieu"?x.value:nv(x.value)});toast("Đã lưu")});
  if($("#cs-2026"))$("#cs-2026").onclick=()=>{DB.mutate(ME.name,"điền mức giảm trừ 2026",dt=>Object.assign(dt.hr.cs[dt.hr.cs.length-1],{gtBan:15500000,gtNPT:6200000,bieu:"5"}));toast("Đã điền. Nhờ kế toán xác nhận trước khi chốt lương");renderMain()};
  if($("#cs-new"))$("#cs-new").onclick=()=>{const d0=prompt("Áp dụng từ ngày (yyyy-mm-dd):",hrNow().thang+"-01");if(!d0||!/^\d{4}-\d{2}-\d{2}$/.test(d0))return;DB.mutate(ME.name,"tạo chính sách lương mới từ "+d0,dt=>{const c=JSON.parse(JSON.stringify(dt.hr.cs[dt.hr.cs.length-1]));c.hieuLuc=d0;c.ma="CS-"+d0.slice(0,7);dt.hr.cs.push(c)});renderMain()};
}
/* ---------- Tổng quan nhân sự ---------- */
function pHrTong(m){
  const h=HRD(),S=D().staff.filter(x=>x.tt!=="Đã nghỉ"),A=[];
  if(h.loaded){D().staff.forEach(x=>{const n=h.ns[x.ma];if(!n||!n.hd)return;const c=daysTo(n.hd.het),t=daysTo(n.hd.hetTV);if(c!=null&&c<0)A.push(["red",`${x.ten}: hợp đồng đã hết hạn ${-c} ngày`,"hr_hd"]);else if(c!=null&&c<=45)A.push(["amb",`${x.ten}: hợp đồng còn ${c} ngày`,"hr_hd"]);if(t!=null&&t>=0&&t<=15)A.push(["amb",`${x.ten}: hết thử việc sau ${t} ngày`,"hr_hd"])});
    Object.entries(h.phep).forEach(([ma,p])=>{if(p.huong-p.da<=1)A.push(["amb",`${staffBy(ma).ten}: sắp hết phép năm`,"hr_nghi"])});h.dt.filter(x=>/Quá/.test(x.tt)).forEach(x=>A.push(["amb",`${staffBy(x.ma).ten}: đào tạo "${x.ct}" quá hạn`,"hr_td"]));h.td.filter(x=>/Đang/.test(x.tt)&&daysTo(x.han)<0).forEach(x=>A.push(["red",`Tuyển ${x.viTri}: quá hạn tuyển ${-daysTo(x.han)} ngày`,"hr_td"]));h.xb.filter(x=>/ĐỦ ĐK/.test(x.kl)&&x.st!=="duyet").forEach(x=>A.push(["grn",`${staffBy(x.ma).ten}: đủ điều kiện lên bậc, chờ duyệt`,"hr_xb"]))}
  const cho=h.don.filter(x=>x.tt==="cho").length+h.tu.filter(x=>x.tt==="cho").length,kc=h.kpi.filter(k=>k.st==="cho").length;if(cho)A.unshift(["amb",`${cho} đơn nghỉ phép / OT / tạm ứng chờ duyệt`,"hr_nghi"]);if(kc)A.unshift(["amb",`${kc} phiếu KPI chờ duyệt`,"hr_kpi"]);
  const quy=h.loaded?S.reduce((a,x)=>a+((h.ns[x.ma]||{}).luong||0),0):0;
  m.innerHTML=H("Tổng quan nhân sự",`${S.length} người đang làm việc`)+`<div class="grid kpis">${kpi("Tổng nhân sự",S.length,KHOI.map(k=>k+" "+S.filter(x=>x.khoi===k).length).join(" · "))}${kpi("Chính thức",S.filter(x=>x.tt==="Chính thức").length,"theo giờ "+S.filter(x=>x.tt==="Theo giờ").length)}${kpi("Quỹ lương cứng / tháng",h.loaded&&canLuong()?money(quy):"—",h.loaded?"chưa gồm phụ cấp, thưởng":"chưa nạp file")}${kpi("Đang tuyển",h.td.filter(x=>/Đang/.test(x.tt)).reduce((a,x)=>a+x.sl-x.nhan,0),"vị trí còn thiếu")}${kpi("Cảnh báo",A.length,"",A.length?"var(--red)":"")}</div>
  ${h.loaded?"":hrEmpty()}
  <div class="xgrid"><section class="card"><div class="card-h"><h2>Việc hành chính cần xử lý</h2></div><div class="xal">${A.map(a=>`<button class="xa ${a[0]==="grn"?"amb":a[0]}" data-go="${a[2]}"><b>${esc(a[1])}</b></button>`).join("")||`<p class="empty">Không có việc cần xử lý.</p>`}</div></section>
  <section class="card"><div class="card-h"><h2>Nhân sự theo phòng ban</h2></div>${tbl(["Phòng ban","Khối","Số người"],D().departments.map(p=>`<tr><td><b>${esc(p.n)}</b></td><td>${esc(p.khoi||"")}</td><td class="n">${S.filter(x=>x.pb===p.k).length}</td></tr>`))}</section></div>
  <section class="card"><div class="card-h"><h2>Luồng dữ liệu</h2></div><div class="flow5">${[["Hồ sơ","phòng ban, vị trí, hợp đồng"],["Chấm công, phép","máy chấm công + đơn trên web"],["KPI","số tự động từ vận hành"],["Bảng lương","chốt → phát hành"],["Đánh giá, xét bậc","3 tháng / lần"]].map((f,i)=>`<div><b>${i+1}. ${f[0]}</b><span>${f[1]}</span></div>`).join("")}</div></section>`;
}
/* ---------- Nhân viên: của tôi ---------- */
function pHrMe(m){
  const ma=ME.maNS,s=ma?staffBy(ma):null,h=HRD(),p=ma?h.phep[ma]:null,D2=h.don.filter(x=>x.ma===ma).slice().reverse();
  m.innerHTML=H("Nhân sự của tôi",s?`${esc(s.ten)} · ${esc(pbName(s.pb))} · ${esc(s.viTri||"")}`:"Tài khoản chưa gắn mã nhân sự")+(!ma?`<section class="card"><p>Nhờ HCNS gắn tài khoản với mã nhân sự ở trang Danh sách nhân sự.</p></section>`:`<div class="grid kpis">${kpi("Mã nhân sự",ma)}${kpi("Ngày vào làm",vndate(s.ngayVao))}${kpi("Phép năm còn",p?p.huong-p.da:"—",p?`đã nghỉ ${p.da}/${p.huong}`:"")}${kpi("Đơn chờ duyệt",D2.filter(x=>x.tt==="cho").length)}</div>
  <section class="card"><div class="card-h"><h2>Gửi đơn</h2><span class="hint">nghỉ phép, OT, tạm ứng</span></div>${donForm(ma)}</section>
  <section class="card"><div class="card-h"><h2>Đơn của tôi</h2></div>${tbl(["Loại","Thời gian","Số lượng","Lý do","Trạng thái"],D2.map(x=>`<tr><td>${esc(x.loai)}</td><td>${vndate(x.tu)}</td><td class="n">${x.sl}</td><td>${esc(x.ly)}</td><td>${pill(x.tt==="cho"?"Chờ duyệt":x.tt==="duyet"?"Đã duyệt":"Từ chối",x.tt==="cho"?"amb":x.tt==="duyet"?"grn":"red")}</td></tr>`))}</section>`);
  if(ma)bindDonForm(ma);
}
Object.assign(PAGES,{hr_tq:pHrTong,hr_hd:pHrHD,hr_cc:pHrCC,hr_nghi:pHrNghi,hr_kpi:m=>pHrKPI(m,false),hr_xb:pHrXetBac,hr_bl:pHrBangLuong,hr_pl:m=>pHrPhieu(m,false),hr_cdl:pHrCaiDat,hr_td:pHrTD,hr_nap:pHrNap,hr_me:pHrMe,hr_kpime:m=>pHrKPI(m,true),hr_plme:m=>pHrPhieu(m,true),hr:pHrTong});
