/* =====================================================================
   TẢI EXCEL LÊN / TẢI EXCEL HIỆN TẠI cho các trang dữ liệu gốc (đồng bộ: thêm mới + cập nhật theo mã)
   ===================================================================== */
const xnum=v=>{if(v==null||v==="")return null;if(typeof v==="number")return v;const s=String(v).replace(/[₫đ\s%]/g,"");if(/^-?\d{1,3}(\.\d{3})+$/.test(s))return +s.replace(/\./g,"");const n=+s.replace(/,/g,"");return isFinite(n)?n:null};
const xbool=v=>!/^(ngừng|không|0|false|no|tắt)$/i.test(String(v??"").trim());
const xnorm=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g,"").replace(/đ/g,"d").replace(/[^a-z0-9%]/g,"");
function xParse(rows,spec){
  const al=spec.cols.map(c=>[c[1]].concat(c[2]||[]).map(xnorm));let hi=-1,map=null;
  for(let i=0;i<Math.min(15,rows.length);i++){const r=(rows[i]||[]).map(xnorm);const m=al.map(a=>r.findIndex(x=>x&&a.includes(x)));if(m.filter(x=>x>=0).length>=Math.min(2,spec.cols.length)&&m[0]>=0){hi=i;map=m;break}}
  if(hi<0)return {err:`Không tìm thấy dòng tiêu đề có cột "${spec.cols[0][1]}". Tải "Excel hiện tại" về để xem mẫu cột.`};
  const out=[];rows.slice(hi+1).forEach(r=>{if(!r)return;const o={};spec.cols.forEach((c,j)=>{const i=map[j];if(i<0)return;const v=r[i];o[c[0]]=c[3]==="num"?xnum(v):c[3]==="bool"?(v==null||v===""?undefined:xbool(v)):v==null?"":String(v).trim()});if(spec.key&&!o[spec.cols[0][0]])return;if(!spec.key&&Object.values(o).every(v=>v===""||v==null))return;out.push(o)});
  return {rows:out,found:spec.cols.filter((c,j)=>map[j]>=0).map(c=>c[1]),missing:spec.cols.filter((c,j)=>map[j]<0).map(c=>c[1])};
}
function xReadFile(f){return new Promise((res,rej)=>{if(typeof XLSX==="undefined"){toast("Cần mạng để đọc Excel");rej();return}const r=new FileReader();r.onload=()=>{try{const wb=XLSX.read(r.result,{type:"array"});const sheets=wb.SheetNames.map(n=>[n,XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,raw:true,defval:null})]);res(sheets)}catch(e){toast("Không đọc được file");rej(e)}};r.readAsArrayBuffer(f)})}
function xExport(spec){if(typeof XLSX==="undefined"){toast("Cần mạng để xuất Excel");return}const R=spec.rows();const ws=XLSX.utils.aoa_to_sheet([spec.cols.map(c=>c[1])].concat(R.map(o=>spec.cols.map(c=>c[3]==="bool"?(o[c[0]]?"Có":"Ngừng"):o[c[0]]??""))));ws["!cols"]=spec.cols.map(c=>({wch:Math.max(12,c[1].length+2)}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,spec.sheet||"Du lieu");XLSX.writeFile(wb,spec.file+".xlsx")}
function xBar(id,spec){return `<div class="xbar"><span class="xb-t">📄 ${esc(spec.hint||"Sửa trên Excel rồi tải lên lại để đồng bộ")}</span><span class="sp"></span><button class="btn" data-xe="${id}">⬇ Tải Excel hiện tại</button><label class="btn pri">⬆ Tải Excel lên<input type="file" accept=".xlsx,.xls,.csv" data-xi="${id}" hidden></label></div>`}
const XSPEC={};
function xBind(m){
  m.querySelectorAll("[data-xe]").forEach(b=>b.onclick=()=>xExport(XSPEC[b.dataset.xe]()));
  m.querySelectorAll("[data-xi]").forEach(inp=>inp.onchange=async()=>{const f=inp.files[0];inp.value="";if(!f)return;const spec=XSPEC[inp.dataset.xi]();const sheets=await xReadFile(f);let res=null,sh="";for(const [n,rows] of sheets){const r=xParse(rows,spec);if(!r.err&&r.rows.length){res=r;sh=n;break}if(!res)res=r}if(res.err){toast(res.err);return}xPreview(spec,res,f.name,sh)});
}
function xPreview(spec,res,fname,sh){
  const plan=spec.plan(res.rows,{});const add=plan.filter(p=>p.op==="add").length,upd=plan.filter(p=>p.op==="upd").length,same=plan.filter(p=>p.op==="same").length,bad=plan.filter(p=>p.op==="bad");
  openDrawerHTML(`<h2>Đồng bộ từ Excel</h2><p class="hint">${esc(fname)} · trang tính "${esc(sh)}" · ${res.rows.length} dòng</p>
   <div class="grid kpis">${kpi("Thêm mới",add)}${kpi("Cập nhật",upd)}${kpi("Không đổi",same)}${bad.length?kpi("Bỏ qua (lỗi)",bad.length):""}</div>
   <p class="hint">Đọc được cột: <b>${res.found.map(esc).join(", ")}</b>${res.missing.length?` · không có cột: ${res.missing.map(esc).join(", ")} (giữ nguyên số cũ)`:""}</p>
   ${spec.month?`<label class="field">${esc(spec.month)}<input type="month" id="xp-m" value="${spec.monthDef()}"></label>`:""}${spec.replace?`<label class="ck"><input type="checkbox" id="xp-r"> ${esc(spec.replace)}</label>`:""}
   ${tbl(["Thao tác"].concat(spec.preview.map(c=>c[1])),plan.filter(p=>p.op!=="same").slice(0,12).map(p=>`<tr><td>${p.op==="add"?pill("Thêm","grn"):p.op==="upd"?pill("Cập nhật","blu"):pill("Bỏ qua","red")}</td>${spec.preview.map(c=>`<td>${esc(p.row[c[0]]??"")}${p.diff&&p.diff[c[0]]!==undefined?`<small class="t-red"> (cũ: ${esc(p.diff[c[0]])})</small>`:""}</td>`).join("")}</tr>`))}
   ${bad.length?`<p class="hint t-red">${bad.slice(0,5).map(b=>esc(b.why)).join(" · ")}</p>`:""}
   <div class="acts"><button class="btn pri" id="xp-ok" ${add+upd||spec.replace?"":"disabled"}>Đồng bộ ${add+upd} dòng</button><button class="btn" id="xp-no">Hủy</button></div>`);
  $("#xp-no").onclick=closeDrawer;
  $("#xp-ok").onclick=()=>{const opts={month:$("#xp-m")?$("#xp-m").value:"",replace:$("#xp-r")?$("#xp-r").checked:false};let n=0;DB.mutate(ME.name,`đồng bộ Excel ${spec.file}: ${fname}`,dt=>{n=spec.apply(dt,spec.plan(res.rows,opts),opts)});closeDrawer();toast(`Đã đồng bộ ${n} dòng`);renderMain()};
}
/* ---------- Đặc tả từng trang ---------- */
const diffOf=(old,row,fields)=>{const d={};fields.forEach(f=>{if(row[f]!==undefined&&row[f]!==null&&row[f]!==""&&String(row[f])!==String(old[f]??""))d[f]=old[f]??""});return d};
const keyPlan=(rows,list,kf,okf,fields,valid)=>rows.map(r=>{const k=String(r[kf]).trim();if(valid){const w=valid(r);if(w)return {op:"bad",row:r,why:w}}const o=list.find(x=>String(x[okf]).trim().toLowerCase()===k.toLowerCase());if(!o)return {op:"add",row:r};const d=diffOf(o,r,fields);return {op:Object.keys(d).length?"upd":"same",row:r,diff:d,old:o}});
XSPEC.sku=()=>{const d=D(),months=[...new Set(d.skus.flatMap(s=>Object.keys(s.giaVon||{})))].sort(),last=months[months.length-1]||"";return {file:"SKU-gia-von",sheet:"SKU gia von",hint:"File giá thành của kế toán, file NHAP_Gia_von (Pancake) hay bảng GIA_VON (Shopee) đều đọc được",month:"Giá vốn ghi cho tháng",monthDef:()=>last||hrNow().thang,
  cols:[["ma","Mã SKU",["Mã thành phẩm","Mã nội bộ","Mã"]],["ten","Tên thành phẩm",["Tên sản phẩm","Tên hàng","Tên"]],["k","Thuộc sản phẩm",["Mã sản phẩm"]],["qc","Quy cách"],["gv","Giá vốn",["Giá thành đơn vị","TỔNG GIÁ VỐN","Giá vốn đơn vị (đ)","Giá vốn đơn vị","Giá thành"],"num"],["giaBan","Giá bán lẻ",["Giá bán niêm yết","Giá bán"],"num"],["active","Đang bán",[],"bool"]],
  preview:[["ma","Mã"],["ten","Tên"],["gv","Giá vốn"],["giaBan","Giá bán"]],
  rows:()=>d.skus.map(s=>({ma:s.ma,ten:s.ten,k:s.k,qc:s.qc,gv:(s.giaVon||{})[last]||"",giaBan:s.giaBan||"",active:s.active})),
  plan:(rows,o)=>rows.map(r=>{const s=d.skus.find(x=>x.ma.toLowerCase()===String(r.ma).toLowerCase());if(!s)return {op:"add",row:r};const dd2={};const th=o.month||last;if(r.gv!=null&&r.gv!==(s.giaVon||{})[th])dd2.gv=(s.giaVon||{})[th]??"";["ten","qc","giaBan"].forEach(f=>{if(r[f]!=null&&r[f]!==""&&String(r[f])!==String(s[f]??""))dd2[f]=s[f]??""});if(r.k&&r.k!==s.k)dd2.k=s.k;if(r.active!==undefined&&r.active!==s.active)dd2.active=s.active?"Có":"Ngừng";return {op:Object.keys(dd2).length?"upd":"same",row:r,diff:dd2}}),
  apply:(dt,P,o)=>{let n=0;P.forEach(p=>{if(p.op==="same"||p.op==="bad")return;const r=p.row;let s=dt.skus.find(x=>x.ma.toLowerCase()===String(r.ma).toLowerCase());if(!s){s={ma:String(r.ma),ten:r.ten||"",k:r.k||guessSku(r.ten||"")||"KHAC",qc:r.qc||"",giaVon:{},giaBan:0,active:true};dt.skus.push(s)}if(r.ten)s.ten=r.ten;if(r.k)s.k=r.k;if(r.qc)s.qc=r.qc;if(r.gv!=null)s.giaVon[o.month||last||hrNow().thang]=Math.round(r.gv);if(r.giaBan!=null)s.giaBan=r.giaBan;if(r.active!==undefined)s.active=r.active;n++});return n}}};
XSPEC.sanpham=()=>{const d=D(),C=d.catalog||[];const F=["n","nhom","gia","mo","pain","claim"];return {file:"Danh-muc-san-pham",sheet:"San pham",
  cols:[["k","Mã",["Mã sản phẩm"]],["n","Tên sản phẩm",["Tên"]],["nhom","Nhóm",["Nhóm hàng","Nhóm sản phẩm"]],["gia","Giá trị đơn TB",["Giá trị đơn trung bình","Giá bán"],"num"],["mo","Mô tả"],["pain","Vấn đề của khách",["Pain"]],["claim","Lưu ý claim",["Claim"]],["active","Đang bán",[],"bool"]],
  preview:[["k","Mã"],["n","Tên"],["nhom","Nhóm"],["gia","Giá TB"]],rows:()=>C,
  plan:rows=>keyPlan(rows,C,"k","k",F,r=>/^[A-Za-z0-9]+$/.test(String(r.k))?"":`Mã "${r.k}" chỉ dùng chữ không dấu và số`),
  apply:(dt,P)=>{let n=0;P.forEach(p=>{if(p.op==="same"||p.op==="bad")return;const r=p.row;let c=dt.catalog.find(x=>x.k.toLowerCase()===String(r.k).toLowerCase());if(!c){c={k:String(r.k).toUpperCase(),n:"",nhom:"Khác",c:"#0e7c86",gia:0,mo:"",pain:"",claim:"",kenh:"TikTok chính",active:true};dt.catalog.push(c)}F.forEach(f=>{if(r[f]!=null&&r[f]!=="")c[f]=r[f]});if(r.active!==undefined)c.active=r.active;const pp=dt.products.find(x=>x.k===c.k);if(pp)["n","gia","mo","pain","claim"].forEach(f=>{if(r[f]!=null&&r[f]!=="")pp[f]=r[f]});n++});return n}}};
XSPEC.kenhban=()=>{const d=D(),F=["loai","phiSan","phiTT","phiDV","affiliate","vc","note"];return {file:"Kenh-ban-phi",sheet:"Kenh ban",
  cols:[["n","Kênh",["Kênh bán","Tên kênh"]],["loai","Loại"],["phiSan","Phí cố định %",["Phí sàn %","Hoa hồng cố định %"],"num"],["phiTT","Phí thanh toán %",["Phí xử lý giao dịch %"],"num"],["phiDV","Phí dịch vụ %",["Phí dịch vụ / voucher %"],"num"],["affiliate","Hoa hồng affiliate %",["Affiliate %"],"num"],["vc","Vận chuyển TB / đơn",["Vận chuyển"],"num"],["note","Ghi chú"],["active","Đang bán",[],"bool"]],
  preview:[["n","Kênh"],["phiSan","Cố định %"],["phiTT","Thanh toán %"],["phiDV","Dịch vụ %"],["affiliate","Affiliate %"]],rows:()=>d.saleChannels,
  plan:rows=>keyPlan(rows,d.saleChannels,"n","n",F),
  apply:(dt,P)=>{let n=0;P.forEach(p=>{if(p.op==="same"||p.op==="bad")return;const r=p.row;let c=dt.saleChannels.find(x=>x.n.toLowerCase()===String(r.n).toLowerCase());if(!c){c={k:uid("ch"),n:r.n,loai:"Khác",phiSan:0,phiTT:0,phiDV:0,affiliate:0,vc:0,note:"",active:true};dt.saleChannels.push(c)}F.forEach(f=>{if(r[f]!=null&&r[f]!=="")c[f]=r[f]});if(r.active!==undefined)c.active=r.active;n++});return n}}};
XSPEC.chiphidm=()=>{const d=D(),F=["n","nhom","loai","phanBo","pb","note"];return {file:"Danh-muc-chi-phi",sheet:"Danh muc chi phi",
  cols:[["k","Mã",["Mã khoản chi"]],["n","Khoản chi",["Tên khoản chi"]],["nhom","Nhóm P&L",["Nhóm"]],["loai","Loại",["Cố định / biến đổi"]],["phanBo","Phân bổ theo"],["pb","Phòng ban chịu",["Mã phòng ban","Phòng ban"]],["note","Ghi chú"]],
  preview:[["k","Mã"],["n","Khoản chi"],["nhom","Nhóm"],["loai","Loại"]],rows:()=>d.costCats,
  plan:rows=>keyPlan(rows,d.costCats,"k","k",F,r=>r.nhom&&!COST_GROUPS.includes(r.nhom)?`Nhóm "${r.nhom}" không có (dùng: ${COST_GROUPS.join(", ")})`:""),
  apply:(dt,P)=>{let n=0;P.forEach(p=>{if(p.op==="same"||p.op==="bad")return;const r=p.row;let c=dt.costCats.find(x=>x.k.toLowerCase()===String(r.k).toLowerCase());if(!c){c={k:String(r.k).toUpperCase(),n:"",nhom:"Khác",loai:"Cố định",phanBo:"Toàn công ty",pb:"BDH",note:""};dt.costCats.push(c)}F.forEach(f=>{if(r[f]!=null&&r[f]!=="")c[f]=f==="pb"?((dt.departments.find(x=>x.k===r[f]||x.n===r[f])||{k:r[f]}).k):r[f]});n++});return n}}};
XSPEC.chiphi=()=>{const d=D();return {file:"Chi-phi-"+CPM,sheet:"Chi phi",hint:"Mỗi dòng một khoản chi. Sau này nối thẳng file xuất MISA",month:"Ghi vào tháng (nếu file không có cột Tháng)",monthDef:()=>CPM,replace:"Xóa chi phí đã nhập của tháng này trước khi đồng bộ (tránh nhập trùng khi tải lại file đã sửa)",
  cols:[["thang","Tháng"],["cat","Mã khoản chi",["Khoản chi","Mã"]],["pb","Phòng ban"],["kenh","Kênh"],["sku","Sản phẩm"],["tien","Số tiền",["Thành tiền","Giá trị"],"num"],["note","Ghi chú",["Diễn giải"]]],
  preview:[["thang","Tháng"],["cat","Khoản chi"],["tien","Số tiền"],["note","Ghi chú"]],rows:()=>d.costs.filter(c=>c.thang===CPM),
  plan:(rows,o)=>rows.map(r=>{const k=String(r.cat||"").trim().toUpperCase();const cat=d.costCats.find(c=>c.k===k||c.n.toLowerCase()===String(r.cat||"").toLowerCase());if(!cat)return {op:"bad",row:r,why:`Khoản chi "${r.cat}" chưa có trong Danh mục chi phí`};if(!r.tien)return {op:"bad",row:r,why:"Thiếu số tiền"};return {op:"add",row:{...r,cat:cat.k,thang:/^\d{4}-\d{2}/.test(String(r.thang||""))?String(r.thang).slice(0,7):(o.month||CPM)}}}),
  apply:(dt,P,o)=>{const th=o.month||CPM;if(o.replace)dt.costs=dt.costs.filter(c=>c.thang!==th);let n=0;P.filter(p=>p.op==="add").forEach(p=>{const r=p.row;dt.costs.push({id:uid("cp"),thang:r.thang,cat:r.cat,pb:(dt.departments.find(x=>x.k===r.pb||x.n===r.pb)||{k:""}).k,kenh:r.kenh||"",sku:r.sku||"",tien:r.tien,note:r.note||"",by:ME.name});n++});return n}}};
XSPEC.b2b_gia=()=>{const d=D().b2b;return {file:"Bang-gia-B2B-8-cap",sheet:"Bang gia",hint:"Bảng giá 8 cấp: mỗi dòng một sản phẩm, mỗi cột một cấp",
  cols:[["k","Mã",["Mã SKU","Mã sản phẩm"]],["n","Sản phẩm",["Tên sản phẩm","Tên"]]].concat(TIERS.map((t,i)=>["t"+i,t[1],[t[0]],"num"])),
  preview:[["k","Mã"],["n","Sản phẩm"],["t0","GĐKD"],["t7","Bán lẻ"]],
  rows:()=>d.products.map(p=>Object.assign({k:p.k,n:p.n},...p.gia.map((g,i)=>({["t"+i]:g})))),
  plan:rows=>rows.map(r=>{const p=d.products.find(x=>x.k.toLowerCase()===String(r.k).toLowerCase());const g=TIERS.map((t,i)=>r["t"+i]);if(g.some((v,i)=>v!=null&&i&&g[i-1]!=null&&v<g[i-1]))return {op:"bad",row:r,why:`${r.k}: giá cấp sau phải ≥ cấp trước`};if(!p)return {op:"add",row:r};const dd2={};TIERS.forEach((t,i)=>{if(r["t"+i]!=null&&r["t"+i]!==p.gia[i])dd2["t"+i]=p.gia[i]});if(r.n&&r.n!==p.n)dd2.n=p.n;return {op:Object.keys(dd2).length?"upd":"same",row:r,diff:dd2}}),
  apply:(dt,P)=>{let n=0;P.forEach(p=>{if(p.op==="same"||p.op==="bad")return;const r=p.row;let x=dt.b2b.products.find(y=>y.k.toLowerCase()===String(r.k).toLowerCase());if(!x){x={k:String(r.k),n:r.n||String(r.k),nhom:"",unit:"Chai",pack:"",gia:TIERS.map(()=>null)};dt.b2b.products.push(x)}if(r.n)x.n=r.n;TIERS.forEach((t,i)=>{if(r["t"+i]!=null)x.gia[i]=r["t"+i]});n++});return n}}};
/* gắn thanh tải lên vào trang */
const XCAN={sku:()=>can(ME,"thietlap.quanly"),sanpham:()=>can(ME,"sanpham.quanly"),kenhban:()=>can(ME,"thietlap.quanly"),chiphidm:()=>can(ME,"thietlap.quanly"),chiphi:()=>can(ME,"chiphi.nhap"),b2b_gia:()=>ME.role==="admin"};
Object.keys(XSPEC).forEach(k=>{const orig=PAGES[k];if(!orig)return;PAGES[k]=m=>{orig(m);if(!XCAN[k]())return;const ph=m.querySelector(".ph");const h=xBar(k,XSPEC[k]());if(ph)ph.insertAdjacentHTML("afterend",h);else m.insertAdjacentHTML("afterbegin",h);xBind(m)}});
