/* =====================================================================
   BÁO CÁO KINH DOANH (toàn công ty + từng kênh) · DIGITAL ADS FB · SALE B2C FACEBOOK · KẾ TOÁN
   Nguồn: BÁO CÁO DIGITAL MKT 2026 FINAL (Ads FB) + AILLA_Pancake_v5 (đơn Facebook). Chỉ nhúng số tổng hợp.
   ===================================================================== */
let KDX=(typeof KD!=="undefined"&&KD)?KD:{adsPeople:[],adsProd:[],adsTran:[],adsMonths:[],adsChiDay:[],fbHist:[],fbDash:{},fbSale:[],fbNhom:[]};
const tr=v=>v?money(v):"—";
const pc=(a,b)=>b?(a/b*100).toFixed(1)+"%":"—";
const cleanN=s=>String(s||"").replace(/\\n/g," ").replace(/\s+/g," ").trim();
const srcNote=t=>`<div class="hint src">Nguồn: ${t}</div>`;
const needFile=(t,what)=>`<section class="card waitf"><h2>${t}</h2><p>${what}</p><p class="hint">Chị gửi file (link Google Sheet hoặc Excel) là em đấu vào trang này, giống cách đã làm với báo cáo Digital và Pancake.</p></section>`;
const barRow=(vals,lbl,fmt)=>{const mx=Math.max(1,...vals);return `<div class="dbar">${vals.map((v,i)=>`<div class="b" title="${lbl(i)}: ${fmt(v)}"><i style="height:${v?Math.max(3,v/mx*100):0}%"></i></div>`).join("")}</div>`};

/* ---------- Toàn công ty ---------- */
function pBcTong(m){
  const F=KDX.fbHist,f8=F.find(x=>x["Kỳ"]==="2026-08")||{},f9=F.find(x=>String(x["Kỳ"]).startsWith("2026-09"))||{};
  const ads9=sum(KDX.adsPeople,p=>p.dt),chi9=sum(KDX.adsPeople,p=>p.chi),A=m7=>(KDX.adsMonths.find(x=>x.m===m7)||{}).tong;
  const T7=KDX.tts?plv(KDX.tts.pl,/^Doanh thu thuần/):0,TL7=KDX.tts?plv(KDX.tts.pl,/^LÃI ĐÓNG GÓP/):0,S7=KDX.spe?plv(KDX.spe.pl,/^Doanh thu thuần/):0,SL7=KDX.spe?plv(KDX.spe.pl,/^LÃI ĐÓNG GÓP/):0;
  const rows=[
   ["TikTok Shop (cả shop, doanh thu thuần)",tr(T7),"—","~1,4 tỷ GMV video (chị báo)","Báo cáo quản trị TikTok, chốt sổ ngày 8","amb","Có T7 · chờ T8, T9"],
   ["   trong đó qua KOC / Affiliate (đã nằm trong TikTok)",KDX.tts?tr(plv(KDX.tts.kocPL,/^Doanh thu quy đổi/)):"—","—","—","TikTok M3_KOC","amb","Có T7"],
   ["Shopee 2 shop (doanh thu thuần)",tr(S7),"—","—","Báo cáo quản trị Shopee, chốt sổ ngày 8","amb","Có T7 · chờ T8, T9"],
   ["Facebook (Pancake, đơn giao thành công)","—",tr(f8["Doanh thu ghi nhận"]),tr(f9["Doanh thu ghi nhận"])+` <small>(1–${f9["Số ngày"]||"?"}/9)</small>`,"Sheet Pancake (tự kéo 7h sáng)","grn","Có T8, T9"],
   ["   Ads Facebook mang về (đơn chốt)",tr(A("2026-07")),tr(A("2026-08")),tr(ads9),"Báo cáo Digital","grn","Có T7, T8, T9"],
   ["B2B / Đại lý","—","—","—","CRM B2B","amb","Nối khi gộp CRM"],
  ];
  const ld=[["TikTok Shop",T7,TL7,"sau giá vốn, phí sàn, ads, agency, KOC, live"],["Shopee 2 shop",S7,SL7,"sau giá vốn, phí sàn, Shopee Ads"]];
  const CR=chanRows();
  m.innerHTML=H("Tổng quan kinh doanh","Doanh thu và lãi theo kênh")+`<section class="card pblk"><div class="card-h"><h2>Trong kỳ đã chọn</h2><span class="pill p-blu">${esc(pLabel())}</span></div>${tbl(["Kênh","Cách tính","Doanh thu","Lãi gộp","Dữ liệu"],CR.slice(0,4).map(s=>`<tr class="clk" data-go="${s[6]}"><td><b>${s[1]}</b></td><td class="hint">${s[2]}</td><td class="n">${tr(s[3])}</td><td class="n">${s[4]===""?"—":tr(s[4])}</td><td class="hint">${s[5]}</td></tr>`))}</section><h3 class="sech">Theo tháng chốt sổ</h3><div class="grid kpis">${kpi("TikTok Shop T7",tr(T7),"lãi kênh "+tr(TL7)+" · "+pc(TL7,T7))}${kpi("Shopee T7",tr(S7),"lãi kênh "+tr(SL7)+" · "+pc(SL7,S7))}${kpi("Facebook T9 (1–"+(f9["Số ngày"]||"?")+"/9)",tr(f9["Doanh thu ghi nhận"]),"đơn giao thành công · T8 "+tr(f8["Doanh thu ghi nhận"]))}${kpi("Ads Facebook T9",tr(ads9),"chi "+tr(chi9)+" · ROAS "+(chi9?(ads9/chi9).toFixed(2):"—"))}</div>
  <section class="card"><div class="card-h"><h2>Doanh thu theo kênh</h2></div>${tbl(["Kênh","Tháng 7","Tháng 8","Tháng 9","Lấy số từ","Dữ liệu"],rows.map(r=>`<tr${r[0].startsWith("   ")?' class="sub"':""}><td><b>${r[0].trim()}</b></td><td class="n">${r[1]}</td><td class="n">${r[2]}</td><td class="n">${r[3]}</td><td>${r[4]}</td><td>${pill(r[6],r[5])}</td></tr>`))}
  <div class="note">Mỗi kênh tính một kiểu. TikTok, Shopee tính <b>doanh thu thuần đã chốt sổ</b> (đã loại hủy, hoàn). Facebook tính <b>đơn đã giao thành công</b>. Ads Facebook tính <b>đơn đã chốt</b> (chưa trừ hủy, hoàn). Vì vậy không cộng thẳng các dòng với nhau. Mỗi kênh chốt sổ đủ 3 tháng thì dòng tổng công ty mới hiện.</div></section>
  <section class="card"><div class="card-h"><h2>Lãi đóng góp từng kênh · tháng 7</h2><span class="hint">chưa trừ lương, kho, chi phí chung</span></div>${tbl(["Kênh","Doanh thu thuần","Lãi đóng góp","Biên","Đã trừ"],ld.map(r=>`<tr><td><b>${r[0]}</b></td><td class="n">${tr(r[1])}</td><td class="n">${tr(r[2])}</td><td class="n">${pill(pc(r[2],r[1]),r[2]/r[1]>=.185?"grn":"amb")}</td><td class="hint">${r[3]}</td></tr>`))}<div class="note">Mục tiêu biên lãi đóng góp: 18,5%. Facebook chưa có tháng 7. Kỳ 13–28/9 lãi gộp Facebook đạt 74,6% nhưng chưa trừ quảng cáo, xem trang Facebook.</div></section>
  <section class="card"><div class="card-h"><h2>Xem chi tiết từng kênh</h2></div><div class="acts">${[["bc_tiktok","TikTok Shop"],["bc_fb","Facebook (Pancake)"],["bc_shopee","Shopee"],["bc_b2b","B2B / Đại lý"],["pl","P&L lãi lỗ"]].map(([k,t])=>`<button class="btn" data-go="${k}">${t} →</button>`).join("")}</div></section>`;
}
/* ---------- Kênh Facebook (Pancake) ---------- */
function fbFunnel(){const F=KDX.fbHist;return tbl(["Chỉ số","Tháng 8","Tháng 9 (1–"+((F[1]||{})["Số ngày"]||"?")+"/9)"],[["Tổng đơn tạo","Tổng đơn tạo",nf],["Đã chốt","Đã chốt",nf],["Giao thành công","Giao TC",nf],["Đơn hủy","Đơn hủy",nf],["Đơn hoàn","Đơn hoàn",nf],["Chưa xử lý","Đơn chưa xử lý",nf],["Tỷ lệ chốt","Tỷ lệ chốt %",v=>v+"%"],["Tỷ lệ hủy","Tỷ lệ hủy %",v=>v+"%"],["Tỷ lệ hoàn","Tỷ lệ hoàn %",v=>v+"%"],["Doanh thu ghi nhận (giao TC)","Doanh thu ghi nhận",money],["Giá trị TB / đơn","AOV",nf],["Số sản phẩm / đơn","SL SP/đơn",v=>v],["Số khách","Số khách",nf],["Khách mua lại","Khách mua lại %",v=>v+"%"]].filter(([l,k])=>F.some(x=>x[k]!=null)).map(([l,k,f])=>`<tr><td>${l}</td>${F.map(x=>`<td class="n">${x[k]!=null?f(x[k]):"—"}</td>`).join("")}</tr>`))}
function fbSaleTbl(){const hasDt=KDX.fbSale.some(s=>s.dt!=null);return tbl(["Hạng","Người xử lý đơn"].concat(hasDt?["Doanh thu"]:[],["Đơn tạo"]).concat(["Chốt","Giao TC","Hủy","Hoàn","Chưa xử lý","Tỷ lệ chốt","Tỷ lệ hủy","Cảnh báo"]),KDX.fbSale.map((s,i)=>{const tc=s.tao?s.chot/s.tao*100:0,th=s.tao?s.huy/s.tao*100:0;const w=[];if(th>20)w.push(pill("hủy cao","red"));if(s.cxl&&s.cxl/s.tao>.1)w.push(pill("tồn đơn","amb"));if(s.n==="(chưa gán)")w.push(pill("chưa gán người","amb"));return `<tr><td>${i+1}</td><td><b>${esc(s.n)}</b></td>${hasDt?`<td class="n">${tr(s.dt)}</td>`:""}<td class="n">${nf(s.tao)}</td><td class="n">${nf(s.chot)}</td><td class="n">${nf(s.giao)}</td><td class="n">${nf(s.huy)}</td><td class="n">${nf(s.hoan)}</td><td class="n">${nf(s.cxl)}</td><td class="n">${s.tao?tc.toFixed(1)+"%":"—"}</td><td class="n">${s.tao?th.toFixed(1)+"%":"—"}</td><td>${w.join(" ")||"—"}</td></tr>`}))}
function pBcFb(m){
  const F=KDX.fbHist,f9=F[1]||{},Dd=KDX.fbDash,N=KDX.fbNhom;
  const g=i=>pSum("fb",i).v,dtChot=g(6),A=adsSum(),dtAds=sum(Object.values(A),a=>a.dt),dtCS=Math.max(0,dtChot-dtAds),has=dtChot>0;
  const src=[["Doanh thu từ quảng cáo","Đơn chốt từ khách vào qua quảng cáo Facebook (doanh số Digital ghi nhận)",dtAds,"fb_ads","pnk"],["Doanh thu từ CSKH","Khách cũ mua lại, khách chăm sóc qua inbox (tạm tính = doanh thu chốt − doanh thu quảng cáo; CSKH triển khai tháng sau)",dtCS,"fb_cskh","grn"]];
  m.innerHTML=H("Facebook","Doanh thu kênh Facebook chia theo nguồn tạo ra doanh thu")+`<section class="card"><div class="card-h"><h2>Doanh thu theo nguồn</h2><span class="pill p-blu">${esc(pLabel())}</span></div>${has?`<div class="srcgrid">${src.map(([t,h,v,go,c])=>`<button class="srcbox t-${c}" data-go="${go}"><div class="l">${t}</div><div class="v">${go==="fb_cskh"&&dtAds>=dtChot?"—":tr(v)}</div><div class="p">${go==="fb_cskh"&&dtAds>=dtChot?"chưa tách được":pc(v,dtChot)+" doanh thu chốt"}</div><div class="h">${h}</div></button>`).join("")}</div><p class="hint">Tổng doanh thu chốt trên Pancake trong kỳ: <b>${tr(dtChot)}</b>. Bấm từng ô để xem chi tiết hoạt động.</p>${dtAds>=dtChot?`<div class="note">Doanh số quảng cáo Digital báo (${tr(dtAds)}) đang <b>cao hơn</b> doanh thu chốt trên Pancake (${tr(dtChot)}), nên chưa tách được phần doanh thu do CSKH tạo ra. Muốn tách đúng: trên Pancake gắn <b>nguồn đơn</b> cho từng đơn (Quảng cáo / Khách cũ – CSKH), web sẽ cộng theo nguồn đó.</div>`:""}`:`<p class="empty">Kỳ đã chọn chưa có số Facebook.</p>`}</section>
  <section class="card"><div class="card-h"><h2>Phễu đơn hàng theo tháng</h2><span class="hint">báo cáo Pancake</span></div>${fbFunnel()}</section>
  <section class="card"><div class="card-h"><h2>Lãi đóng góp kênh</h2><span class="hint">kỳ ${esc(Dd.ky||"")} · tính trên đơn giao thành công</span></div>${tbl(["Khoản","Số tiền","% doanh thu"],[["Doanh thu ghi nhận",Dd.dt],["− Giá vốn hàng bán",Dd.gv],["− Phí vận chuyển",Dd.vc],["− Ship đơn hoàn (2 chiều)",Dd.hoan],["= Lãi gộp",Dd.laigop],["− Chi phí quảng cáo","chưa kéo"]].map(([l,v])=>`<tr class="${l.startsWith("=")?"tot":""}"><td>${l}</td><td class="n">${typeof v==="number"?nf(v):v}</td><td class="n">${typeof v==="number"&&Dd.dt?Math.abs(v/Dd.dt*100).toFixed(1)+"%":"—"}</td></tr>`))}<div class="note">Sheet Pancake chưa kéo chi phí Ads nên lãi gộp đang chưa trừ quảng cáo. Trên web này hai báo cáo nằm chung một chỗ. Khi có số chi Ads tháng 9 thì lãi sau quảng cáo sẽ tự trừ ra. ROAS hòa vốn theo sheet: <b>${Dd.roasHoaVon||"—"}</b>.</div></section>
  <section class="card"><div class="card-h"><h2>Theo nhóm sản phẩm · tháng 9</h2><span class="hint">không tính đơn hủy, đơn hoàn</span></div>${tbl(["Nhóm hàng","Số đơn","Số lượng","Doanh thu","Giá vốn","Biên gộp"],N.map(x=>`<tr><td><b>${esc(x.n)}</b></td><td class="n">${nf(x.don)}</td><td class="n">${nf(x.sl)}</td><td class="n">${tr(x.dt)}</td><td class="n">${tr(x.gv)}</td><td class="n">${x.dt?pill(Math.round((x.dt-x.gv)/x.dt*100)+"%",(x.dt-x.gv)/x.dt>.6?"grn":"amb"):"—"}</td></tr>`))}</section>
  ${srcNote("Google Sheet AILLA_Pancake_v5 (LICH_SU, DASHBOARD_CHUNG, DASHBOARD_SALE, DATA_San_pham). Bản thật: web tự gọi Pancake mỗi sáng thay cho sheet.")}`;
}
/* ---------- Bảng lãi lỗ kênh dùng chung ---------- */
const plTbl=(L,dt)=>tbl(["Chỉ tiêu","Số tiền","% doanh thu","Ghi chú"],L.map(r=>{const big=/^[A-ZÀ-Ỹ =]/.test(r[0])&&r[0]===r[0].toUpperCase();return `<tr class="${big?"tot":""}"><td>${esc(r[0])}</td><td class="n">${typeof r[1]==="number"?nf(Math.round(r[1])):esc(r[1])}</td><td class="n">${typeof r[2]==="number"?(r[2]*100).toFixed(1)+"%":""}</td><td class="hint">${esc(r[3]||"")}</td></tr>`}));
const kvTbl=(L,h=["Chỉ số","Giá trị","Ghi chú"])=>tbl(h,L.map(r=>`<tr><td>${esc(r[0])}</td><td class="n">${typeof r[1]==="number"?(Math.abs(r[1])<10&&r[1]%1?(Math.abs(r[1])<1?(r[1]*100).toFixed(1)+"%":r[1].toFixed(2)):nf(Math.round(r[1]))):esc(r[1]??"")}</td><td class="hint">${esc(r.slice(2).filter(x=>typeof x==="string").join(" · "))}${r.slice(2).find(x=>typeof x==="number")!=null?" "+((r.slice(2).find(x=>typeof x==="number"))*100).toFixed(1)+"%":""}</td></tr>`));
let TT=KDX.tts||null,SP=KDX.spe||null;
const plv=(P,re)=>((P||[]).find(r=>re.test(r[0]))||[])[1]||0;

function pBcTikTok(m){
  if(!TT){m.innerHTML=needFile("TikTok Shop","Chưa có báo cáo.");return}
  const ms=monthStats(),dt=plv(TT.pl,/^Doanh thu thuần/),lai=plv(TT.pl,/^LÃI ĐÓNG GÓP/),ads=plv(TT.pl,/Quảng cáo/),gmv=(TT.lanes.find(r=>/^TỔNG/.test(r[0]))||[])[1];
  const tab=SUB.bc_tiktok||"tong",tabs=[["tong","Lãi lỗ & nguồn doanh thu"],["sp","Sản phẩm"],["ads","Quảng cáo"],["content","Video & live"]];
  m.innerHTML=H("Kênh TikTok Shop",TT.ky+" · báo cáo quản trị (chốt sổ ngày 8)")+`<div class="grid kpis">${kpi("GMV cả shop",tr(gmv),"doanh thu thuần "+tr(dt))}${kpi("Lãi đóng góp kênh",tr(lai),pc(lai,dt)+" doanh thu · mục tiêu 18,5%","var(--green)")}${kpi("Quảng cáo TikTok",tr(-ads),pc(-ads,dt)+" doanh thu · ROAS thực "+(dt&&ads?(dt/-ads).toFixed(2):"—"))}${kpi("Từ KOC",pc((TT.lanes[1]||[])[1],gmv),"của GMV · "+tr((TT.lanes[1]||[])[1]))}${kpi("Video team tháng 10",tr(ms.all),"số mẫu demo")}</div>
  <div class="tabs">${tabs.map(([k,t])=>`<button data-sub="${k}" class="${k===tab?"on":""}">${t}</button>`).join("")}</div>
  ${tab==="tong"?`<section class="card"><div class="card-h"><h2>Lãi lỗ kênh</h2></div>${plTbl(TT.pl)}</section>
   <section class="card"><div class="card-h"><h2>Doanh thu đến từ đâu — 5 nguồn</h2></div>${tbl(["Nguồn","GMV","% GMV","Lãi gộp ước tính","Chi phí riêng","Lãi ròng","Ghi chú"],TT.lanes.map(r=>`<tr class="${/^TỔNG/.test(r[0])?"tot":""}"><td><b>${esc(r[0])}</b></td><td class="n">${tr(r[1])}</td><td class="n">${(r[2]*100).toFixed(1)}%</td><td class="n">${tr(r[4])}</td><td class="n">${tr(r[5])}</td><td class="n">${tr(r[6])}</td><td class="hint">${esc(r[7]||"")}</td></tr>`))}</section>
   <section class="card"><div class="card-h"><h2>Chỉ số điều hành</h2></div>${kvTbl(TT.chiso)}</section>
   <section class="card"><div class="card-h"><h2>Nhận xét kỳ báo cáo</h2></div><ol class="lessons">${TT.nhanxet.map(x=>`<li>${esc(x)}</li>`).join("")}</ol></section>`:""}
  ${tab==="sp"?`<section class="card">${tbl(["Sản phẩm","Doanh thu","Giá vốn","Phí sàn","Lãi gộp","Ads","Lãi sau ads","ROAS","Đánh giá"],TT.sp.map(s=>`<tr><td>${esc(s.n)}</td><td class="n">${tr(s.dt)}</td><td class="n">${tr(s.gv)}</td><td class="n">${tr(s.phi)}</td><td class="n">${tr(s.lg)}</td><td class="n">${tr(s.ads)}</td><td class="n">${s.lai<0?`<span class="t-red">${tr(s.lai)}</span>`:tr(s.lai)}</td><td class="n">${s.roas?s.roas.toFixed(2):"—"}</td><td>${s.dg?pill(s.dg,/CẮT|lỗ/i.test(s.dg)?"red":/ĐẨY/.test(s.dg)?"grn":"gry"):""}</td></tr>`))}</section>`:""}
  ${tab==="ads"?`<section class="card"><div class="card-h"><h2>Toàn kênh</h2></div>${kvTbl(TT.ads)}</section><section class="card"><div class="card-h"><h2>Từng chiến dịch</h2></div>${tbl(["Chiến dịch","Chi + thuế","Đơn","GMV khai báo","ROI khai báo","Chi / đơn","Nhóm sản phẩm","Đánh giá"],TT.camp.map(c=>`<tr><td>${esc(c.n)}</td><td class="n">${tr(c.chi)}</td><td class="n">${nf(c.don||0)}</td><td class="n">${tr(c.gmv)}</td><td class="n">${c.roi?c.roi.toFixed(2):"—"}</td><td class="n">${c.cpa?nf(Math.round(c.cpa)):"—"}</td><td>${esc(c.nhom)}</td><td>${c.dg?pill(c.dg,/Đạt/.test(c.dg)?"grn":"amb"):""}</td></tr>`))}<div class="note">ROI trong Ads Manager là số TikTok tự khai, cao hơn thực tế. Số để quyết định là ROAS thực ở tab Lãi lỗ.</div></section>`:""}
  ${tab==="content"?`<section class="card"><div class="card-h"><h2>Video của shop (team Content)</h2></div>${kvTbl(TT.content)}</section><section class="card"><div class="card-h"><h2>Livestream người bán</h2></div><div class="grid kpis">${kpi("Số phiên",TT.live.phien)}${kpi("Số giờ",TT.live.gio)}${kpi("GMV live",tr(TT.live.gmv))}${kpi("GMV / giờ",TT.live.gio?tr(TT.live.gmv/TT.live.gio):"—")}</div></section><div class="acts"><button class="btn" data-go="hieuqua">Hiệu quả tháng của team Content →</button><button class="btn" data-go="win">Video win →</button></div>`:""}
  ${TT.no.length?`<section class="card"><div class="card-h"><h2>Dữ liệu còn thiếu</h2></div>${tbl(["Việc","Trạng thái","Ai xử lý"],TT.no.map(r=>`<tr><td>${esc(r[0])}</td><td>${pill(r[1],"amb")}</td><td>${esc(r[2])}</td></tr>`))}</section>`:""}
  ${srcNote("Google Sheet BÁO CÁO TIKTOKSHOP 2026 (M1–M6). Tháng 8, 9 chưa chốt sổ trong file này.")}`;
}
function pBcShopee(m){
  if(!SP){m.innerHTML=needFile("Shopee","Chưa có báo cáo.");return}
  const dt=plv(SP.pl,/^Doanh thu thuần/),lai=plv(SP.pl,/^LÃI ĐÓNG GÓP/),ads=plv(SP.pl,/Ads/),koc=(SP.shop.find(r=>/KOC/.test(r[0]))||[])[3];
  const tab=SUB.bc_shopee||"tong",tabs=[["tong","Lãi lỗ"],["shop","So sánh 2 shop"],["sp","Sản phẩm"],["phi","Phí sàn"]];
  m.innerHTML=H("Kênh Shopee (2 shop)",SP.ky+" · đang thuê ngoài vận hành")+`<div class="grid kpis">${kpi("Doanh thu thuần",tr(dt))}${kpi("Lãi đóng góp kênh",tr(lai),pc(lai,dt)+" doanh thu","var(--green)")}${kpi("Shopee Ads",tr(-ads),pc(-ads,dt)+" doanh thu · KPI dưới 20%")}${kpi("Phí sàn",tr(-plv(SP.pl,/^Phí sàn/)),pc(-plv(SP.pl,/^Phí sàn/),dt)+" doanh thu","var(--orange)")}${kpi("Doanh thu qua KOC",tr(koc),pc(koc,dt))}</div>
  <div class="tabs">${tabs.map(([k,t])=>`<button data-sub="${k}" class="${k===tab?"on":""}">${t}</button>`).join("")}</div>
  ${tab==="tong"?`<section class="card">${plTbl(SP.pl)}</section><section class="card"><div class="card-h"><h2>Chỉ số điều hành</h2></div>${kvTbl(SP.chiso)}</section><section class="card"><div class="card-h"><h2>Độ tin cậy số liệu</h2></div>${kvTbl(SP.tincay)}<div class="note">40% doanh thu Shopee đang thuộc SKU chưa chốt định mức giá vốn (combo, quà tặng). Kế toán xác nhận 95 SKU thì lãi lỗ từng sản phẩm mới dùng được để cắt hay đẩy.</div></section>`:""}
  ${tab==="shop"?`<section class="card">${tbl(SP.shop[0],SP.shop.slice(1).map(r=>`<tr class="${/^LÃI/.test(r[0])?"tot":""}"><td>${esc(r[0])}</td>${r.slice(1).map(v=>`<td class="n">${typeof v==="number"?nf(Math.round(v)):esc(v)}</td>`).join("")}</tr>`))}</section>`:""}
  ${tab==="sp"?`<section class="card">${tbl(["Sản phẩm","SL bán","Doanh thu","Giá vốn","Phí sàn","Lãi gộp sau phí sàn","Biên","Đánh giá"],SP.sp.map(s=>`<tr><td>${esc(s.n)}</td><td class="n">${nf(s.sl||0)}</td><td class="n">${tr(s.dt)}</td><td class="n">${tr(s.gv)}</td><td class="n">${tr(-s.phi)}</td><td class="n">${s.lg<0?`<span class="t-red">${tr(s.lg)}</span>`:tr(s.lg)}</td><td class="n">${s.bien!=null?(s.bien*100).toFixed(0)+"%":"—"}</td><td>${s.dg?pill(s.dg,/lỗ|Lỗ/.test(s.dg)?"red":/mỏng/.test(s.dg)?"amb":"grn"):""}</td></tr>`))}</section>`:""}
  ${tab==="phi"?`<section class="card"><div class="card-h"><h2>Cơ cấu phí sàn Shopee</h2></div>${plTbl(SP.phi)}</section>`:""}
  ${srcNote("Google Sheet AILLA_BaoCao_QuanTri_Shopee_2Shop_202607 (DASHBOARD, SO_SANH_SHOP, SANPHAM). Chốt sổ ngày 8 hằng tháng.")}`;
}
function pBcKoc(m){
  if(!TT){m.innerHTML=needFile("KOC","Chưa có báo cáo.");return}
  const koc=(SP&&(SP.shop.find(r=>/KOC/.test(r[0]))||[])[3])||0,bk=TT.booking;
  m.innerHTML=H("KOC / Affiliate",TT.ky+" · Marketing › Team KOC · doanh thu KOC đã nằm trong số TikTok Shop, Shopee")+`<div class="grid kpis">${kpi("GMV TikTok nhờ KOC",tr(plv(TT.kocPL,/^GMV/)),pc(plv(TT.kocPL,/^Doanh thu quy đổi/),plv(TT.pl,/^Doanh thu thuần/))+" doanh thu kênh")}${kpi("Lãi sau đầu tư KOC",tr(plv(TT.kocPL,/^LÃI SAU/)),"đầu tư mẫu + ship "+tr(-plv(TT.kocPL,/mẫu gửi/)-plv(TT.kocPL,/ship/)),"var(--green)")}${kpi("KOC có doanh số",nf(plv(TT.kocHD,/có doanh số/)),"trên "+nf(plv(TT.kocHD,/trong hoạt động/))+" KOC đang gắn sản phẩm")}${kpi("Shopee qua KOC",tr(koc))}</div>
  <section class="card"><div class="card-h"><h2>Lãi lỗ từ KOC — TikTok</h2></div>${kvTbl(TT.kocPL,["Chỉ tiêu","Số tiền","Ghi chú"])}</section>
  <section class="card"><div class="card-h"><h2>Hoạt động của KOC</h2></div>${kvTbl(TT.kocHD)}</section>
  <section class="card"><div class="card-h"><h2>Phễu team booking</h2><span class="hint">dữ liệu booking tháng 8</span></div>${kvTbl(bk,["Bước","Số KOC","Tỷ lệ / ghi chú"])}
   <h3>Theo người booking</h3>${tbl(["Người booking","Đã book","Đã gửi mẫu","Đã nhận","Nghiệm thu video","Đầu tư"],TT.bookNV.map(b=>`<tr><td><b>${esc(b.n)}</b></td><td class="n">${b.book}</td><td class="n">${b.gui}</td><td class="n">${b.nhan}</td><td class="n">${b.nt}</td><td class="n">${nf(b.dt||0)}</td></tr>`))}
   <div class="note">Chưa KOC nào được nghiệm thu (chưa dán ID video), nên chưa biết booking nào ra đơn. Bản thật: mỗi KOC là một thẻ có hạn lên video 7 ngày sau khi nhận hàng, quá hạn tự báo đỏ cho người booking.</div></section>
  ${srcNote("BÁO CÁO TIKTOKSHOP 2026 (M3_KOC, 15_BOOKING_KOC) + Shopee SO_SANH_SHOP.")}`;
}
function pBcB2B(m){m.innerHTML=H("B2B / Đại lý","Số liệu từ CRM B2B")+`<section class="card"><p>Doanh thu B2B lấy từ đơn đã kế toán xác nhận trong CRM. Bản demo chưa kéo số được (CRM chạy riêng). Khi gộp bản thật, bảng tổng quan kinh doanh tự có dòng B2B.</p><div class="crmlinks">${CRM_PAGES.map(([k,t,p])=>`<a class="btn" href="${CRM_URL+p}" target="_blank" rel="noopener">${t} ↗</a>`).join("")}</div></section>`}

/* ---------- Digital: Ads Facebook ---------- */
/* Mục tiêu doanh số từng bạn chạy Ads theo tháng: chị/lead giao ở đây, mặc định lấy KPI trong báo cáo Digital. */
const ADS_TG_M="2026-09";
const adsTarget=n=>{const t=((D().adsTargets||{})[ADS_TG_M]||{})[n];return t!=null?t:((KDX.adsPeople||[]).find(p=>p.n===n)||{}).kpi||0};
function pAdsHieuQua(m){
  const P=KDX.adsPeople.map(p=>({...p,kpi:adsTarget(p.n)})),ed=can(ME,"kehoach.duyet")||can(ME,"viec.giao"),T={kpi:sum(P,p=>p.kpi),chi:sum(P,p=>p.chi),dt:sum(P,p=>p.dt),don:sum(P,p=>p.don)},CD=KDX.adsChiDay.filter(r=>r[4]);
  m.innerHTML=H("Hiệu quả Ads Facebook","Tháng 9 · 3 bạn chạy Ads: Việt Anh, Thảo, Duẩn")+`<div class="grid kpis">${kpi("Chi Ads",tr(T.chi),CD.length+" ngày có chi")}${kpi("Doanh số mang về",tr(T.dt),"mục tiêu "+tr(T.kpi)+" · đạt "+pc(T.dt,T.kpi))}${kpi("ROAS",T.chi?(T.dt/T.chi).toFixed(2):"—","trên doanh số chốt")}${kpi("Đơn chốt",nf(T.don),"chi / đơn "+(T.don?nf(Math.round(T.chi/T.don))+"đ":"—"))}${kpi("Chi Ads / doanh số",pc(T.chi,T.dt),"mục tiêu ≤ 35%",T.dt&&T.chi/T.dt>.35?"var(--orange)":"var(--green)")}</div>
  <section class="card"><div class="card-h"><h2>Bảng xếp hạng nhân sự</h2><span class="hint">xếp theo % đạt KPI</span></div>${tbl(["Nhân sự","Mục tiêu doanh số","Doanh số mang về","% đạt mục tiêu","Chi Ads","Chi / doanh số","Đơn chốt","Chi / đơn","ROAS"],P.slice().sort((a,b)=>(b.kpi?b.dt/b.kpi:0)-(a.kpi?a.dt/a.kpi:0)).map((p,i)=>`<tr><td><b>${i+1}. ${esc(p.n)}</b></td><td class="n">${ed?`<input class="num" data-atg="${esc(p.n)}" value="${Math.round(p.kpi/1e6)}" title="triệu đồng" style="width:80px"> tr`:tr(p.kpi)}</td><td class="n">${tr(p.dt)}</td><td class="n">${pill(pc(p.dt,p.kpi),p.dt>=p.kpi?"grn":"amb")}</td><td class="n">${tr(p.chi)}</td><td class="n">${pc(p.chi,p.dt)}</td><td class="n">${nf(p.don)}</td><td class="n">${p.don?nf(Math.round(p.chi/p.don)):"—"}</td><td class="n">${p.chi?(p.dt/p.chi).toFixed(2):"—"}</td></tr>`))}</section>
  <section class="card"><div class="card-h"><h2>Chi Ads theo ngày · tháng 9</h2></div><div class="dleg">${P.map(p=>{const A=(DAYD.ads||{})[p.n]||{},v=Array.from({length:30},(_,j)=>+((A["2026-09-"+String(j+1).padStart(2,"0")]||[])[0])||0);return `<div><b>${esc(p.n)}</b> <span class="hint">${tr(v.reduce((a,b)=>a+b,0))}</span>${barRow(v,j=>"ngày "+(j+1),money)}</div>`}).join("")}</div></section>
  <section class="card"><div class="card-h"><h2>Theo tháng</h2><span class="hint">T7, T8 từ tab "1. Báo cáo Tổng quan" · T9 cộng 3 tab Ads từng người</span></div>${tbl(["Tháng","Việt Anh","Thảo","Duẩn","Tổng","Chi / đơn","ROAS"],KDX.adsMonths.concat([{m:"2026-09",va:(P[0]||{}).dt,thao:(P[1]||{}).dt,duan:(P[2]||{}).dt,tong:T.dt,cpo:T.don?T.chi/T.don:0,roas:T.chi?T.dt/T.chi:0}]).map(r=>`<tr><td><b>${r.m.slice(5)}/${r.m.slice(0,4)}</b></td><td class="n">${tr(r.va)}</td><td class="n">${tr(r.thao)}</td><td class="n">${tr(r.duan)}</td><td class="n"><b>${tr(r.tong)}</b></td><td class="n">${nf(Math.round(r.cpo))}</td><td class="n">${(+r.roas).toFixed(2)}</td></tr>`))}
</section>
  ${D().adsRows.length?`<section class="card"><div class="card-h"><h2>Báo cáo Ads đã nhập trên web (tháng ${MONTH.mon})</h2></div>${adsSummary()}</section>`:""}
  ${srcNote("Google Sheet BÁO CÁO DIGITAL MKT 2026 FINAL (tab Ads từng người, EXPORT_CP_ADS, 1. Báo cáo Tổng quan).")}`;
  m.querySelectorAll("[data-atg]").forEach(i=>i.onchange=()=>{const n=i.dataset.atg,v=Math.round((+String(i.value).replace(",",".")||0)*1e6);DB.mutate(ME.name,`giao mục tiêu Ads tháng ${ADS_TG_M.slice(5)} cho ${n}: ${tr(v)}`,d=>{d.adsTargets=d.adsTargets||{};(d.adsTargets[ADS_TG_M]=d.adsTargets[ADS_TG_M]||{})[n]=v});toast("Đã giao mục tiêu");renderMain()});
}
function pAdsSP(m){
  const P=KDX.adsProd,tot=sum(P,p=>p.chi),chiAll=sum(KDX.adsPeople,p=>p.chi),d=D();if(!d.adsTran)d.adsTran=JSON.parse(JSON.stringify(KDX.adsTran));
  const ed=can(ME,"baocao.ads");
  m.innerHTML=H("Ads theo sản phẩm & trần KPI","Tháng 9")+`<div class="note">Đã gán sản phẩm ${tr(tot)} trên tổng chi ${tr(chiAll)} (${pc(tot,chiAll)}). Phần còn lại chưa khai báo mã sản phẩm, nên không biết sản phẩm nào đang lãi.</div>
  <section class="card">${tbl(["Sản phẩm","Người chạy","Chi Ads","Data","Đơn","Doanh số","Chi / đơn","ROAS"],P.slice().sort((a,b)=>b.dt-a.dt).map(p=>`<tr><td><b>${esc(cleanN(p.ten))}</b></td><td>${esc(p.nv)}</td><td class="n">${tr(p.chi)}</td><td class="n">${nf(p.data)}</td><td class="n">${nf(p.don)}</td><td class="n">${tr(p.dt)}</td><td class="n">${p.don?nf(Math.round(p.chi/p.don)):"—"}</td><td class="n">${p.chi?pill((p.dt/p.chi).toFixed(2),p.dt/p.chi>=2.5?"grn":"amb"):"—"}</td></tr>`))}</section>
  <section class="card"><div class="card-h"><h2>Trần chi phí & ROAS kỳ vọng</h2><span class="hint">vượt trần là báo đỏ</span></div><div class="tbl edit"><table><thead><tr><th>Mã</th><th>Sản phẩm</th><th>Phễu</th><th class="n">Trần giá data / tin nhắn</th><th class="n">Trần chi / đơn</th><th class="n">ROAS tối thiểu</th></tr></thead><tbody>${d.adsTran.map((t,i)=>`<tr><td class="mono">${t.ma}</td><td>${esc(t.ten)}</td><td>${esc(t.pheu)}</td>${["lead","cpo","roas"].map(f=>`<td class="n">${ed?`<input class="num" data-at="${i}" data-f="${f}" value="${t[f]}">`:nf(t[f])}</td>`).join("")}</tr>`).join("")}</tbody></table></div></section>`;
  m.querySelectorAll("[data-at]").forEach(x=>x.onchange=()=>{DB.mutate(ME.name,"sửa trần KPI Ads",dt=>{if(!dt.adsTran)dt.adsTran=JSON.parse(JSON.stringify(KDX.adsTran));dt.adsTran[+x.dataset.at][x.dataset.f]=+x.value||0});toast("Đã lưu")});
}
/* ---------- Sale B2C Facebook (khu làm việc) ---------- */
function pFbDon(m){const f9=KDX.fbHist[1]||{};m.innerHTML=H("Đơn hàng Facebook","Khu làm việc Sale B2C / CSKH")+`<div class="grid kpis">${kpi("Đơn tạo T9",nf(f9["Tổng đơn tạo"]||0))}${kpi("Chưa xử lý",nf(f9["Đơn chưa xử lý"]||0),"cần gọi chốt","var(--orange)")}${kpi("Đơn hủy",nf(f9["Đơn hủy"]||0),(f9["Tỷ lệ hủy %"]||0)+"%")}${kpi("Đơn hoàn",nf(f9["Đơn hoàn"]||0),(f9["Tỷ lệ hoàn %"]||0)+"%")}</div><section class="card"><div class="card-h"><h2>Phễu đơn</h2></div>${fbFunnel()}</section><section class="card"><p>Bản thật: mỗi sáng web tự lấy đơn từ Pancake. Sale thấy danh sách đơn chưa xử lý, đơn hủy cần gọi lại, đơn hoàn cần hỏi lý do. Tên và số điện thoại khách chỉ người được phân quyền mới xem.</p></section>`}
function pFbSale(m){const Dd=KDX.fbDash||{},f9=KDX.fbHist[1]||{},g=i=>pSum("fb",i).v,tao=g(0),chot=g(1),huy=g(2),hoan=g(3),giao=g(4),dt=g(6);
  const top=tao?`<section class="card pblk"><div class="card-h"><h2>Bán hàng trong kỳ đã chọn</h2><span class="pill p-blu">${esc(pLabel())}</span></div><div class="grid kpis">${kpi("Doanh thu chốt",tr(dt),covTxt("fb"))}${kpi("Đơn chốt",nf(chot),"trên "+nf(tao)+" đơn tạo · chốt "+pc(chot,tao))}${kpi("Giá trị TB đơn",chot?nf(Math.round(dt/chot))+"đ":"—")}${kpi("Tỷ lệ hủy",pc(huy,tao),nf(huy)+" đơn")}${kpi("Tỷ lệ hoàn",pc(hoan,giao+hoan),nf(hoan)+" đơn")}</div></section>`:"";
  m.innerHTML=H("Hoạt động Sale B2C","Facebook · người xử lý đơn trên Pancake (Sale + CSKH)")+top+`<section class="card"><div class="card-h"><h2>Xếp hạng & cảnh báo người xử lý đơn</h2><span class="hint">kỳ ${esc(Dd.ky||"")}</span></div>${fbSaleTbl()}</section><section class="card"><div class="card-h"><h2>Phễu đơn theo tháng</h2><span class="hint">báo cáo Pancake</span></div>${fbFunnel()}</section><div class="note">Huyền Phạm, Mai Hương là bạn Sale + CSKH trong danh sách nhân sự (phòng CSKH). "Việt Nam", "Thảo Đĩnh", "Dũng Hoàng" là tên tài khoản trên Pancake, cần gắn với mã nhân sự ở Thiết lập để tính KPI đúng người. Bản thật: mỗi sáng web lấy đơn từ Pancake, Sale thấy ngay đơn chưa xử lý, đơn hủy cần gọi lại, đơn hoàn cần hỏi lý do.</div>`}
function pFbCSKH(m){m.innerHTML=H("Chăm sóc khách hàng","Facebook · triển khai từ tháng sau")+`<section class="card waitf"><h2>Sắp triển khai</h2><p>Khu này dành cho CSKH khi bắt đầu chạy: danh sách khách mua lại, khách sắp hết hàng theo chu kỳ dùng, đơn hoàn cần hỏi lý do, phản hồi và khiếu nại, tỷ lệ khách mua lại. Số đã có sẵn từ Pancake: khách mua lại tháng 9 là <b>${(f9=>f9["Khách mua lại %"]??"—")(KDX.fbHist[1]||{})}%</b> trên ${nf((KDX.fbHist[1]||{})["Số khách"]||0)} khách.</p></section>`}
/* ---------- Kế toán ---------- */
function pDoiSoat(m){const Dd=KDX.fbDash;m.innerHTML=H("Đối soát tiền về","Kênh Facebook · kỳ "+esc(Dd.ky||""))+`<div class="grid kpis">${kpi("Doanh thu giao thành công",tr(Dd.dt))}${kpi("Tiền đã về",tr(Dd.tienVe)||"0",pc(Dd.tienVe,Dd.dt))}${kpi("Đang treo ở hãng vận chuyển",tr(Dd.treo),pc(Dd.treo,Dd.dt),"var(--red)")}</div><div class="note">Theo sheet Pancake, 100% tiền đơn giao thành công chưa ghi nhận đã về. Có thể do chưa cài mã trạng thái "đã đối soát" (16, 20) đúng với Pancake. Kế toán cần kiểm trước khi tin số này.</div>${needFile("File đối soát vận chuyển","Cần file đối soát từ hãng vận chuyển (GHTK, Viettel Post, J&T…) hoặc file xuất MISA để khớp tiền về theo đơn.")}`}

const _pb=(fn,kind)=>m=>{fn(m);const ph=m.querySelector('.ph');if(ph)ph.insertAdjacentHTML('afterend',periodBlock(kind))};
Object.assign(PAGES,{fb_cskh:pFbCSKH,bc_tong:pBcTong,bc_fb:pBcFb,bc_tiktok:pBcTikTok,bc_shopee:pBcShopee,bc_koc:pBcKoc,bc_b2b:pBcB2B,adshieuqua:pAdsHieuQua,adssp:pAdsSP,fb_don:pFbDon,fb_sale:pFbSale,doisoat:pDoiSoat});
