/* =====================================================================
   NHÂN SỰ — trang "Nhân viên" (danh sách + hồ sơ từng người, kiểu phần mềm nhân sự)
   Dữ liệu hồ sơ (CCCD, MST, ngân hàng, lương, người phụ thuộc, khen thưởng – kỷ luật, lịch sử)
   nằm trong d.hr.ns[mã] — máy chủ cất ở ngăn riêng, chỉ CEO / kế toán / HCNS nhận về (SV.hrOk).
   File đính kèm (ảnh, CCCD, HĐ, quyết định) lưu ở /api/hub/hr/files.
   ===================================================================== */
const hrOk=()=>!!(typeof SV!=="undefined"&&SV.hrOk);
const HSK=[["gioi","Giới tính"],["ngaySinh","Ngày sinh","date"],["cccd","Số CCCD"],["ngayCap","Ngày cấp","date"],["noiCap","Nơi cấp"],["mst","Mã số thuế"],["sdt","Số điện thoại"],["email","Email"],["diaChi","Địa chỉ"],["stk","Số tài khoản"],["nh","Ngân hàng"]];
const LDK=[["luong","Lương cơ bản","n"],["nenBH","Mức đóng BHXH","n"],["pcCV","Phụ cấp chức vụ","n"],["pcKhac","Phụ cấp khác","n"],["bac","Bậc lương"],["nghe","Nhóm nghề"],["hinhThuc","Hình thức trả lương"],["noiLam","Nơi làm việc"]];
const FKIND=[["anh","Ảnh thẻ"],["cccd","CCCD"],["hd","Hợp đồng / phụ lục"],["qd","Quyết định"],["khac","Giấy tờ khác"]];
let NVF={q:"",pb:"",tt:"dang",sel:"",tab:"chung",edit:""},NVFILES={ma:"",L:[],busy:false};
const nvNs=ma=>HRD().ns[ma]||{};
const hsOf=ma=>nvNs(ma).hs||{};
const nptOf=ma=>(nvNs(ma).npts||[]);
const ttTone=t=>t==="Đã nghỉ"?"red":t==="Thử việc"?"amb":t==="Tạm nghỉ"?"gry":"grn";
function nvLog(dt,ma,msg){const n=dt.hr.ns[ma]=dt.hr.ns[ma]||{};n.ls=n.ls||[];n.ls.unshift({t:new Date().toLocaleString("vi-VN"),who:ME.name,msg});n.ls=n.ls.slice(0,200)}
function nvAlerts(){
  const S=D().staff.filter(x=>x.tt!=="Đã nghỉ"),A={hd:[],cccd:[],mst:[],nh:[],npt:[]};
  S.forEach(x=>{const n=nvNs(x.ma),h=n.hs||{},c=n.hd?daysTo(n.hd.het):null;if(c!=null&&c<=30)A.hd.push([x,c]);if(!h.cccd)A.cccd.push(x);if(!h.mst)A.mst.push(x);if(!h.stk)A.nh.push(x);if((n.npts||[]).some(p=>p.tt!=="Thôi"&&!p.mst))A.npt.push(x)});
  return A;
}
/* Nhắc HĐ sắp hết hạn lên chuông: mỗi hợp đồng nhắc một lần, gửi CEO + người làm nhân sự. */
function nvNhacHD(){
  if(!hrOk()||!HRD()||!ME)return;const due=nvAlerts().hd.filter(([x])=>{const k=x.ma+"|"+nvNs(x.ma).hd.het;return !(HRD().nhac||{})[k]});if(!due.length)return;
  const to=D().users.filter(u=>u.active&&(u.role==="admin"||u.phongBan==="HCNS"||can(u,"nhansu.quanly"))).map(u=>u.id);
  DB.mutate("Hệ thống","nhắc hợp đồng sắp hết hạn",dt=>{dt.hr.nhac=dt.hr.nhac||{};due.forEach(([x,c])=>{const k=x.ma+"|"+dt.hr.ns[x.ma].hd.het;if(dt.hr.nhac[k])return;dt.hr.nhac[k]=hrNow().iso;if(typeof notifyU==="function")notifyU(dt,to,c<0?`Hợp đồng của ${x.ten} đã hết hạn ${-c} ngày`:`Hợp đồng của ${x.ten} còn ${c} ngày là hết hạn`,"page:hr_nv")})});
}
async function nvLoadFiles(ma,force){
  if(!force&&NVFILES.ma===ma)return;NVFILES={ma,L:[],busy:true};
  try{NVFILES.L=await svApi("/api/hub/hr/files?ma="+encodeURIComponent(ma))||[]}catch(e){NVFILES.L=[]}
  NVFILES.busy=false;if(PAGE==="hr_nv"&&NVF.sel===ma)renderMain();
}
function nvList(){const d=D();return d.staff.filter(x=>(NVF.tt==="all"||(NVF.tt==="dang"?x.tt!=="Đã nghỉ":x.tt===NVF.tt))&&(!NVF.pb||x.pb===NVF.pb)&&(!NVF.q||foldName(x.ma+" "+x.ten+" "+(x.viTri||"")+" "+(hsOf(x.ma).cccd||"")+" "+(hsOf(x.ma).mst||"")+" "+(hsOf(x.ma).sdt||"")).includes(foldName(NVF.q))))}
function pHrNV(m){
  if(!hrOk()){m.innerHTML=H("Nhân viên")+`<section class="card"><p>Trang này chỉ CEO, kế toán và phòng Hành chính nhân sự xem được.</p></section>`;return}
  const d=D(),h=HRD(),S=d.staff,dang=S.filter(x=>x.tt!=="Đã nghỉ"),A=nvAlerts(),L=nvList(),ed=can(ME,"nhansu.quanly")||ME.role==="admin"||ME.phongBan==="HCNS";
  if(!NVF.sel||!S.some(x=>x.ma===NVF.sel))NVF.sel=(L[0]||{}).ma||"";
  const quy=dang.reduce((a,x)=>a+(nvNs(x.ma).luong||0),0);
  const warn=[["red",A.hd.length,"hợp đồng hết hạn trong 30 ngày"],["red",A.cccd.length,"hồ sơ thiếu CCCD"],["amb",A.npt.length,"người phụ thuộc chưa có MST"],["amb",A.mst.length,"nhân viên chưa có MST"],["amb",A.nh.length,"nhân viên chưa có tài khoản ngân hàng"]];
  m.innerHTML=H("Nhân viên",`${dang.length} người đang làm · bấm vào một người để xem hồ sơ`)+`
  <div class="nv-top">
   <section class="card nv-t"><div class="nv-ic c-blu">${ico("users")}</div><div class="l">Nhân viên</div><div class="v">${dang.length}</div><div class="nv-sub"><span><b class="g">${dang.filter(x=>x.tt==="Chính thức"||x.tt==="Theo giờ").length}</b> chính thức</span><span><b class="b">${dang.filter(x=>x.tt==="Thử việc").length}</b> thử việc</span><span><b class="o">${S.filter(x=>x.tt==="Đã nghỉ").length}</b> đã nghỉ</span></div></section>
   <section class="card nv-t"><div class="nv-ic c-grn">${ico("money")}</div><div class="l">Tổng lương cơ bản / tháng</div><div class="v">${money(quy)}</div><div class="nv-sub"><span><b>${dang.filter(x=>nvNs(x.ma).luong).length}</b> người có lương</span><span><b class="o">${dang.filter(x=>!nvNs(x.ma).luong).length}</b> chưa nhập lương</span></div></section>
   <section class="card nv-t"><div class="nv-ic c-amb">${ico("task")}</div><div class="l">Hợp đồng sắp hết hạn</div><div class="v" style="color:var(--orange)">${A.hd.length}</div><div class="nv-sub">${A.hd.slice(0,3).map(([x,c])=>`<span>${esc(x.ten)}: ${c<0?"quá "+(-c):"còn "+c} ngày</span>`).join("")||"<span>Không có hợp đồng nào sắp hết</span>"}</div></section>
   <section class="card nv-w"><div class="nv-wh"><div class="nv-ic c-red sm">${ico("alert")}</div><div class="l">Cảnh báo</div></div>${warn.filter(w=>w[1]).map(w=>`<div class="nv-wr"><i class="dot d-${w[0]}"></i><b>${w[1]}</b> ${w[2]}</div>`).join("")||`<div class="nv-wr">Hồ sơ đủ cả, không có gì cần bổ sung.</div>`}</section>
  </div>
  <section class="card flush"><div class="card-h pad"><h2>Danh sách nhân viên</h2><span class="sp"></span>
   ${ed?`<button class="btn sm pri" id="nv-add">+ Thêm</button>`:""}<button class="btn sm" data-go="hr_nap">Nhập Excel</button><button class="btn sm" id="nv-xl">Xuất Excel</button><button class="btn sm" id="nv-in">In danh sách</button></div>
   <div class="filters pad"><input id="nv-q" placeholder="Tìm mã, tên, CCCD, MST, số điện thoại…" value="${esc(NVF.q)}" style="max-width:300px"><select id="nv-pb">${opt([["","Mọi phòng ban"]].concat(d.departments.map(p=>[p.k,p.n])),NVF.pb)}</select><select id="nv-tt">${opt([["dang","Đang làm"],["Chính thức","Chính thức"],["Thử việc","Thử việc"],["Theo giờ","Theo giờ"],["Tạm nghỉ","Tạm nghỉ"],["Đã nghỉ","Đã nghỉ"],["all","Tất cả"]],NVF.tt)}</select><span class="hint">${L.length} người</span></div>
   <div class="tbl nv-list"><table><thead><tr><th>STT</th><th>Mã NV</th><th>Họ và tên</th><th>Giới tính</th><th>Ngày sinh</th><th>Phòng ban</th><th>Vị trí</th><th>Ngày vào làm</th><th>Loại HĐ</th><th class="n">Lương cơ bản</th><th>Trạng thái</th></tr></thead><tbody>
   ${L.map((x,i)=>{const n=nvNs(x.ma),hs=n.hs||{};return `<tr data-nv="${x.ma}" class="${x.ma===NVF.sel?"on":""}"><td>${i+1}</td><td class="mono">${x.ma}</td><td><b>${esc(x.ten)}</b></td><td>${esc(hs.gioi||n.gioi||"")}</td><td>${vndate(hs.ngaySinh)}</td><td>${esc(pbName(x.pb))}</td><td>${esc(x.viTri||"")}</td><td>${vndate(x.ngayVao)}</td><td>${esc((n.hd||{}).loai||"")}</td><td class="n">${n.luong?nf(n.luong):"—"}</td><td><i class="dot d-${ttTone(x.tt)}"></i> ${esc(x.tt||"")}</td></tr>`}).join("")||`<tr><td colspan="11" class="empty">Không có ai khớp bộ lọc.</td></tr>`}
   </tbody></table></div></section>
  ${NVF.sel?nvHoSo(NVF.sel,ed):""}`;
  $("#nv-q").onchange=e=>{NVF.q=e.target.value;renderMain()};$("#nv-pb").onchange=e=>{NVF.pb=e.target.value;renderMain()};$("#nv-tt").onchange=e=>{NVF.tt=e.target.value;renderMain()};
  m.querySelectorAll("[data-nv]").forEach(r=>r.onclick=()=>{NVF.sel=r.dataset.nv;NVF.edit="";renderMain();setTimeout(()=>{const p=$("#nv-hs");if(p)p.scrollIntoView({behavior:"smooth",block:"start"})},30)});
  $("#nv-xl").onclick=()=>nvExcel(L);$("#nv-in").onclick=()=>nvPrintList(L);
  if($("#nv-add"))$("#nv-add").onclick=nvAddForm;
  if(NVF.sel)nvBind(NVF.sel,ed);
}
function nvHoSo(ma,ed){
  const x=staffBy(ma),n=nvNs(ma),hs=n.hs||{},hd=n.hd||{},anh=NVFILES.ma===ma&&NVFILES.L.find(f=>f.kind==="anh");if(NVFILES.ma!==ma)nvLoadFiles(ma);
  const tabs=[["chung","Thông tin chung"],["npt","Người phụ thuộc"],["vb","Hợp đồng – quyết định"],["kt","Khen thưởng – kỷ luật"],["file","File đính kèm"],["ls","Lịch sử thay đổi"]];
  const fld=(k,l,t,v,e)=>`<label class="nv-f"><span>${l}</span>${e?`<input data-hsf="${k}" ${t==="date"?'type="date"':t==="n"?'inputmode="numeric"':""} value="${esc(t==="n"&&v?nf(v):v??"")}">`:`<b>${esc(t==="date"?vndate(v):t==="n"?nf(v):v||"—")}</b>`}</label>`;
  const SUA=k=>ed?(NVF.edit===k?`<button class="btn sm pri" data-nved="">Xong</button>`:`<button class="btn sm" data-nved="${k}">✎ Sửa</button>`):"";
  let body="";
  if(NVF.tab==="chung")body=`<div class="nv-3">
   <div class="nv-ph">${anh?`<img src="/api/hub/hr/files/${anh.id}" alt="Ảnh ${esc(x.ten)}">`:`<div class="nv-noph">${esc((x.ten||"?").replace(/(.*?)/g,"").trim().split(" ").pop().slice(0,1))}</div>`}${ed?`<label class="btn sm">Thay ảnh<input type="file" accept="image/*" data-up="anh" hidden></label>`:""}</div>
   ${(ed=>`<div class="nv-box"><div class="nv-bh"><h3>Thông tin cá nhân</h3>${SUA("cn")}</div><label class="nv-f"><span>Mã nhân viên</span><b class="mono">${x.ma}</b></label>${ed?`<label class="nv-f"><span>Họ và tên</span><input data-stf="ten" value="${esc(x.ten)}"></label>`:`<label class="nv-f"><span>Họ và tên</span><b>${esc(x.ten)}</b></label>`}${HSK.map(([k,l,t])=>k==="gioi"&&ed?`<label class="nv-f"><span>${l}</span><select data-hsf="gioi">${opt(["","Nam","Nữ"],hs.gioi||n.gioi||"")}</select></label>`:fld(k,l,t,k==="gioi"?hs.gioi||n.gioi:hs[k],ed)).join("")}</div>`)(ed&&NVF.edit==="cn")}
   ${(ed=>`<div class="nv-box"><div class="nv-bh"><h3>Thông tin lao động</h3>${SUA("ld")}</div>${ed?`<label class="nv-f"><span>Phòng ban</span><select data-stf="pb">${opt([["","—"]].concat(D().departments.map(p=>[p.k,p.n])),x.pb)}</select></label><label class="nv-f"><span>Vị trí</span><input data-stf="viTri" value="${esc(x.viTri||"")}"></label><label class="nv-f"><span>Ngày vào làm</span><input type="date" data-stf="ngayVao" value="${esc(x.ngayVao||"")}"></label><label class="nv-f"><span>Trạng thái</span><select data-stf="tt">${opt(["Thử việc","Chính thức","Theo giờ","Tạm nghỉ","Đã nghỉ"],x.tt)}</select></label>`:`<label class="nv-f"><span>Phòng ban</span><b>${esc(pbName(x.pb))}</b></label><label class="nv-f"><span>Vị trí</span><b>${esc(x.viTri||"—")}</b></label><label class="nv-f"><span>Ngày vào làm</span><b>${vndate(x.ngayVao)}</b></label><label class="nv-f"><span>Trạng thái</span><b>${esc(x.tt)}</b></label>`}
    ${[["loai","Loại hợp đồng"],["so","Số hợp đồng"],["ky","Ngày ký","date"],["het","Ngày hết hạn","date"],["hetTV","Hết thử việc","date"]].map(([k,l,t])=>ed?`<label class="nv-f"><span>${l}</span>${k==="loai"?`<select data-hdf="loai">${opt(["","Thử việc","HĐLĐ xác định thời hạn","HĐLĐ không xác định thời hạn","Cộng tác viên","Thời vụ / theo giờ"],hd.loai||"")}</select>`:`<input data-hdf="${k}" ${t?'type="date"':""} value="${esc(hd[k]||"")}">`}</label>`:`<label class="nv-f"><span>${l}</span><b>${esc(t?vndate(hd[k]):hd[k]||"—")}</b></label>`).join("")}
    ${LDK.map(([k,l,t])=>fld(k,l,t,n[k],ed)).join("")}</div>`)(ed&&NVF.edit==="ld")}
   <div class="nv-box"><div class="nv-bh"><h3>Hồ sơ đính kèm</h3>${ed?`<button class="btn sm" data-nvt="file">+ Thêm file</button>`:""}</div>${NVFILES.busy?`<p class="hint">Đang tải…</p>`:NVFILES.L.filter(f=>f.kind!=="anh").map(f=>`<a class="nv-file" href="/api/hub/hr/files/${f.id}" target="_blank" rel="noopener"><i>${/pdf/.test(f.mime)?"PDF":"ẢNH"}</i><span>${esc(f.name)}</span><small>${vndate(f.created_at)}</small></a>`).join("")||`<p class="hint">Chưa có file. Bấm "+ Thêm file" để tải CCCD, hợp đồng, quyết định…</p>`}</div></div>
  <div class="nv-2"><div class="nv-box"><div class="nv-bh"><h3>Người phụ thuộc</h3>${ed?`<button class="btn sm" data-nvt="npt">+ Thêm</button>`:""}</div>${tbl(["STT","Họ và tên","Quan hệ","Ngày sinh","MST","Trạng thái"],nptOf(ma).map((p,i)=>`<tr><td>${i+1}</td><td>${esc(p.ten)}</td><td>${esc(p.qh)}</td><td>${vndate(p.ngaySinh)}</td><td class="mono">${esc(p.mst||"")}</td><td>${p.tt==="Thôi"?pill("Thôi","gry"):p.mst?pill("Đủ hồ sơ","grn"):pill("Thiếu MST","amb")}</td></tr>`))}</div>
   <div class="nv-box"><div class="nv-bh"><h3>Hợp đồng – quyết định</h3>${ed?`<button class="btn sm" data-nvt="vb">+ Thêm</button>`:""}</div>${tbl(["STT","Loại văn bản","Số văn bản","Ngày ban hành","Ngày hiệu lực"],(n.vb||[]).map((v,i)=>`<tr><td>${i+1}</td><td>${esc(v.loai)}</td><td class="mono">${esc(v.so)}</td><td>${vndate(v.ngay)}</td><td>${vndate(v.hieuLuc)}</td></tr>`))}</div></div>`;
  if(NVF.tab==="npt"){const P=nptOf(ma);body=`${tbl(["STT","Họ và tên","Quan hệ","Ngày sinh","MST","Từ tháng","Trạng thái",""],P.map((p,i)=>`<tr><td>${i+1}</td><td><b>${esc(p.ten)}</b></td><td>${esc(p.qh)}</td><td>${vndate(p.ngaySinh)}</td><td class="mono">${esc(p.mst||"")}</td><td>${esc(p.tu||"")}</td><td>${p.tt==="Thôi"?pill("Thôi giảm trừ","gry"):p.mst?pill("Đủ hồ sơ","grn"):pill("Thiếu MST","amb")}</td><td>${ed?`<button class="btn sm" data-nptx="${i}">${p.tt==="Thôi"?"Giảm trừ lại":"Thôi giảm trừ"}</button>`:""}</td></tr>`))}
   ${ed?`<form class="frm row7" id="nptf"><label class="field">Họ và tên<input id="np-t" required></label><label class="field">Quan hệ<select id="np-q">${opt(["Con","Vợ","Chồng","Bố","Mẹ","Khác"],"Con")}</select></label><label class="field">Ngày sinh<input id="np-s" type="date"></label><label class="field">MST<input id="np-m"></label><label class="field">Giảm trừ từ tháng<input id="np-f" type="month"></label><button class="btn pri">Thêm</button></form>`:""}<p class="hint">Số người phụ thuộc đang giảm trừ (${P.filter(p=>p.tt!=="Thôi").length}) tự dùng khi tính thuế trong bảng lương.</p>`}
  if(NVF.tab==="vb"){const V=n.vb||[];body=`${tbl(["STT","Loại văn bản","Số văn bản","Ngày ban hành","Ngày hiệu lực","Nội dung",""],V.map((v,i)=>`<tr><td>${i+1}</td><td>${esc(v.loai)}</td><td class="mono">${esc(v.so)}</td><td>${vndate(v.ngay)}</td><td>${vndate(v.hieuLuc)}</td><td>${esc(v.nd||"")}</td><td>${ed?`<button class="btn sm" data-vbx="${i}">Xóa</button>`:""}</td></tr>`))}
   ${ed?`<form class="frm row7" id="vbf"><label class="field">Loại<select id="vb-l">${opt(["Hợp đồng lao động","Phụ lục hợp đồng","Quyết định tăng lương","Quyết định bổ nhiệm","Quyết định điều chuyển","Quyết định thôi việc","Khác"],"Hợp đồng lao động")}</select></label><label class="field">Số văn bản<input id="vb-s"></label><label class="field">Ngày ban hành<input id="vb-n" type="date"></label><label class="field">Ngày hiệu lực<input id="vb-h" type="date"></label><label class="field grow">Nội dung<input id="vb-d"></label><button class="btn pri">Thêm</button></form>`:""}`}
  if(NVF.tab==="kt"){const K=n.ktkl||[];body=`${tbl(["Ngày","Loại","Nội dung","Số quyết định","Số tiền",""],K.map((k,i)=>`<tr><td>${vndate(k.ngay)}</td><td>${pill(k.loai,k.loai==="Khen thưởng"?"grn":"red")}</td><td>${esc(k.nd)}</td><td class="mono">${esc(k.so||"")}</td><td class="n">${k.tien?nf(k.tien):""}</td><td>${ed?`<button class="btn sm" data-ktx="${i}">Xóa</button>`:""}</td></tr>`))}
   ${ed?`<form class="frm row7" id="ktf"><label class="field">Ngày<input id="kt-n" type="date" value="${hrNow().iso}"></label><label class="field">Loại<select id="kt-l">${opt(["Khen thưởng","Kỷ luật"],"Khen thưởng")}</select></label><label class="field grow">Nội dung<input id="kt-d" required></label><label class="field">Số quyết định<input id="kt-s"></label><label class="field">Số tiền<input id="kt-t" inputmode="numeric"></label><button class="btn pri">Thêm</button></form>`:""}<p class="hint">Kỷ luật ghi ở đây được dùng cho cửa "Không kỷ luật" khi xét bậc.</p>`}
  if(NVF.tab==="file")body=`${NVFILES.busy?`<p class="hint">Đang tải danh sách file…</p>`:tbl(["Loại","Tên file","Dung lượng","Ngày tải lên",""],NVFILES.L.map(f=>`<tr><td>${esc((FKIND.find(k=>k[0]===f.kind)||["","Khác"])[1])}</td><td><a href="/api/hub/hr/files/${f.id}" target="_blank" rel="noopener">${esc(f.name)}</a></td><td class="n">${Math.max(1,Math.round(f.size/1024))} KB</td><td>${vndate(f.created_at)}</td><td>${ed?`<button class="btn sm" data-fx="${f.id}">Xóa</button>`:""}</td></tr>`))}
   ${ed?`<div class="filters"><select id="up-k">${opt(FKIND,"hd")}</select><label class="btn pri">+ Thêm file<input type="file" accept="image/*,application/pdf" data-up="" hidden></label><span class="hint">Ảnh hoặc PDF, mỗi file tối đa 1,5 MB</span></div>`:""}`;
  if(NVF.tab==="ls")body=tbl(["Thời gian","Người sửa","Nội dung"],(n.ls||[]).map(l=>`<tr><td>${esc(l.t)}</td><td>${esc(l.who)}</td><td>${esc(l.msg)}</td></tr>`));
  return `<section class="card nv-hs" id="nv-hs"><div class="card-h"><h2>Hồ sơ nhân viên · <span class="mono">${x.ma}</span> · ${esc(x.ten)}</h2>${pill(x.tt||"",ttTone(x.tt))}<span class="sp"></span><button class="btn sm" id="nv-print">In hồ sơ</button></div>
   <div class="nv-hsw"><nav class="nv-tabs">${tabs.map(([k,t])=>`<button data-nvt="${k}" class="${NVF.tab===k?"on":""}">${t}</button>`).join("")}</nav><div class="nv-body">${body}</div></div></section>`;
}
function nvBind(ma,ed){
  const m=$("#main");m.querySelectorAll("[data-nvt]").forEach(b=>b.onclick=()=>{NVF.tab=b.dataset.nvt;renderMain()});m.querySelectorAll("[data-nved]").forEach(b=>b.onclick=()=>{NVF.edit=b.dataset.nved;renderMain()});
  $("#nv-print").onclick=()=>nvPrintHS(ma);
  if(!ed)return;const nm=staffBy(ma).ten,num=v=>+String(v).replace(/[^\d]/g,"")||0;
  m.querySelectorAll("[data-hsf]").forEach(i=>i.onchange=()=>{const k=i.dataset.hsf,l=(HSK.concat(LDK).find(f=>f[0]===k)||[k,k])[1],t=(LDK.find(f=>f[0]===k)||[])[2];
    DB.mutate(ME.name,`sửa hồ sơ ${nm}: ${l}`,dt=>{const n=dt.hr.ns[ma]=dt.hr.ns[ma]||{};if(LDK.some(f=>f[0]===k)){const old=n[k];n[k]=t==="n"?num(i.value):i.value;nvLog(dt,ma,`${l}: ${t==="n"?nf(old):old||"—"} → ${t==="n"?nf(n[k]):n[k]||"—"}`)}else{n.hs=n.hs||{};const old=n.hs[k];n.hs[k]=i.value.trim();nvLog(dt,ma,`${l}: ${old||"—"} → ${n.hs[k]||"—"}`)}});toast("Đã lưu")});
  m.querySelectorAll("[data-hdf]").forEach(i=>i.onchange=()=>{DB.mutate(ME.name,`sửa hợp đồng ${nm}`,dt=>{const n=dt.hr.ns[ma]=dt.hr.ns[ma]||{};n.hd=n.hd||{};n.hd[i.dataset.hdf]=i.value;nvLog(dt,ma,`Hợp đồng · ${i.dataset.hdf}: ${i.value||"—"}`)});toast("Đã lưu")});
  m.querySelectorAll("[data-stf]").forEach(i=>i.onchange=()=>{const f=i.dataset.stf;DB.mutate(ME.name,`sửa hồ sơ ${nm}`,dt=>{const r=dt.staff.find(v=>v.ma===ma);const old=r[f];r[f]=i.value;if(f==="pb")r.khoi=(dt.departments.find(p=>p.k===i.value)||{}).khoi||r.khoi;nvLog(dt,ma,`${{ten:"Họ tên",pb:"Phòng ban",viTri:"Vị trí",ngayVao:"Ngày vào làm",tt:"Trạng thái"}[f]}: ${old||"—"} → ${i.value||"—"}`)});toast("Đã lưu");if(f!=="ngayVao")renderMain()});
  if($("#nptf"))$("#nptf").onsubmit=e=>{e.preventDefault();DB.mutate(ME.name,`thêm người phụ thuộc cho ${nm}`,dt=>{const n=dt.hr.ns[ma]=dt.hr.ns[ma]||{};n.npts=n.npts||[];n.npts.push({ten:$("#np-t").value.trim(),qh:$("#np-q").value,ngaySinh:$("#np-s").value,mst:$("#np-m").value.trim(),tu:$("#np-f").value,tt:"Đang"});n.npt=n.npts.filter(p=>p.tt!=="Thôi").length;nvLog(dt,ma,"Thêm người phụ thuộc: "+$("#np-t").value)});renderMain()};
  m.querySelectorAll("[data-nptx]").forEach(b=>b.onclick=()=>{DB.mutate(ME.name,`đổi giảm trừ người phụ thuộc ${nm}`,dt=>{const n=dt.hr.ns[ma],p=n.npts[+b.dataset.nptx];p.tt=p.tt==="Thôi"?"Đang":"Thôi";n.npt=n.npts.filter(q=>q.tt!=="Thôi").length;nvLog(dt,ma,`${p.ten}: ${p.tt==="Thôi"?"thôi":"giảm trừ lại"}`)});renderMain()});
  if($("#vbf"))$("#vbf").onsubmit=e=>{e.preventDefault();DB.mutate(ME.name,`thêm văn bản cho ${nm}`,dt=>{const n=dt.hr.ns[ma]=dt.hr.ns[ma]||{};n.vb=n.vb||[];n.vb.push({loai:$("#vb-l").value,so:$("#vb-s").value.trim(),ngay:$("#vb-n").value,hieuLuc:$("#vb-h").value,nd:$("#vb-d").value.trim()});nvLog(dt,ma,`Thêm ${$("#vb-l").value} ${$("#vb-s").value}`)});renderMain()};
  m.querySelectorAll("[data-vbx]").forEach(b=>b.onclick=()=>{if(!confirm("Xóa văn bản này?"))return;DB.mutate(ME.name,`xóa văn bản của ${nm}`,dt=>{const v=dt.hr.ns[ma].vb.splice(+b.dataset.vbx,1)[0];nvLog(dt,ma,`Xóa ${v.loai} ${v.so}`)});renderMain()});
  if($("#ktf"))$("#ktf").onsubmit=e=>{e.preventDefault();DB.mutate(ME.name,`ghi khen thưởng / kỷ luật cho ${nm}`,dt=>{const n=dt.hr.ns[ma]=dt.hr.ns[ma]||{};n.ktkl=n.ktkl||[];n.ktkl.unshift({ngay:$("#kt-n").value,loai:$("#kt-l").value,nd:$("#kt-d").value.trim(),so:$("#kt-s").value.trim(),tien:num($("#kt-t").value)});nvLog(dt,ma,`${$("#kt-l").value}: ${$("#kt-d").value}`)});renderMain()};
  m.querySelectorAll("[data-ktx]").forEach(b=>b.onclick=()=>{if(!confirm("Xóa dòng này?"))return;DB.mutate(ME.name,`xóa khen thưởng / kỷ luật của ${nm}`,dt=>{const k=dt.hr.ns[ma].ktkl.splice(+b.dataset.ktx,1)[0];nvLog(dt,ma,`Xóa ${k.loai}: ${k.nd}`)});renderMain()});
  m.querySelectorAll("[data-up]").forEach(i=>i.onchange=async()=>{const f=i.files[0];if(!f)return;if(f.size>1.5e6){toast("File quá 1,5 MB");return}const kind=i.dataset.up||$("#up-k").value,fd=new FormData();fd.append("file",f);fd.append("ma",ma);fd.append("kind",kind);toast("Đang tải lên…");
    try{const r=await fetch("/api/hub/hr/files",{method:"POST",body:fd,credentials:"same-origin"});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error((j.error&&j.error.message)||"Lỗi tải lên");DB.mutate(ME.name,`thêm file cho ${nm}`,dt=>nvLog(dt,ma,`Thêm file: ${f.name}`));toast("Đã tải lên");nvLoadFiles(ma,true)}catch(e){toast(e.message)}});
  m.querySelectorAll("[data-fx]").forEach(b=>b.onclick=async()=>{if(!confirm("Xóa file này?"))return;try{await svApi("/api/hub/hr/files/"+b.dataset.fx,{method:"DELETE"});const f=NVFILES.L.find(x=>x.id===b.dataset.fx);DB.mutate(ME.name,`xóa file của ${nm}`,dt=>nvLog(dt,ma,`Xóa file: ${f?f.name:""}`));nvLoadFiles(ma,true)}catch(e){toast("Không xóa được")}});
}
function nvAddForm(){
  const d=D();openDrawerHTML(`<h2>Thêm nhân viên</h2><form class="frm" id="nvaf"><label class="field">Họ và tên<input id="na-n" required></label><label class="field">Phòng ban<select id="na-p">${opt(d.departments.map(p=>[p.k,p.n]),NVF.pb||"")}</select></label><label class="field">Vị trí<input id="na-v"></label><label class="field">Ngày vào làm<input id="na-d" type="date" value="${hrNow().iso}"></label><label class="field">Trạng thái<select id="na-t">${opt(["Thử việc","Chính thức","Theo giờ"],"Thử việc")}</select></label><div class="acts"><button class="btn pri">Thêm</button></div></form><p class="hint">Thêm xong, hồ sơ người này mở ra bên dưới danh sách để điền CCCD, MST, hợp đồng, lương.</p>`);
  $("#nvaf").onsubmit=e=>{e.preventDefault();const pb=$("#na-p").value,ten=$("#na-n").value.trim();let ma="";DB.mutate(ME.name,"thêm nhân sự "+ten,dt=>{const n=Math.max(0,...dt.staff.map(x=>+String(x.ma).replace(/\D/g,"")||0))+1;ma="NV"+String(n).padStart(3,"0");dt.staff.push({ma,ten,khoi:(dt.departments.find(p=>p.k===pb)||{}).khoi||"Văn phòng",pb,viTri:$("#na-v").value,ql:"",ngayVao:$("#na-d").value,tt:$("#na-t").value,hd:"",nghe:"",bac:""});nvLog(dt,ma,"Tạo hồ sơ")});closeDrawer();NVF.sel=ma;NVF.tab="chung";renderMain()};
}
function nvRows(L){return L.map((x,i)=>{const n=nvNs(x.ma),h=n.hs||{},hd=n.hd||{};return [i+1,x.ma,x.ten,h.gioi||n.gioi||"",vndate(h.ngaySinh),pbName(x.pb),x.viTri||"",vndate(x.ngayVao),hd.loai||"",vndate(hd.het),h.cccd||"",h.mst||"",h.sdt||"",h.email||"",h.stk||"",h.nh||"",n.luong||0,nptOf(x.ma).filter(p=>p.tt!=="Thôi").length,x.tt||""]})}
const NV_HEAD=["STT","Mã NV","Họ và tên","Giới tính","Ngày sinh","Phòng ban","Vị trí","Ngày vào làm","Loại HĐ","Hết hạn HĐ","CCCD","MST","Điện thoại","Email","Số tài khoản","Ngân hàng","Lương cơ bản","Người phụ thuộc","Trạng thái"];
function nvExcel(L){if(typeof XLSX==="undefined"){toast("Cần mạng để xuất Excel");return}const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([NV_HEAD].concat(nvRows(L))),"NhanVien");XLSX.writeFile(wb,`Danh-sach-nhan-vien-${hrNow().iso}.xlsx`)}
function nvPrint(title,html){const w=window.open("","_blank");if(!w){toast("Trình duyệt chặn cửa sổ in");return}w.document.write(`<!doctype html><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:Arial,sans-serif;padding:20px;color:#14213d;font-size:12px}h1{font-size:18px}h2{font-size:14px;margin:16px 0 6px;border-bottom:1px solid #ccd}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ccd;padding:4px 6px;text-align:left}th{background:#eef}.kv td:first-child{width:35%;color:#556}</style>${html}<script>onload=()=>print()<\/script>`);w.document.close()}
function nvPrintList(L){nvPrint("Danh sach nhan vien",`<h1>DANH SÁCH NHÂN VIÊN — AILLA VIỆT NAM</h1><p>Ngày in ${vndate(hrNow().iso)} · ${L.length} người</p><table><tr>${NV_HEAD.slice(0,10).concat(["Trạng thái"]).map(h=>`<th>${h}</th>`).join("")}</tr>${nvRows(L).map(r=>`<tr>${r.slice(0,10).concat([r[18]]).map(c=>`<td>${esc(String(c))}</td>`).join("")}</tr>`).join("")}</table>`)}
function nvPrintHS(ma){const x=staffBy(ma),n=nvNs(ma),h=n.hs||{},hd=n.hd||{};const kv=L=>`<table class="kv">${L.map(([a,b])=>`<tr><td>${a}</td><td>${esc(String(b??"")||"—")}</td></tr>`).join("")}</table>`;
  nvPrint("Ho so "+ma,`<h1>HỒ SƠ NHÂN VIÊN · ${x.ma} · ${esc(x.ten)}</h1><h2>Thông tin cá nhân</h2>${kv(HSK.map(([k,l,t])=>[l,t==="date"?vndate(h[k]):k==="gioi"?h.gioi||n.gioi:h[k]]))}<h2>Thông tin lao động</h2>${kv([["Phòng ban",pbName(x.pb)],["Vị trí",x.viTri],["Ngày vào làm",vndate(x.ngayVao)],["Trạng thái",x.tt],["Loại hợp đồng",hd.loai],["Số hợp đồng",hd.so],["Ngày hết hạn",vndate(hd.het)]].concat(LDK.map(([k,l,t])=>[l,t==="n"?nf(n[k]):n[k]])))}
  <h2>Người phụ thuộc</h2><table><tr><th>Họ tên</th><th>Quan hệ</th><th>Ngày sinh</th><th>MST</th><th>Trạng thái</th></tr>${nptOf(ma).map(p=>`<tr><td>${esc(p.ten)}</td><td>${esc(p.qh)}</td><td>${vndate(p.ngaySinh)}</td><td>${esc(p.mst||"")}</td><td>${p.tt==="Thôi"?"Thôi":"Đang giảm trừ"}</td></tr>`).join("")}</table>
  <h2>Hợp đồng – quyết định</h2><table><tr><th>Loại</th><th>Số</th><th>Ngày ban hành</th><th>Hiệu lực</th><th>Nội dung</th></tr>${(n.vb||[]).map(v=>`<tr><td>${esc(v.loai)}</td><td>${esc(v.so)}</td><td>${vndate(v.ngay)}</td><td>${vndate(v.hieuLuc)}</td><td>${esc(v.nd||"")}</td></tr>`).join("")}</table>
  <h2>Khen thưởng – kỷ luật</h2><table><tr><th>Ngày</th><th>Loại</th><th>Nội dung</th><th>Số QĐ</th></tr>${(n.ktkl||[]).map(k=>`<tr><td>${vndate(k.ngay)}</td><td>${esc(k.loai)}</td><td>${esc(k.nd)}</td><td>${esc(k.so||"")}</td></tr>`).join("")}</table>`)}
/* Nạp HR MASTER: lấy thêm CCCD, MST, liên lạc, ngân hàng, ngày sinh nếu file có cột tương ứng. */
{const _imp=importHR;importHR=function(S){const r=_imp(S);const rows=tableOf(S["01_NhanSu"]||[]);const col=(row,re)=>{const k=Object.keys(row).find(k=>re.test(k));return k?String(row[k]??"").trim():""};
  rows.filter(x=>/^NV/.test(x["Mã NS"]||"")).forEach(x=>{const n=r.out.ns[x["Mã NS"]];if(!n)return;const hs={gioi:n.gioi||"",ngaySinh:dstr(x[Object.keys(x).find(k=>/ngày sinh/i.test(k))]||""),cccd:col(x,/cccd|căn cước|cmnd/i),ngayCap:dstr(x[Object.keys(x).find(k=>/ngày cấp/i.test(k))]||""),noiCap:col(x,/nơi cấp/i),mst:col(x,/mã số thuế|^mst/i),sdt:col(x,/điện thoại|sđt/i),email:col(x,/email/i),diaChi:col(x,/địa chỉ/i),stk:col(x,/số tk|số tài khoản|tài khoản ngân hàng|stk/i),nh:col(x,/^ngân hàng|tên ngân hàng/i)};Object.keys(hs).forEach(k=>{if(!hs[k])delete hs[k]});n.hs=hs});return r}}
/* Giữ hồ sơ đã sửa tay khi nạp lại file: chỉ ghi đè ô file có số. */
{const _np=pHrNap;pHrNap=function(m){_np(m);const s=m.querySelector(".ph-sub");if(s)s.textContent="Dữ liệu cất ở ngăn riêng trên máy chủ: chỉ CEO, kế toán và HCNS xem được"}}
/* Menu: "Hồ sơ nhân sự" thay bằng trang Nhân viên; kế toán & CEO (SV.hrOk) cũng vào được phần hồ sơ, lương. */
{const hr=MODULES.find(m=>m.k==="hr");if(hr){const g0=hr.groups;hr.groups=()=>g0().map(([g,its])=>[g,its.map(i=>i[0]==="hoso"?MI("hr_nv","Nhân viên",()=>hrOk()):["hr_tq","hr_hd","hr_bl","hr_pl","hr_cdl","hr_nap","hr_cc","hr_xb"].includes(i[0])?[i[0],i[1],u=>hrOk()&&(i[2](u)||u.role==="admin"||u.phongBan==="HCNS"||can(u,"luong.quanly")),i[3]]:i)])}}
{const _al=svAllowedMods;svAllowedMods=function(){const s=_al();if(s&&hrOk())s.add("hr");return s}}
PAGES.hr_nv=pHrNV;
{const _rm=renderMain;let done=false;renderMain=function(){_rm.apply(this,arguments);if(!done&&hrOk()&&DB.data&&ME){done=true;setTimeout(nvNhacHD,1500)}}}
/* ---------- Dữ liệu demo: 8 người mẫu (mã DM01…), đánh dấu demo:true để xóa sạch một lần ---------- */
const NV_DEMO=[["Nguyễn Văn An","Nam","1990-03-15","Kế toán trưởng","HĐLĐ không xác định thời hạn","2023-03-01","",20000000,"Chính thức"],["Trần Thị Bình","Nữ","1992-06-22","Nhân viên kinh doanh","HĐLĐ xác định thời hạn","2025-05-15","2026-10-30",12000000,"Chính thức"],["Lê Minh Cường","Nam","1988-11-08","Quản đốc xưởng","HĐLĐ xác định thời hạn","2024-04-10","2027-04-10",18000000,"Chính thức"],["Phạm Thu Dung","Nữ","1995-09-27","Nhân viên HCNS","Thử việc","2026-09-01","2026-10-31",11000000,"Thử việc"],["Hoàng Văn Em","Nam","1993-01-12","Kỹ thuật pha chế","HĐLĐ xác định thời hạn","2025-02-03","2026-11-03",14000000,"Chính thức"],["Nguyễn Thị Hà","Nữ","1997-08-06","Trưởng nhóm Content","HĐLĐ xác định thời hạn","2023-09-01","2027-09-01",16000000,"Chính thức"],["Đỗ Quang Huy","Nam","1990-12-19","Công nhân đóng gói","Thời vụ / theo giờ","2025-04-15","",0,"Theo giờ"],["Vũ Thị Lan","Nữ","1994-04-02","Chăm sóc khách hàng","HĐLĐ xác định thời hạn","2024-07-01","2026-07-01",9500000,"Đã nghỉ"]];
function nvDemoAdd(){DB.mutate(ME.name,"nạp dữ liệu nhân viên demo",dt=>{const P=dt.departments;NV_DEMO.forEach((r,i)=>{const ma="DM"+String(i+1).padStart(2,"0");if(dt.staff.some(x=>x.ma===ma))return;const pb=(P[i%P.length]||{}).k||"";dt.staff.push({ma,ten:r[0]+" (demo)",khoi:(P[i%P.length]||{}).khoi||"Văn phòng",pb,viTri:r[3],ql:"",ngayVao:r[5],tt:r[8],hd:"",nghe:"",bac:"",demo:true});
  dt.hr.ns[ma]={demo:true,luong:r[7],nenBH:r[7],pcCV:i%3?0:3000000,pcKhac:1000000,bac:["L2a","L1b","L3a","L1a","L2b","L3b","",""][i],hinhThuc:"Chuyển khoản",noiLam:"Văn phòng Hà Nội",hd:{loai:r[4],so:`0${i+1}/2025/HĐLĐ`,ky:r[5],het:r[6]},hs:{gioi:r[1],ngaySinh:r[2],cccd:i===3?"":"0010900"+String(12345+i),ngayCap:"2021-06-12",noiCap:"Cục CS QLHC",mst:i===4||i===6?"":"80"+String(34567890+i),sdt:"0903 123 4"+i+"6",email:"demo"+(i+1)+"@ailla.vn",diaChi:"Hà Nội",stk:i===6?"":"10234567"+i,nh:i===6?"":"Vietcombank"},
   npts:i===0?[{ten:"Nguyễn Minh Anh",qh:"Con",ngaySinh:"2018-05-10",mst:"8888888888",tu:"2026-01",tt:"Đang"},{ten:"Trần Thị Hoa",qh:"Vợ",ngaySinh:"1992-09-12",mst:"",tu:"2026-01",tt:"Đang"}]:[],npt:i===0?2:0,
   vb:[{loai:"Hợp đồng lao động",so:`0${i+1}/2025/HĐLĐ`,ngay:r[5],hieuLuc:r[5],nd:r[4]}].concat(i===0?[{loai:"Quyết định tăng lương",so:"15/2026/QĐ",ngay:"2026-06-15",hieuLuc:"2026-06-15",nd:"Tăng lên 20.000.000"}]:[]),
   ktkl:i===5?[{ngay:"2026-08-30",loai:"Khen thưởng",nd:"Video win tháng 8",so:"",tien:500000}]:[],ls:[{t:new Date().toLocaleString("vi-VN"),who:ME.name,msg:"Tạo hồ sơ demo"}]}})});NVF.sel="DM01";toast("Đã nạp 8 nhân viên demo");renderMain()}
function nvDemoDel(){if(!confirm("Xóa toàn bộ nhân viên demo (mã DM…)? Dữ liệu thật không bị đụng tới."))return;DB.mutate(ME.name,"xóa dữ liệu nhân viên demo",dt=>{const ids=dt.staff.filter(x=>x.demo).map(x=>x.ma);dt.staff=dt.staff.filter(x=>!x.demo);ids.forEach(ma=>{delete dt.hr.ns[ma];Object.keys(dt.hr.nhac||{}).forEach(k=>{if(k.startsWith(ma+"|"))delete dt.hr.nhac[k]})})});NVF.sel="";toast("Đã xóa dữ liệu demo");renderMain()}
{const _p=pHrNV;pHrNV=function(m){_p(m);if(!hrOk()||!(can(ME,"nhansu.quanly")||ME.role==="admin"||ME.phongBan==="HCNS"))return;const has=D().staff.some(x=>x.demo),h=m.querySelector(".card.flush .card-h");if(!h)return;h.insertAdjacentHTML("beforeend",has?`<button class="btn sm" id="nv-demo-x" style="color:var(--red)">Xóa dữ liệu demo</button>`:`<button class="btn sm" id="nv-demo">Nạp dữ liệu demo</button>`);if($("#nv-demo"))$("#nv-demo").onclick=nvDemoAdd;if($("#nv-demo-x"))$("#nv-demo-x").onclick=nvDemoDel}}
PAGES.hr_nv=pHrNV;
