/* =====================================================================
   KẾ HOẠCH THÁNG › BƯỚC 5 › ② PILLAR & TUYẾN
   Mỗi sản phẩm ở mỗi kênh (chọn ở ①) là một pillar. Trong pillar là các dòng tuyến:
   tuyến nội dung (demo, so sánh, đóng gói, HDSD, giải đáp, combat, khuyến mại…) · vai trò
   (giáo dục khách, phá rào cản, kêu gọi vào live…) · số lượng kế hoạch · định dạng.
   Video phát sinh khi đi quay được ghi thêm vào tuyến; mỗi tuyến hiện thừa / thiếu so với kế hoạch.
   ===================================================================== */
const TUYEN_GOIY=["Demo sản phẩm","So sánh sản phẩm","Quy trình đóng gói","Hướng dẫn sử dụng","Giải đáp thắc mắc","Combat","Khuyến mại","Trước/sau","Review / feedback khách","Pain/Insight","Bí quyết chuyên gia","Chọn mùi/Lifestyle","Nhân bản winner","Đăng lại video kho","Đổi hook video tồn"];
const VAITRO_GOIY=["Giáo dục khách hàng","Phá rào cản mua hàng","Kêu gọi mua ngay","Kêu gọi vào live","Tăng niềm tin","Giữ chân khách cũ","Test góc mới"];
/* Pillar "Thương hiệu Ailla" (branding) có bộ tuyến và vai trò riêng */
const TUYEN_TH=["Câu chuyện thương hiệu","Nhà máy & quy trình sản xuất","Đội ngũ Ailla","Giá trị Sạch & Lành","Mẹo hay gia đình","Khách hàng nói về Ailla","Chứng nhận & giải thưởng","Hoạt động cộng đồng","Sự kiện, ngày lễ","Hậu trường"];
const VAITRO_TH=["Tăng nhận diện thương hiệu","Tăng niềm tin","Gắn kết cộng đồng","Kéo người theo dõi page","Chăm sóc khách cũ","Tuyển đại lý / đối tác"];
let PT_K="",PT_ED=false;const PT_OPEN=new Set();
/* Danh sách gợi ý sửa được: lưu trong dữ liệu chung (settings.goiy), chưa sửa thì dùng danh sách mặc định */
const GOIY_DEF={tuyen:TUYEN_GOIY,vaitro:VAITRO_GOIY,tuyenTH:TUYEN_TH,vaitroTH:VAITRO_TH,dd:LISTS.dangVideo.filter(x=>!["Bài ảnh","Carousel"].includes(x)),ddFB:LISTS.fbFormat};
const goiy=k=>{const g=(D().settings||{}).goiy;return g&&Array.isArray(g[k])?g[k]:GOIY_DEF[k]};
function goiyAdd(dt,k,v){v=(v||"").trim();if(!v)return false;dt.settings.goiy=dt.settings.goiy||{};const L=Array.isArray(dt.settings.goiy[k])?dt.settings.goiy[k]:GOIY_DEF[k].slice();if(L.some(x=>x.toLowerCase()===v.toLowerCase()))return false;dt.settings.goiy[k]=L.concat(v);return true}
const ptPairs=()=>{const o=[];prods().forEach(p=>pKenhs(p).forEach(e=>o.push({sku:p.k,kenh:e.kenh,huong:e.huong,sl:+e.sl||0})));return o};
/* So tổng số video các tuyến với KPI số video của sản phẩm ở kênh */
const ptVs=(kpi,kh)=>!kpi?pill("Chưa đặt KPI","gry"):kh===kpi?pill("Đủ KPI","grn"):kh<kpi?pill("Còn thiếu "+(kpi-kh)+" video","amb"):pill("Vượt "+(kh-kpi)+" video","vio");
const ptPil=(d,sku,kenh)=>(d.pillars||[]).find(x=>x.sku===sku&&x.kenh===kenh);
function ptEnsure(dt,sku,kenh){let p=ptPil(dt,sku,kenh);if(!p){p={ma:"PIL-"+MONTH.key.slice(2).replace("-","")+"-"+String(dt.pillars.length+1).padStart(2,"0"),sku,kenh,vaiTro:"",mucTieu:"",kh:0,dinhDang:"",idea:"",nguoi:"",ghiChu:""};dt.pillars.push(p)}return p}
const ptFmt=kenh=>chOf(kenh).needId?LISTS.dangVideo.filter(x=>!["Bài ảnh","Carousel"].includes(x)):LISTS.fbFormat;
function ptHtml(d,ed){
  const pairs=ptPairs(),chs=CHANNELS.filter(ch=>pairs.some(x=>x.kenh===ch.k));
  if(!PT_K||!chs.some(c=>c.k===PT_K))PT_K=(chs[0]||{}).k||"";
  const P=pairs.filter(x=>x.kenh===PT_K);
  const block=x=>{const pl=ptPil(d,x.sku,x.kenh)||{},T=d.tuyen.map((t,i)=>[t,i]).filter(([t])=>t.kenh===x.kenh&&t.sku===x.sku),key=x.sku+"|"+x.kenh;
    const C=d.cards.filter(c=>c.kenh===x.kenh&&c.sku===x.sku),kh=sum(T,([t])=>t.kh),xong=C.filter(c=>c.step==="xong").length;
    const rows=T.map(([t,i])=>{const cs=C.filter(c=>c.maTuyen===t.ma),dn=cs.filter(c=>c.step==="xong").length,ps=cs.filter(c=>c.phatSinh).length,diff=cs.length-t.kh;
      const chenh=diff>0?pill("+"+diff+" phát sinh","vio"):diff<0&&d.plan.published?pill("thiếu "+(-diff)+" thẻ","amb"):"";
      return `<tr><td>${ed?`<input list="${x.sku==="TH"?"dl-tuyen-th":"dl-tuyen"}" data-tu2="${i}" data-f="tuyen" value="${esc(t.tuyen)}">`:esc(t.tuyen)}<small class="mono">${esc(t.ma)}</small></td>
       <td>${ed?`<input list="${x.sku==="TH"?"dl-vaitro-th":"dl-vaitro"}" data-tu2="${i}" data-f="vaiTro" value="${esc(t.vaiTro||"")}">`:esc(t.vaiTro||"")}</td>
       <td class="n">${ed?`<input class="num" type="number" min="0" data-tu2="${i}" data-f="kh" value="${t.kh}">`:t.kh}</td>
       <td>${ed?`<input list="${chOf(x.kenh).needId?"dl-dd":"dl-ddfb"}" data-tu2="${i}" data-f="dangVideo" value="${esc(t.dangVideo||"")}" placeholder="Định dạng">`:esc(t.dangVideo||"—")}</td>
       <td class="n"><button type="button" class="lnk" data-gotuyen="${esc(t.ma)}">${cs.length} thẻ</button><small>${dn} đã đăng${ps?` · ${ps} phát sinh`:""}</small></td>
       <td>${chenh}</td>
       <td class="nowrap">${ed?`<button class="btn sm" data-tps="${i}" title="Ghi thêm 1 video ngoài kế hoạch cho tuyến này">+ Phát sinh</button> ${cs.length?"":`<button class="lnk danger" data-tdel2="${i}">Xóa</button>`}`:""}</td></tr>`}).join("");
    const op=PT_OPEN.has(key);return `<div class="ptb${op?" open":""}"><div class="pth" data-ptopen="${esc(key)}"><i class="ptar">${op?"▾":"▸"}</i>${swatch(x.sku)}<b>${esc(sk(x.sku).n)}</b>${x.sku==="TH"?pill("Branding","vio"):""}${pill(x.huong,x.huong==="Đẩy mạnh"?"pnk":x.huong==="Test"||x.huong==="Đẩy nhẹ"?"amb":"gry")}<span class="ptkpi">KPI ${ed?`<input type="number" min="0" class="num" data-pkpi="${esc(key)}" value="${x.sl||""}" placeholder="—">`:`<b>${x.sl||"—"}</b>`} video · các tuyến cộng <b>${kh}</b> ${ptVs(x.sl,kh)}</span><span class="sp"></span><span class="hint">có thẻ <b>${C.length}</b> · đã đăng <b>${xong}</b>${C.length>kh&&kh?` · <b class="t-vio">phát sinh +${C.length-kh}</b>`:""}</span></div>
     ${op?`<div class="ptbody"><div class="pti"><label>Big idea${ed?`<input data-pi="${esc(key)}" data-f="idea" value="${esc(pl.idea||"")}" placeholder="${x.sku==="TH"?"Ý lớn xuyên suốt, ví dụ: Ailla, Sạch & Lành cho cả nhà":"Ý lớn xuyên suốt pillar, ví dụ: bí quyết tiệm giặt về tận nhà"}">`:`<b>${esc(pl.idea||"—")}</b>`}</label><label>Ghi chú${ed?`<input data-pi="${esc(key)}" data-f="ghiChu" value="${esc(pl.ghiChu||"")}">`:`<span>${esc(pl.ghiChu||"")}</span>`}</label></div>
     <div class="tbl"><table class="pttab"><thead><tr><th>Tuyến nội dung</th><th>Vai trò</th><th class="n">Số lượng KH</th><th>Định dạng</th><th class="n">Thẻ</th><th>Thừa / thiếu</th><th></th></tr></thead><tbody>${rows||`<tr><td colspan="7" class="empty">Chưa có tuyến. Thêm ở dòng dưới.</td></tr>`}</tbody></table></div>
     ${ed?`<div class="ptadd" data-nf="${esc(key)}"><input list="${x.sku==="TH"?"dl-tuyen-th":"dl-tuyen"}" class="nt" placeholder="${x.sku==="TH"?"Tuyến thương hiệu (gõ hoặc chọn)":"Tuyến nội dung (gõ hoặc chọn)"}"><input list="${x.sku==="TH"?"dl-vaitro-th":"dl-vaitro"}" class="nv" placeholder="Vai trò"><input type="number" min="1" class="nn" value="4" title="Số lượng kế hoạch"><input list="${chOf(x.kenh).needId?"dl-dd":"dl-ddfb"}" class="nd" placeholder="Định dạng (gõ hoặc chọn)"><button class="btn sm pri" data-tnew="${esc(key)}">+ Thêm tuyến</button></div>`:""}</div>`:`<div class="ptmini">${T.map(([t])=>esc(t.tuyen)+" "+t.kh).join(" · ")||"Chưa có tuyến"} · <span class="lnk">bấm để mở</span></div>`}</div>`};
  return `<section class="card" id="ptsec"><div class="card-h"><h2>② Pillar & tuyến</h2><span class="hint">mỗi sản phẩm ở mỗi kênh (chọn ở ①) là một pillar · trong pillar ghi các tuyến: nội dung gì, vai trò gì, bao nhiêu video, định dạng nào</span>${ed?`<span class="sp"></span><button class="btn sm" id="pt-ed">${PT_ED?"Đóng danh sách gợi ý":"＋ Thêm / sửa danh sách tuyến, vai trò"}</button>`:""}</div>
   ${ed&&PT_ED?`<div class="gyed"><div class="gyhd"><b>Danh sách gợi ý tuyến, vai trò, định dạng</b><button class="btn sm" data-gyclose="1">✕ Đóng danh sách</button></div>${[["tuyen","Tuyến nội dung (bán hàng)"],["vaitro","Vai trò (bán hàng)"],["tuyenTH","Tuyến thương hiệu"],["vaitroTH","Vai trò thương hiệu"],["dd","Định dạng video (TikTok)"],["ddFB","Định dạng bài Fanpage"]].map(([k,t])=>`<div class="gyg"><b>${t}</b><div class="chips2">${goiy(k).map((v,i)=>`<span class="pchip">${esc(v)}<button class="lnk danger" data-gyx="${k}|${i}" title="Bỏ khỏi danh sách">✕</button></span>`).join("")}</div><div class="ptadd"><input class="gyi" data-gyk="${k}" placeholder="Gõ mục mới rồi bấm Thêm"><button class="btn sm pri" data-gya="${k}">+ Thêm</button></div></div>`).join("")}<p class="hint">Bỏ một mục khỏi danh sách không ảnh hưởng tuyến đã lập. Tuyến gõ mới khi thêm tuyến cũng tự được lưu vào danh sách.</p><div class="gyft"><button class="btn sm pri" data-gyclose="1">▲ Xong, đóng danh sách</button></div></div>`:""}
   ${chs.length?`<div class="seg ptk">${chs.map(ch=>`<button data-ptk="${esc(ch.k)}" class="${ch.k===PT_K?"on":""}">${esc(ch.short)} <span class="xbadge">${pairs.filter(x=>x.kenh===ch.k).length}</span></button>`).join("")}</div>`:""}
   ${P.length?(()=>{const K=sum(P,x=>x.sl),Kh=sum(d.tuyen.filter(t=>t.kenh===PT_K),t=>t.kh);return `<div class="ptsum"><b>${esc(chOf(PT_K).short)}</b> · KPI cả kênh <b>${K||"—"}</b> video · các tuyến cộng <b>${Kh}</b> ${ptVs(K,Kh)}</div>`})():""}${P.map(block).join("")||`<p class="empty">Chưa có sản phẩm nào ở ①. Thêm sản phẩm vào kênh trước, pillar sẽ tự hiện ở đây.</p>`}
   <datalist id="dl-tuyen">${goiy("tuyen").map(x=>`<option value="${esc(x)}">`).join("")}</datalist><datalist id="dl-vaitro">${goiy("vaitro").map(x=>`<option value="${esc(x)}">`).join("")}</datalist><datalist id="dl-dd">${goiy("dd").map(x=>`<option value="${esc(x)}">`).join("")}</datalist><datalist id="dl-ddfb">${goiy("ddFB").map(x=>`<option value="${esc(x)}">`).join("")}</datalist><datalist id="dl-tuyen-th">${goiy("tuyenTH").map(x=>`<option value="${esc(x)}">`).join("")}</datalist><datalist id="dl-vaitro-th">${goiy("vaitroTH").map(x=>`<option value="${esc(x)}">`).join("")}</datalist>
   ${ed?`<div class="acts"><button class="btn pri" id="pt-pub">Phát hành thẻ còn thiếu</button><span class="hint">Video phát sinh khi đi quay: bấm "+ Phát sinh" ở đúng tuyến, hoặc ghi ngay ở buổi quay (Xếp việc tuần › ③ Quay). Số kế hoạch giữ nguyên, phần thêm hiện là "phát sinh".</span></div>`:""}</section>`;
}
function ptBind(b){
  b.querySelectorAll("[data-ptopen]").forEach(h=>h.onclick=e=>{if(e.target.closest("input,select,button,a,textarea"))return;const k=h.dataset.ptopen;PT_OPEN.has(k)?PT_OPEN.delete(k):PT_OPEN.add(k);renderMain()});
  b.querySelectorAll("[data-ptk]").forEach(x=>x.onclick=()=>{PT_K=x.dataset.ptk;renderMain()});
  b.querySelectorAll("[data-pi]").forEach(x=>x.onchange=()=>{const [sku,kenh]=x.dataset.pi.split("|");DB.mutate(ME.name,"sửa pillar "+sk(sku).n,dt=>{ptEnsure(dt,sku,kenh)[x.dataset.f]=x.value});toast("Đã lưu")});
  b.querySelectorAll("[data-tu2]").forEach(x=>x.onchange=()=>{DB.mutate(ME.name,"sửa tuyến",dt=>{const t=dt.tuyen[+x.dataset.tu2],f=x.dataset.f,th=t.sku==="TH";t[f]=f==="kh"?Math.max(0,+x.value||0):x.value;if(f==="tuyen")goiyAdd(dt,th?"tuyenTH":"tuyen",x.value);if(f==="vaiTro")goiyAdd(dt,th?"vaitroTH":"vaitro",x.value);if(f==="dangVideo")goiyAdd(dt,chOf(t.kenh).needId?"dd":"ddFB",x.value)});toast("Đã lưu");renderMain()});
  b.querySelectorAll("[data-tnew]").forEach(x=>x.onclick=()=>{const [sku,kenh]=x.dataset.tnew.split("|"),f=x.closest(".ptadd"),tu=f.querySelector(".nt").value.trim();if(!tu){toast("Gõ hoặc chọn tuyến nội dung");f.querySelector(".nt").focus();return}
    DB.mutate(ME.name,"thêm tuyến "+tu,dt=>{ptEnsure(dt,sku,kenh);const th=sku==="TH";goiyAdd(dt,th?"tuyenTH":"tuyen",tu);goiyAdd(dt,th?"vaitroTH":"vaitro",f.querySelector(".nv").value);goiyAdd(dt,chOf(kenh).needId?"dd":"ddFB",f.querySelector(".nd").value);const n=dt.tuyen.filter(t=>t.sku===sku).length+1;let ma=`T${MONTH.mon}-${sku}-${String(n).padStart(2,"0")}`;while(dt.tuyen.some(t=>t.ma===ma))ma+="b";dt.tuyen.push({ma,kenh,sku,tuyen:tu,vaiTro:f.querySelector(".nv").value.trim(),kh:Math.max(1,+f.querySelector(".nn").value||1),dangVideo:f.querySelector(".nd").value,nguoi:"",kiemChung:"Giả thuyết",maInsight:"",ghiChu:""})});PT_OPEN.add(x.dataset.tnew);toast("Đã thêm tuyến "+tu);renderMain()});
  b.querySelectorAll("[data-tps]").forEach(x=>x.onclick=()=>{const t=D().tuyen[+x.dataset.tps];let id;DB.mutate(ME.name,"video phát sinh tuyến "+t.ma,dt=>{const c=newCard(dt,{sku:t.sku,kenh:t.kenh,maTuyen:t.ma,day:dt.settings.today,nguon:"Quay mới",loai:"moi",dangVideo:t.dangVideo||undefined,phatSinh:true});dt.cards.push(c);id=c.id});toast("Đã ghi 1 video phát sinh ("+id+"), giao người làm ở Xếp việc tuần");renderMain()});
  b.querySelectorAll("[data-tdel2]").forEach(x=>x.onclick=()=>{if(x.dataset.ok){DB.mutate(ME.name,"xóa tuyến",dt=>dt.tuyen.splice(+x.dataset.tdel2,1));renderMain()}else{x.dataset.ok=1;x.textContent="Bấm lần nữa để xóa"}});
  b.querySelectorAll("[data-pkpi]").forEach(x=>x.onchange=()=>{const [sku,kenh]=x.dataset.pkpi.split("|");DB.mutate(ME.name,"đặt KPI số video "+sk(sku).n+" · "+kenh,dt=>{const p=dt.products.find(y=>y.k===sku);if(!p)return;p.kenhs=pKenhs(p).map(e=>e.kenh===kenh?Object.assign({},e,{sl:Math.max(0,+x.value||0)}):e)});toast("Đã lưu KPI");renderMain()});
  if($("#pt-ed"))$("#pt-ed").onclick=()=>{PT_ED=!PT_ED;renderMain()};
  b.querySelectorAll("[data-gyclose]").forEach(x=>x.onclick=()=>{PT_ED=false;renderMain();const s=$("#ptsec");if(s)s.scrollIntoView({block:"start"})});
  b.querySelectorAll("[data-gya]").forEach(x=>x.onclick=()=>{const k=x.dataset.gya,i=b.querySelector(`.gyi[data-gyk="${k}"]`),v=i.value.trim();if(!v){toast("Gõ mục mới trước");i.focus();return}let ok=false;DB.mutate(ME.name,"thêm gợi ý "+v,dt=>{ok=goiyAdd(dt,k,v)});toast(ok?"Đã thêm "+v:"Mục này đã có");renderMain()});
  b.querySelectorAll(".gyi").forEach(i=>i.onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();b.querySelector(`[data-gya="${i.dataset.gyk}"]`).click()}});
  b.querySelectorAll("[data-gyx]").forEach(x=>x.onclick=()=>{const [k,i]=x.dataset.gyx.split("|");DB.mutate(ME.name,"bỏ gợi ý",dt=>{dt.settings.goiy=dt.settings.goiy||{};const L=(Array.isArray(dt.settings.goiy[k])?dt.settings.goiy[k]:GOIY_DEF[k]).slice();L.splice(+i,1);dt.settings.goiy[k]=L});renderMain()});
  if($("#pt-pub"))$("#pt-pub").onclick=()=>{let n=0;DB.mutate(ME.name,"phát hành thẻ",dt=>{n=publishPlan(dt)});toast(n?`Đã sinh ${n} thẻ vào bước Chưa giao`:"Đủ thẻ theo kế hoạch");renderMain()};
}
/* Thay bảng Pillar và bảng Tuyến cũ bằng khối Pillar & tuyến theo kênh (giữ ① Sản phẩm của hàm cũ) */
const _lichPillarOld=lichPillar;
lichPillar=function(b){_lichPillarOld(b);[...b.querySelectorAll("section.card")].slice(1).forEach(s=>s.remove());const ed=can(ME,"kehoach.sua");b.insertAdjacentHTML("beforeend",ptHtml(D(),ed));ptBind(b);bindCommon(b)};
